### ISSUE TITLE
[BUG] WONT TURN ON 

### ISSUE THREAD

**Issue by neshk16** [flybywiresim/a32nx#1001]
**Mod Version**

0.3.1

**Describe the bug**

I turned on the batteries and the ext power, but the displays will not turn on at all.

**To Reproduce**

1. batteries were turned on
2. ext power turned on
3. screen displays were put at highest brightness 

**Expected behavior**

expected displays to turn on
**Actual behavior**

displays didnt turn on

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Jamwoo91** [comment]
I get the same behaviour but for me it is every display in the cockpit, from the battery voltage levels to PFD's, Autopilot LCD, etc....

**Comment by Jasperuk** [comment]
I have the same issue

**Comment by neshk16** [comment]
> I have the same issue

You have to put the AI traffic density to 0 then it works.

**Comment by Jamwoo91** [comment]
> I get the same behaviour but for me it is every display in the cockpit, from the battery voltage levels to PFD's, Autopilot LCD, etc....

Just replaced the files and it now works for me, I thought I had the latest version but maybe not?

**Comment by JPZV** [comment]
This bug seems to be related with the amount of entities in the airport. For example, if I have everything on traffic settings at max, I can only turn on the A320 in my local airport (SCEL) as there is no much activity neither by the AI nor by the online players, but, if I try the same settings in Nagasaki (RJFU) where there is a lot of online players plus AI aircraft, I often (but not always) get this kind of bug.

Also, this could be related directly with MSFS2020 instead of the plugin itself, as this also happens with the stock A320.

Another weird thing is that none of the electrics works, including the ATC (if you turn on the batteries and the Ext. Pwr., you can hear a kind of whistling, but it's not the same sound as the AC, and the ATC screen will say that you have to turn on the electric system)

**Comment by wftinmn** [comment]
Same behavior here. Replaced the files today, and set all the AI traffic to zero. Still not working. Tried KORD and KMSP. Pretty weird.

**Comment by lousybyte** [comment]
We recommend disabling multiplayer, AI traffic, and ground AI, there's a known issue since the previous update in the base game.

**Comment by EsherDemo** [comment]
I tried all the settings and sug. in this thread, but still no reactions from the displays. :(

**Comment by NathanInnes** [comment]
Try running build.py

**Comment by Jasperuk** [comment]
I am an idiot, downloaded the a32nx-master and that seems to work fine on all screens in the cockpit

**Comment by hotshotp** [comment]
closing as issue not present anymore
