### ISSUE TITLE
Doors page no longer indicates when any door is open [BUG]

### ISSUE THREAD

**Issue by Ares1378** [flybywiresim/a32nx#1021]
**Mod Version**

Master

**Describe the bug**

Doors page no longer indicates doors open
**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by CaptainStraw** [comment]
I was just going to file a bug on this. 

I think the problem is that in the latest master versions, the open door indicators have changed from amber to green, possibly related to #911  or #937  ?

The actual A320 indicates open/unlocked doors with amber and locked doors with green, as can be seen here:
<img width="431" alt="Screen_Shot_2020-10-02_at_12 36 53" src="https://user-images.githubusercontent.com/8702738/94969325-25423b80-04c8-11eb-93cc-7dec52a1b7f0.png">

and also here:
[https://youtu.be/Mo7A3CuVb8g?t=103](url)

Some input from IRL A320 pilots would be helpful to confirm this.
