### ISSUE TITLE
[REQUEST] To allow user to setup the mod to his taste or possibilities (performances limits)

### ISSUE THREAD

**Issue by ACSoft47** [flybywiresim/a32nx#1073]
**Is your feature request related to a problem? Please describe.**

In this work, you have modifications with are not mandatory to reach the study level.

For example changing all the sounds will eventually  satisfy a lot true life A320 pilots, assuming the new sounds are really more realistic, but to my humble view, this has nothing to do with study level. The vast majority of the users never flied into an A320 cockpit. So they can only have a subjective feeling. A matter of taste if you prefer. So perhaps, they will prefer the old unrealistic vanilla sound, for thousand good reasons.

You can also have modifications which are completely outside the scope of the study level target. For example, a complete pax cabin. Probably, many users will love that (me included), but you may have some which will be happy to not have it, because this mod will probably have a great impact on the framerate and be reserved to lucky owner of alien PC.

**Describe the feature you'd like to see implemented**

For these reasons and other not mentioned here, I propose that A32NX mod become exclusively reserved to all modifications which are effectively growing the study level of the mod. All other mod should be OPTIONAL so the user can chose what he prefer. Even, why not, optional with multiple choices.

This can be done all in the same single mod with a way to parametrize, or more simply to separate into several mods what is really important for study level from what is secondary and/or be mainly a matter taste.

Nobody will cry if you add the missing pages. But some will do, if they don't like some sounds of have to simply forget this marvelous mod because of the frame rate impact.

Just a proposition of course !

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Please add a title.

In summary you want an option to change sounds or any misc features?

**Comment by NathanInnes** [comment]
I'm also seeing a lot of opinions in this request, to add. This is an OPEN SOURCE project meaning you can branch off and make your own variant on the aircraft and not be confined to what the community brings to the table. 

As a maintainer of the project, I personally don't merge things that serve little to no purpose in achieving the goal of making things better for people and I'm sure others are in the same boat.

**Comment by Benjozork** [comment]
> because this mod will probably have a great impact on the framerate and be reserved to lucky owner of alien PC.

No, that's not how it works. Models like passenger cabins are not rendered if the player is not inside them.

**Comment by ACSoft47** [comment]
@NathanInnes Sorry for the title, but I don't see were I can specify it. In summary I don't wan't nothing, I just propose what I consider to be an important improvement. And don't worry for me, I am a former FS freeware dev of the FS200X era and my personal variant is already made. But not everybody have the knowledge to do that, this is why I proposed that.

@Benjozork Of course, if the goal is not to please people... But, let me just tell you that you don't need to be rude in your comment and I definitively don't see how to have the possibility to change some default setup parameters, to eventually make the mod more to his taste may "piss of" the user (My mother language is not English and I hope that Google translator is wrong on this one, because it translated this in a very vulgar French expression "faire chier"). Those who don't care will just do nothing. Speaking of the passenger cabin this was just an example I had in mind, coming from the FS200X era. I am sure you are clever enough to found a lot of other features which might eat performances. It is always the case with mods like that. We will see with this one what happen in the future on this matter.

OK guys, you seem to not like my proposition, no problem, don't do it.

But just sad, because "who can the most, can the less", like we say in French.

**Comment by Benjozork** [comment]
I'll respond in french since that seems to be your first language.

Bien que je comprenne votre point de vue, le but de ce mod, comme je l'ai dit, ce n'est pas d'offrir une expérience facile. Je comprends très bien que les sons du cockpit, par exemple, ne sont pas nécéssairement "agréables". Mais ils sont réalistes. Comme certains collaborateurs d'ici vous ont déjà dit, plusieurs pilotes d'A320 nous ont confirmé maintes fois que ces sons sont réalistes. Et c'est ce qui est important ici.

Encore là, le but n'est pas de "piss off" l'utilisateur. Nous n'allons pas commencer à ajouter des fonctionnalités, comme celle que j'ai mentionné plus haut, que rendent l'expérience de jeu plus énervante, ça c'est clair... Mais en même temps. j'imagine qu'en tant que dev freeware tel que vous le mentionnez, vous comprenez que l'on ne peut pas commencer à ajouter des dizaines d'options dans le mod pour plaire aux goûts de chacuns. En fait, nous avons déja prévu une telle possibilité pour de gros changements (nous planifions par exemple une version avec l'EIS1 (vieux systèmes d'affichage) et les versions originales de l'A320). Le problème, c'est que lorsque l'on commence à parler de détails comme les sons et l'éclairage, on doit non seulement supporter un mod mais maintenant un kit de personnalisation d'A320 qui pourrait générer des milliers de combinaisons qui pourraient chacunes causer des problèmes innattendus.

Si quelqu'un cherche à faire un vol agréable sans se casser la tête, il peut prendre l'Airbus par défaut. Si il veut un appareil complexe mais sans rechercher la perfection "study level", il peut aller chez Aerosoft. Nous, chez FBW, on a décidé d'aller en classe à part et de faire les choses les plus réalistes possibles.

Je suis parfaitement d'accord avec l'idée mais simplement ce n'est pas possible pour l'instant. Il est déjà difficile de garder un appareil fonctionnel avec le bordel des mises à jour de MS et Asobo, commencer à introduire nos propres variations serait l'enfer.

Nous sommes ouverts à discuter des potentielles alternatives, par exemple un mode "facile" ou certaines choses comme les IRS sont désactivées. Mais tant que l'on à des gens qui veulent améliorer le réalisme, je ne vois pas comment des sons rendent l'expérience moins agréable.

Je m'excuse si mes propos en anglais semblent "rude", j'ai tendance à me bourrer dans les choix de mots avec la langue anglaise ;)

p.s.: if anyone wants a translation of the above text, I will provide it for the sake of transparency

**Comment by hotshotp** [comment]
Translation of above text (Google translate):

While I understand your point of view, the point of this mod, like I said, is not to provide an easy experience. I understand very well that the sounds of the cockpit, for example, are not necessarily "pleasant". But they are realistic. As some of our collaborators have already told you, several A320 pilots have repeatedly confirmed that these sounds are realistic. And that's what's important here.

Again, the goal is not to "piss off" the user. We're not going to start adding features, like the one I mentioned above, that make the gaming experience more annoying, that's clear ... But at the same time. I imagine that as a freeware dev as you mention it, you understand that one cannot start adding dozens of options in the mod to please everyone's tastes. In fact, we have already planned such a possibility for big changes (for example we are planning a version with the EIS1 (old display systems) and the original versions of the A320). The problem is, when you start talking about details like sounds and lighting, you not only have to support a mod but now an A320 customization kit that could generate thousands of combinations that each could. cause unexpected problems.

If someone is looking to have a pleasant flight without breaking their head, they can take the Airbus by default. If he wants a complex device but without looking for "study level" perfection, he can go to Aerosoft. We at FBW decided to go to a separate class and do the most realistic things possible.

I totally agree with the idea, but it's just not possible at the moment. It's hard enough to keep a working device running with the mess of updates from MS and Asobo, starting to introduce our own variations would be hell.

We are open to discussing potential alternatives, for example an "easy" mode or certain things like IRS are disabled. But as long as you have people who want to improve the realism, I don't see how sounds make the experience less enjoyable.

I apologize if my words in English seem "rude", I tend to get bogged down in the choice of words with the English language;)

=====================================

I totally agree, it would take lots of time to create separate combinations for everything. While for example, wind sounds might not be pleasant they are realistic.

**Comment by NathanInnes** [comment]
This issue is going to be closed. Further discussion about this can continue on discord. 

If you have a future request then feel free to open a new issue.

**Comment by ACSoft47** [comment]
Thanks to benjozork to have written in french and to hotshotp for the translation, but this was really not necessary. I mean, you don't need trying to convince me of anything and even to justify your position. I propose something, then you decide if you adopt or not the idea.

To separate the project in 2 different mods, one who is exclusively devoted to the avionic systems (I call it the study level target) and a second one, for the hyper-realism (I call this the cosmetic part) is most probably not so complicate, like you all 3 pretend and perfectly feasible. Yes it is an open source project and in theory, anybody can build its own version. But you know perfectly that the vast majority of users are not going to do that, because it require a lot of complex knowledges. Even me, a former dev in FS of the old FS200X era, I fear to try this, because I don't master the actual FS dev technologies.

If you do that, you will offer more choices to users and therefore, for sure, increase greatly the popularity of A32NX mod.

The ball is in your camp. Maybe it is the time now to submit this proposition to all the staff of FlyByWire and to decide democratically what you will do with it

For me, you can lock again this thread (thanks to AdenFlorian to have unlocked it)

**Comment by AdenFlorian** [comment]
We have considered allowing customization at some point. As long as we can add options in a way that don't get in the way of players who want the default realistic experience, then I don't see a problem with adding options.

**Comment by wpine215** [comment]
As the founder of this project, I can say with certainty that the goal is to achieve an a320neo that is as close to study level as possible, without any concessions or shortcuts. This means every PR, whether it be a system feature, visual change, or new sound, is run by real A320 pilots and engineers who give feedback and confirm it functions as it's supposed to in real life (or at least closely approximates the real thing). We would not merge any new features, such as sounds, if they are a regression from the default plane. This mod is not meant to cater to the average sim user, who can simply get by using the default A320neo. I see no need to fork the project into two separate mods, which presents massive logistical challenges with this codebase, and will confuse users as well. This is my final decision.

**Comment by Pleasure0102** [comment]
That being said, you can always create a fork, and stay at that level or work on it on your own, or even try to mix match things merged. Of course that can not get any support
