### ISSUE TITLE
[BUG] Managed speeds are a kind of a mess

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/a32nx#1080]
**Mod Version**
from 0.3.1 to current master

**Describe the bug**
The whole managed speed is a bit a mess. Climbing with 320kts managed, automatic switch to mach, but when CRZ mach is reached still holds the kts, then suddenly going back to 285kts (managed CRZ). The descent goes with managed ~240kts (it should be CRZ mach first and then switch to according kts ~280 or higher).  Even if you switch to selected speed prior to open descent, the FCU shows mach, but it still will descent with knots (speed overshoots speed bug).

**To Reproduce**

1. Plan a full flight and start it
2. Don't fiddle with the phase speeds in MCDU (except takeoff speeds)
3. Fly and watch the speeds, during different flight phases
4. Try to switch to selected speed prior to descent from CRZ alt. Use mach speed first and watch the actual speed overshooting the mach speed bug.

**Expected behavior**
see above

**Actual behavior**
see above

**References**

**Additional context**
I think it started with version 0.3.1. Could be also a 1.9.3 vanilla issue. I don't know.

**Comment by aboodilatif** [comment]
I have experienced a similar bug to what you describe, and since the title is vague I will include my observations in this issue instead of opening a new one.





**Mod Version**

current master

**Describe the bug**

Cannot switch back to managed speed or managed heading after using selected mode (push). I am only able to switch back to managed altitude.

**To Reproduce**


1. Start at a gate C/D
2. did not touch the MCDU
3. takeoff and pass thrust reduction altitude
4. flaps up
5. switch to selected heading and speed
6. cannot switch back to managed heading and speed


**Expected behavior**

when pulling on the speed and heading selector, it should enable managed mode

**Actual behavior**

when pulling on the speed and heading selector, it remains displaying current selected speed/hdg and the aircraft remains following it


**Additional context**


Was this working before/when did the issue start occurring?
Today's master, haven't tried out managed speeds since 0.2.0

Discord username (if different from GitHub): Aboodilatif # 0001
