### ISSUE TITLE
[BUG] CTD in landing approach 

### ISSUE THREAD

**Issue by MANFahrer-GF** [flybywiresim/a32nx#1137]
**Mod Version**
0.3.1

**Describe the bug**
The flight simulator crashes with every landing approach. (CTD) What the problem is I can't tell you. No error message is displayed. 
If I fly with the A320 from MSFS I can land my flight without CTD.  

Routing: 
EDDT - EDDF tried 6 times and always CTD on approach 
EDDF - EDDM tried 2 times and always CTD in landing approach

**To Reproduce**

I can't say that it always happened during landing approach. 
I don't know but I tried to find it but couldn't find a way.

**Expected behavior**
that the flight simulator does not bring me to the desktop but that I can land
No CTD

**Actual behavior**
CTD

**References**
none

**Additional context**
none

Was this working before/when did the issue start occurring?
With version 0.3.0 I had no problems before updating MSFS

Is this a problem in the vanilla unmodded game?
Without the mod A320 Neo I can finish flying without CTD

Discord username (if different from GitHub): MANFahrer ( But I have not been on the Discord yet and unfortunately I do not speak English )

**Comment by MANFahrer-GF** [comment]
Windows Crash
[windows 10 MSFS.zip](https://github.com/flybywiresim/a32nx/files/5331705/windows.10.MSFS.zip)
 File

**Comment by MANFahrer-GF** [comment]
on the current master the error occurs. 
In LS landing approach on EDDF again CTD

**Comment by Dubbick** [comment]
The same CTD happened to me consistently on landing approaches to LFPG (three consecutive times) and also on EDDF approach.

**Comment by fabianoheringer** [comment]
Same problem here, selecting any ILS Approach, Crash to Desktop. No mod´s on Comunity folder, only a2320nx DEV VERSION.

**Comment by Benjozork** [comment]
> Same problem here, selecting any ILS Approach, Crash to Desktop. No mod´s on Comunity folder, only a2320nx DEV VERSION.

Hello, do you use software like PACX or SLC ?

**Comment by fabianoheringer** [comment]
> > Same problem here, selecting any ILS Approach, Crash to Desktop. No mod´s on Comunity folder, only a2320nx DEV VERSION.
> 
> Hello, do you use software like PACX or SLC ?

No, i don´t use any 3rd part software.

**Comment by MisterChocker** [comment]
Issue persists

**Comment by cgm95** [comment]
Same problem here. CTD while approaching. (mod Version 0.5.2).

**Comment by IcedLemonTea** [comment]
Mod Version
Latest Dev Version: after commit #2781 

Describe the bug
CTD while flying approach:
Changing STAR or using DIR to waypoints in a STAR. One of these 2 symptoms
1. Clears flight plan & init pages and then CTDif you try to load in  from simbrief mid flight
2. CTD when using DIR to a waypoint in a STAR
3. Waypoint hold feature doesn't work

Routing:
EGCC - LSGG
Issue occurred in the LUSA2N Approach

To Reproduce
Takeoff and cruise normally. Begin descent before LUSAR
1. Use waypoint hold at DINIG in F-Plan Track: 143, Dist: 1 min (Should automatically hold but it instead continues to SOVAD)
2. Manually fly a hold using FCU heading selector 1 lap
3. Set HDG to managed once 1 lap is completed (F-plan chooses to fly to KERAD instead of SOVAD)
4. Use DIR page to select SOVAD (Preview route shows correctly but once you select temp insert, it CTD's)

Expected behavior
1. Waypoint Hold works over DINIG
2. DIR to SOVAD does not CTD after pressing Temp insert

Actual behavior
CTD

References
none

Additional context
none

Was this working before/when did the issue start occurring?
Unsure

Is this a problem in the vanilla unmodded game?
Unsure

Discord username (if different from GitHub): IcedLemonTea

**Comment by depthvader** [comment]
Getting the same, on approaches, it crashes on descent or approach. not 100% consistent, but tonight tried to fly KDEN to KORD 4 times. with the A32NX it crashed 3 times. Twice on approach, once enroute. Removed A32NX mod and was able to complete the flight with no issues. Was running development version the first flight, Stable version the next two and then removed it completely and was able to use the base A320 from the Sim, which is of course, like flying your favorite toaster compared to the A32NX

**Comment by CoffeePanda0** [comment]
Issue persists on latest experimental but is no where near as bad as it used to be.

**Comment by sidnov** [comment]
This issue has been stale for quite some time. There are no frequent CTDs linked to the A32NX during approaches. If it happens again, feel free to open a new issue with updated information about the steps to reproduce the crash.
