### ISSUE TITLE
[BUG] Fuel consumption too high

### ISSUE THREAD

**Issue by SgtNikeR** [flybywiresim/a32nx#1166]
**Mod Version**
Latest master

**Describe the bug**
The A32NX fuel consumption is too high

**To Reproduce**
1. Fly anywhere
2. During cruise open FUEL page and monitor fuel consumption

**Expected behavior**
Fuel consumption should be around 2100-2500 kg/h during CRUISE

**Actual behavior**
Now the fuel consumption is more than 3000kg/h

**References**
- Real LIDO's for A20N flights, 
- https://airinsight.com/airbus-a320neo-family-fuel-burn-numbers/
- https://www.airliners.net/forum/viewtopic.php?t=1440797
- real A20N pilots

**Additional context**
Check engines.cfg and the fuel_flow_scalar should be 0.768

fuel_flow_scalar = 0.768 ; Fuel flow scalar

I would request the pull, but have no idea how to do it

Is this a problem in the vanilla unmodded game?
Yes, as well

Discord username (if different from GitHub): Nikodem Rudziński#7173

**Comment by Pheome** [comment]
Yesterday with actual master I noticed that I'm almost empty at landing and I'm using the regular a320 template with 15 min extra fuel in simbrief and the Neo must be 15-20% more efficient.I check it after work.

**Comment by SgtNikeR** [comment]
For simbrief use Fuel Factor M15 and remember to set fuel_flow_scalar to 0.768, let me know how it works

**Comment by theersink** [comment]
> For simbrief use Fuel Factor M15 and remember to set fuel_flow_scalar to 0.768, let me know how it works

Tried this but now with full fuel I can get almost 6000 miles and 13 hrs. That scaler setting is way too low, may be an accurate fuel flow but something may be off with the actual consumption.

**Comment by theersink** [comment]
> For simbrief use Fuel Factor M15 and remember to set fuel_flow_scalar to 0.768, let me know how it works

Now the range is a bit too high. Avg around 3900nm. Much better than it was though.

**Comment by SgtNikeR** [comment]
Better have slightly more range than top high fuel. Me and my friend have compared real A20N LIDO's to Asobo performance and if you would load fuel according to real loadsheet, then you will land with empty fuel tanks for sure

**Comment by theersink** [comment]
> Better have slightly more range than too high fuel flow. Me and my friend have compared real A20N LIDO's to Asobo performance and if you would load fuel according to real loadsheet, then you will land with empty fuel tanks for sure

Well I have been using a custom airframe since simbrief only has the regular 320 that has been pretty spot on when following the load sheet. I agree that the scaler at 1 is way too high. Maybe something in the range of .81 or so seems to be good from my last flight. 

Try this airframe file with following the loadout sheets. Fuel scaler at p00 and see what you think. 

https://www.simbrief.com/system/dispatch.php?sharefleet=eyJ0cyI6IjE2MDA1NDI5MTkyODIiLCJiYXNldHlwZSI6IkEzMjAiLCJjb21tZW50cyI6IiIsImljYW8iOiJBMzJOIiwibmFtZSI6IkEzMjBORU8iLCJlbmdpbmVzIjoiQ0ZNIExFQVAtMUEyNiIsInJlZyI6Ik4zMDFGUiIsImZpbiI6IjYwOSIsInNlbGNhbCI6IiIsImhleGNvZGUiOiIiLCJjYXQiOiJNIiwicGVyIjoiQyIsImVxdWlwIjoiU0RFM0ZHSElSV1kiLCJ0cmFuc3BvbmRlciI6IkxCMSIsInBibiI6IkExQjFDMUQxTzFTMSIsImV4dHJhcm1rIjoiIiwibWF4cGF4IjoiMTgwIiwid2d0dW5pdHMiOiJMQlMiLCJvZXciOiI5MDQwMCIsIm16ZnciOiIxNDE4MDAiLCJtdG93IjoiMTc0MTY1IiwibWx3IjoiMTQ4NjAwIiwibWF4ZnVlbCI6IjQ2OTAwIiwicGF4d2d0IjoiMjMwIiwiZGVmYXVsdGNpIjoiIiwiZnVlbGZhY3RvciI6IlAwMCIsImNydWlzZW9mZnNldCI6IlAwMDAwIn0-

I'm ending up with reserve + contingency fuel + alternate fuel + about 650KG left from trip fuel.

**Comment by SgtNikeR** [comment]
But you miss one important thing - during cruise look at your fuel flow per one engine and then for both summer. It should be around 39-44 kgs/min as in real

**Comment by theersink** [comment]
No I realize it is a bit off but I'd rather have a more realistic range as a tradeoff until the flightmodel gets worked out. I suppose it is all about preferences. Good place to start though. I wonder which other settings will still allow for correct fuel flow but keep the range intact. I may have to play around with it.

**Comment by SgtNikeR** [comment]
You can also check 0.77, let me know what you think

**Comment by theersink** [comment]
Ran some tests with 0.81 and this seems to be the sweet spot for range. With that fuel scaler I get between 3400-3600 miles depending on winds. 
Fuel Flow is just a tad over nominal range at that. Hopefully the team can figure out how to untie the FF from the scaler settings.
