### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kparsons34** [flybywiresim/a32nx#1281]
**Mod Version**

**Describe the bug**

When inserting The current A32NX file into the community folder the game is vanilla. Not sure what happened but the last version I was able to successfully use was last weeks version of the stable A32NX. 

Please help 

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Hello,

Due to recent changes in our development process that were necessary in order to introduce our own fly-by-wire and autopilot modules,  you should now use either the installer or this automatically updated direct download link:

https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip

Please see README.MD for more information.
