### ISSUE TITLE
Black screens [BUG]

### ISSUE THREAD

**Issue by CptRPeralta93** [flybywiresim/a32nx#1291]
Hello, i´ve just install the latest a320nx and my screens on the plane just went completly black, and the litle flashlight that stays on at night before we turn the bateries on is also gone! Can anyone help with this problem?
thanks

**Mod Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
# Please follow this guide and report back on whether your issue disappeared.

FlyByWire Simulations:  Make sure you have your mod installed correctly : 

- Make sure you identified your Community folder correctly (ie. you can use liveries airports and such)
  If you are using custom install location its X:\MSFS\Community 
- When you update to a new version delete the old A32NX folder and copy in the new one.
- If you downloaded the master branch version from github, only take the A32NX folder 
  out of the package, do not unzip the whole zip in the community folder it will cause conflicts.

 This bug can be caused by certain liveries : 

- You should really delete any old liveries (megapack v8 and older) as they are known to cause 
  this bug and use newer liveries like the ones from this website (check at the bottom)
- Set your game to use generic AI models by setting Use Generic Plane Models (AI Traffic): On" (Off causes the problems)
  in graphics options, or turning off all of AI traffic if the first setting doesn't fix the problem for you.

 Make sure your Community folder is not corrupted and does not have anything in there that shouldn't be there : 

- Remove everything out of your Community folder put a fresh copy of stable/master and test if the problem persists
- For some people the Community folder can get corrupted, you can rebuild it by deleting it (remember to back up its contents first),
  and then running the game. That will rebuild the folder. If your game is installed in custom location and you had to create the Community 
  folder manually you can just delete it and recreate it.

 If you have changed any of the files in the A32NX folder or if non of the above worked for you: 

- Run build.py located in the A32NX
- Disable Multiplayer 
- If your version is from MS store and you haven't restarted your PC in a while, do that.

**Comment by kielyscott** [comment]
Can confirm, ND and PFD both off when updated to latest MSFS patch (13/10)

**Comment by Benjozork** [comment]
@kielyscott have you reinstalled the latest master build using the installer ?

**Comment by AdamNZ** [comment]
@Benjozork ...
"You should really delete any old liveries (megapack v8 and older) as they are known to cause
this bug **and use newer liveries like the ones from this website (check at the bottom)**"

Where "on the bottom"?

**Comment by CptRPeralta93** [comment]
> # Please follow this guide and report back on whether your issue disappeared.
> FlyByWire Simulations: Make sure you have your mod installed correctly :
> 
> * Make sure you identified your Community folder correctly (ie. you can use liveries airports and such)
>   If you are using custom install location its X:\MSFS\Community
> * When you update to a new version delete the old A32NX folder and copy in the new one.
> * If you downloaded the master branch version from github, only take the A32NX folder
>   out of the package, do not unzip the whole zip in the community folder it will cause conflicts.
> 
> This bug can be caused by certain liveries :
> 
> * You should really delete any old liveries (megapack v8 and older) as they are known to cause
>   this bug and use newer liveries like the ones from this website (check at the bottom)
> * Set your game to use generic AI models by setting Use Generic Plane Models (AI Traffic): On" (Off causes the problems)
>   in graphics options, or turning off all of AI traffic if the first setting doesn't fix the problem for you.
> 
> Make sure your Community folder is not corrupted and does not have anything in there that shouldn't be there :
> 
> * Remove everything out of your Community folder put a fresh copy of stable/master and test if the problem persists
> * For some people the Community folder can get corrupted, you can rebuild it by deleting it (remember to back up its contents first),
>   and then running the game. That will rebuild the folder. If your game is installed in custom location and you had to create the Community
>   folder manually you can just delete it and recreate it.
> 
> If you have changed any of the files in the A32NX folder or if non of the above worked for you:
> 
> * Run build.py located in the A32NX
> * Disable Multiplayer
> * If your version is from MS store and you haven't restarted your PC in a while, do that.

i´ve tried all of this and still doesn´t work! Also, The APU doesn´t start, the fire teste of eng 1 and 2 and the apu doesn´t make the alarms sound like before and the temperature buttons on the overhead panel doesn´t work either

**Comment by tvanhove** [comment]
Can confirm!

Mod version
0.3.1

Issues started occurring after the recent update (2.1 GB) of MSFS. Screens no longer come on as well as the battery indicators, autopilot indicators, and fire tests no longer produce sounds.

**Comment by Watsi01** [comment]
The latest stable build (0.3.1) is actually unstable, regarding the last MSFS update. Try using the latest developer branch. This works much better right now. Download:
https://github.com/flybywiresim/a32nx/releases/download/vmaster/A32NX-master.zip

**Comment by CptRPeralta93** [comment]
@Watsi01 now it´s finally working, althouth the engine sound on the cockpit seems to be a litle too high, but at least now i can fly again

**Comment by Watsi01** [comment]
@CptRPeralta93  Yeah, I didn't fly the newest version (with new sounds) today, but I heard, some people say, the engine sounds are too loud.

**Comment by hotshotp** [comment]
> @Watsi01 now it´s finally working, althouth the engine sound on the cockpit seems to be a litle too high, but at least now i can fly again

Engine sounds have been removed in latest master and will be turned down when they get re released
