### ISSUE TITLE
[BUG]Approach/short final speed, not working as it should

### ISSUE THREAD

**Issue by snaylor111** [flybywiresim/a32nx#1370]
**Mod Version**

built: 2020-10-15T01:38:50+00:00
ref: refs/heads/master
sha: a72a977f0b5c74eab9396bab64cb16f6cc4c8120
actor: Benjozork
event_name: push

**Describe the bug**

1.When on Approach, click LOC then APP
2.
3.

**Expected behavior**

Normally once on short finals the speed normally automatically goes to the speed it should e.g 150kt

**Actual behavior**

short Finals speed was still at 250kt causing overspeed while dropping flaps 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
it was working in the last builld 0.3
Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by joniatus** [comment]
You sure approach mode was active in the MCDU? sometimes you have to do it manually

**Comment by snaylor111** [comment]
yes i double checked

**Comment by joniatus** [comment]
you might need a video b/c I've never had an issue with managed speed during approach

**Comment by snaylor111** [comment]
i wouldnt make it up, not everyone get's the same issues so does not mean you would it this issue

**Comment by joniatus** [comment]
not what I was implying, it would be easier to diagnose tho.  Going off your description alone it seems like it would be difficult to pin down since in fact it doesn't affect everyone.  At least list detailed steps to reproduce reliably.

**Comment by snaylor111** [comment]
i have, nothing more to put, i went in for an ils landing at EKCH runway 4 ils was established g/s established after click on LOC but APP button automatically iluminated and speed was not decreased for apprach, but was activated within the MCDU, nothing else to say BTW i am using the DEV build and not the master

**Comment by joniatus** [comment]
So is it a one-off or you can reliably reproduce that issue? How about different airport, still the same?

**Comment by snaylor111** [comment]
i will check when i do another flight, one off or not i've put it in here just incase someone else has had the same issue and i will update this once i do another flight and post screenshot

**Comment by Rameyuk** [comment]
I think the issue here is the APPR phase itself. I started a longhaul flight with default payload and full fuel. But at the start, the APPR page doesn't seem right, because the airspeed between the S F and O is too fast than from what it was before.

I believe F should be the slowest, followed by a slightly faster S, and then O should be the fastest. In this screenshot, S and F is the same amount and it's faster than O airspeed.

VLS at 346 doesn't seem right to me too, since it was about 150-160 before the latest version.

By the time I'm on APPR phase, the flaps will set a target managed airspeed within the overspeed zone. My current workaround is to override the airspeed using the selected airspeed and adjust it manually as I approach. And I will have to edit the VAPP accordingly too, which is far below the VLS.

![1250410_20201016030530_1](https://user-images.githubusercontent.com/72927569/96157044-89034480-0f5d-11eb-8870-39a7c2820dc3.png)

**Comment by lve0200** [comment]
Did you check ZFZ/ZFCG? It affects heavily these values!

**Comment by snaylor111** [comment]
i did

**Comment by AldenGriffith** [comment]
ZFW in kg or lbs? It seems that kg are required for fbw 320 mod

**Comment by lve0200** [comment]
Yes KG 4all

**Comment by snaylor111** [comment]
it automatically calculates it anyway by tapping the key when blank

**Comment by Rameyuk** [comment]
I realised what was wrong.. It was the value I input to the Block. I put 106.2 instead of 10.62. So it calculates an overweight landing.
I input the correct decimal place, and the VREF is showing correctly now.

**Comment by snaylor111** [comment]
it's tricky as when inputting fuel MS2020 is in LBS or Gallons and the A320 is in KG'S wish ASOBO would sort this issue out

**Comment by lve0200** [comment]
I have a bug opened in Zendesk for this.

**Comment by snaylor111** [comment]
your best of putting it on the forum and if it gets enough votes they will look into it. they going by a vote system within their forum now

**Comment by Watsi01** [comment]
> 
> 
> it's tricky as when inputting fuel MS2020 is in LBS or Gallons and the A320 is in KG'S wish ASOBO would sort this issue out

This is one thing that is in MSFS as tricky as IRL.

**Comment by snaylor111** [comment]
Sorry guy's must of been a one time bug or pilot error. It's never happpened since, closing this issue
