### ISSUE TITLE
[BUG] Waypoints before an DIRECT TO Waypoint are after the DIRECT TO still in Plan and Display. 

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1438]
**Mod Version**
Last Master Version 0.4.0

**Describe the bug**
I choose in FMC DIRECT TO , but all Waypoints before the DIRECT TO Waypoint are also in FP in FMC and in the Flightplan in the Navigation Display too. 

**To Reproduce**
1. Choose an WP for an DIRECT TO . 
2. Control FP in FMC and Navigation Display. 

**Expected behavior**
All WPs before the DIRECT TO WP should delete in FMC FP Screen and also in Navigatin Display. 

**Actual behavior**
The WPs before are still there and this is very confusing . 

![DIRECT TO](https://user-images.githubusercontent.com/50043259/96364330-7db94000-113a-11eb-9479-68cf07ba3a25.jpg)

![dirte](https://user-images.githubusercontent.com/50043259/96364766-8dd21f00-113c-11eb-9c6c-780c09c6bbd1.jpg)

**Comment by o4oren** [comment]
This is critical. When hapenning during STAR the way points can't be deleted to fix it, and it destroys the approch.

**Comment by fsxmanu** [comment]
So I have the latest dev version (downloaded it around 30 minutes ago) and I did a flight from LSZH to LFPG. I tried the direct just after departure to test this because I was sure this worked a few days ago for me.
T.O. at LSZH RWY28 WIL3V departure.
It takes a few seconds but it works.



![image](https://user-images.githubusercontent.com/22397350/100996373-44f1f080-3559-11eb-8d99-76b424379b66.png)
![image](https://user-images.githubusercontent.com/22397350/100996434-563afd00-3559-11eb-8d60-83e9d1ba438d.png)

**Comment by SierraBravo1** [comment]
A 'Direct To' during SIDs or Enroute works correctly. The waypoints before are removed and the route continues as planned after the DCT.
But it is not working correct during approaches. The previous waypoints are not removed (and cannot manually cleared) and the plane is routed back to the first waypoint of the approach when the DCT is passed. This is not related to #2345 and happens also when far away from the runway and other waypoints are located afterwards.
Probably this issue has the same root cause described in #1388, that waypoints inside a STAR (or other approach) cannot be deleted.
Please proceed with this issue. It would be often required to shorten the approach with a Direct To, which is not possible at the moment (and requires switching to HDG mode).
Thanks.

**Comment by sidnov** [comment]
This issue has been stale for quite some time, and most of the reports have been addressed by the updated FMS systems in the recent dev versions.
