### ISSUE TITLE
[BUG] Approach Via Missing. Airport ICAO displaying instead. 

### ISSUE THREAD

**Issue by mak60062** [flybywiresim/a32nx#1446]
**Mod Version**

{
  "built": "2020-12-23T23:38:26+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**

For some reason a single approach VIA is missing and instead it is replaced with the airport code. 

**To Reproduce**

1. Select an approach in the MCDU
2. Open the vias list

**Expected behavior**

All possible vias will be displayed

**Actual behavior**

A single via is missing and replaced with the airport code. 

**References**

A320NX KPIA RNAV 22 Vias:
![image](https://user-images.githubusercontent.com/6889399/96375629-17d3b500-1148-11eb-9a01-6058f45b083f.png)

TBM KPIA RNAV 22 Vias list:
![image](https://user-images.githubusercontent.com/6889399/96375526-7d737180-1147-11eb-9693-b834f811f7a4.png)

A320NX KCMH RNAV 10L Y Vias:
![image](https://user-images.githubusercontent.com/6889399/96375611-fd014080-1147-11eb-8f57-dce7d8943664.png)

TBM KCMH RNAV 10L Y Vias
![image](https://user-images.githubusercontent.com/6889399/96375540-9714b900-1147-11eb-8c4f-fafd26fc0053.png)

**Additional context**

Maybe related to #1412 and/or #1436 

Was this working before/when did the issue start occurring?
Never has worked.

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub): COVID_19_Fox3

**Comment by pareil6** [comment]
I potentially hit the same issue at EGLL, where some approaches have the arrows showing for the vias but no name - eg. ILS 27R approach contains BIG, BNN and CHT, followed by 3 arrows with a blank space next to them (which should be EPM, LAM and OCK), shown here (scrolled past BIG/BNN):

![a32nx_missing_via1](https://user-images.githubusercontent.com/73158172/96549141-fc32f080-12a6-11eb-836c-24ecb10a674f.png)

Looking at A320_Neo_CDU_AvailableArrivalsPage.js, ShowViasPage() picks the via name based on `approachTransition.waypoints[0].infos.icao.substr(7)`, which seems to be failing because the first waypoint on these approaches actually isn't the correct via - eg. if I pick what should be the OCK via for the approach above, the first waypoint it inserts is the D7.0 outbound from OCK (based on the approach plate), which just shows up as USR in the flight plan:

![a32nx_missing_via2](https://user-images.githubusercontent.com/73158172/96549800-e3770a80-12a7-11eb-96d0-0c14322d9847.png)

**Comment by dedyk** [comment]
I want to report the same issue. This is my record from the A320 where this issue exists and from the Cessna latitude longitude where doesn't exist.

https://www.youtube.com/watch?v=NCzm792EBLI
https://www.youtube.com/watch?v=eTKBdTHGcKM

**Comment by MisterChocker** [comment]
Please retest on latest master or stable and report back.

**Comment by mak60062** [comment]
> Please retest on latest master or stable and report back.

Retested per request. Issue still appears to be occurring on both latest master and latest dev version. 
![image](https://user-images.githubusercontent.com/6889399/103397758-ad57d180-4b07-11eb-8469-a4f52a1ae46d.png)
![image](https://user-images.githubusercontent.com/6889399/103397794-d8422580-4b07-11eb-86db-ee4832dacd1e.png)

**Comment by pareil6** [comment]
The EGLL example I reported above also still occurs on latest master.

**Comment by pareil6** [comment]
Just checked in the WT CJ4 -it displays these correctly, so it should be possible to fix this as part of the flight plan manager rewrite since the nav data is obviously available _somewhere_.

![image](https://user-images.githubusercontent.com/73158172/103415988-71ab1f00-4b7c-11eb-9dba-b1670eb34f4e.png)
![image](https://user-images.githubusercontent.com/73158172/103415996-796ac380-4b7c-11eb-9021-a8c047636347.png)

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
