### ISSUE TITLE
Landing Gear Gravity Extension

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/a32nx#1452]
**Is your feature request related to a problem? Please describe.**

No, but there is a need and I would say relatively good demand for this, especially when emergency scenarios become easier to simulate in-game.

**Describe the feature you'd like to see implemented**

Implement working functionality for the landing gear gravity extension lever. This can be used when no hydraulic power is available such as the APU, and dual engine failure. This doesn't necessarily have to be fancy in terms of the logic in the short term. For now, it can simply be a call to lower the gear as if it were normally lowered. 

**References**

http://www.a320dp.com/A320_DP/landing-gear/sys-12.3.0.html

**Additional context**

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
I will see if this is possible right now.

**Comment by komp1821** [comment]
I understand that this is a funny thing to do, but from my point of view we are hundreds of miles away from having emergency procedures. We should focus on normal operations rather than implementing random emergency features. Once we have well working systems it will also be a lot easier to implement such things. 

The gravity gear extension lever needs three full 360° clockwise turns before the gear drops.
1st turn: hydraulic pressure supply is cut off
2nd turn: vent valves open to allow fluid inside the actuator to return to the reservoir. 
3rd turn: uplocks open. Gear doors and gear fall down by gravity.

Notice that the gear doors will NOT close after operation, so this would also have to be represented on the ECAM SD gear page. There would also be a few other messages on the EWD and ECAM status page... Also, we have to verify the behavior of the three gear annunciators on the main instrument panel.

After gravity extension, operation of the normal gear lever will have no effect on the landing gear. It's possible to restore normal configuration by turning the gravity gear lever 3 turns ccw however.

Just my 2 cents...

**Comment by maxpain** [comment]
Hello guys. Any updates on this?

**Comment by Benjozork** [comment]
@maxpain Abnormal operations are not a priority.

**Comment by maxpain** [comment]
@Benjozork When it will be?

**Comment by Benjozork** [comment]
When normal operations are finished.

**Comment by Benjozork** [comment]
btw,

https://github.com/flybywiresim/a32nx/pull/5359

**Comment by tracernz** [comment]
> Hello guys. Any updates on this?

Check out #6893
