### ISSUE TITLE
[BUG] In the A320 FMC the C-Prefix for the Center Runways is not choosable. 

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1472]
**Mod Version**
Latest Build , 0.4.0 

**Describe the bug**
At the Moment we have an Discussion about the Reason why the A320 with his FMC has not the possibility to choose ther right Runway for LOWG.
When utry to choose an Runway for Arrival via ILS the FMC from the A320 only shows an Runway 35 ( nor 35L , 35R or 35C )
From the Scenery and also in Simbrief you are able to see all three 35er Runways L, R and C.
But when u choose in A320 FMC in FS2020 the 35 , then after this in the Flightplan there is an 35L what is totally wrong for ILS .

I open an Ticket on OrbX Side , this is the Scenery Developer and also on Navigraph side. 
Navigraph wrote an answer of my Post . You can read the answer under Actual behaviour. 

**To Reproduce**
Try to insert Arrival at LOWG Airport via ILS on Runway 35C . But in FMC only 35 is choosable which choose the unfortunately the Grass Runway 35L . 

**Expected behavior**
For the Runways the C for Center should be choosable . 

**Actual behavior**
Hi,
as you see in the worldmap (also in your picture) - the correct runway-ident is 17C/35C ... but in the A320-FMC you can´t add any center runway because ASOBO forgets the C-prefix in the FMCs (not only in the A320, also in the TBM930 or B787). Thats not an ORBX issue, nor a navdata issue but due the missing C-prefix, the procedures (which are included for LOWG) can´t be assigned to the correct runway-ident - which is 17C/35C.

In other words - sorry a bug in the sim. In worldmap the runway-idents are ok, but not in the FMCs - here the center-runways are all missing (KSEA, EDDF, LOWG, ... - all runways with a center runway). Sorry!

**References**
Navigraph Forum Post : 
https://forum.navigraph.com/viewtopic.php?f=14&t=10872

OrbX Forum Post : 
https://orbxsystems.com/forum/topic/201102-lowg-ils-35c-loc-gs-path-is-too-far-left-near-the-runway/?tab=comments#comment-1718477

![2020-10-20 09_20_16-LOWG_Ground_Aerodrome Overview_13082020](https://user-images.githubusercontent.com/50043259/96600244-0843a000-12f1-11eb-94d1-7efff7c166ca.jpg)
![2020-10-20 09_39_14-Microsoft Flight Simulator - 1 9 5](https://user-images.githubusercontent.com/50043259/96600247-0974cd00-12f1-11eb-9490-81dc653d4059.jpg)
![2020-10-20 09_57_43-Microsoft Flight Simulator - 1 9 5](https://user-images.githubusercontent.com/50043259/96600249-0974cd00-12f1-11eb-8809-82add47d076c.jpg)

**Comment by Benjozork** [comment]
I'll look into whether or not we can fix this on our end. Thanks for your report and the detailed info.

**Comment by SM-396** [comment]
> I'll look into whether or not we can fix this on our end. Thanks for your report and the detailed info.

You welcome . This is a very serious Bug .

**Comment by Kimbyeoungjang** [comment]
I don’t know that this is helpful

On frankfurt airport, i find same issue that I can’t choose 25C runway
Frankfurt have 25L, 25C, 25R runway but there is no 25C.

But there is a 25 Runway in mcdu that can select. ( there is no 25 runway on frankfurt, only 25R 25L 25C.)

When i choose arrival on frankfurt 25 Runway, on F-PLN and PERF(appr) page showed to me 25C runway selected.

**Comment by donstim** [comment]
Same issue with arrival at KSEA. Landing south, the choices are 16, 16L, and 16R instead of 16C, 16L, and 16R. If 16 is selected, 16L is shown as the arrival runway for the destination on the flight plan page, but the correct 16C localizer frequency is shown on the RAD NAV page. Appears to just be an issue with the "C" identifier missing from the runway choices when selecting an approach procedure. Although I would like to see this fix, I would not consider it to be a "very serious bug" since the runway can be selected and the nav radio is set properly.

It is interesting that the C runways apparently appear okay on the departure selection screen.

**Comment by ntlgr** [comment]
Some interesting findings:
- C runways can be selected without problem for departure.
- KDFW 17C in the arrival options appears as "17 C" instead of "17C" and there are also runways "17 L C" and "17 R C"
- departing from KDFW 17C appears just fine and can be selected.
- KCLT also has C runway. Appears in the list for departures, but not in the list for arrival.

**Comment by Benjozork** [comment]
@ntlgr thank you for the details, will help in our diagnosis of the issue.

**Comment by 2hwk** [comment]
Fixed by #4953 closing ☑️
