### ISSUE TITLE
Plane can't descent more than 1000 ft/minute [BUG]

### ISSUE THREAD

**Issue by vlbreda** [flybywiresim/a32nx#1509]
**Mod Version**

Latest dev

**Describe the bug**

Plane seems to have far too much lift. Descent rate is < 1000ft/minute in appr phase, even in open descent. 

**To Reproduce**

1. Fly a programmed route
2. Try to descent 
3.

**Expected behavior**

Higher descent rate

**Actual behavior**

Descent rate far too low

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Worked fine till dev oct 23th

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by vlbreda** [comment]
BTW: Stable version still working fine!

**Comment by Benjozork** [comment]
This is probably gonna be tweaked, we did some flight model changes.

**Comment by LissomPineapple** [comment]
Will add to this. Plane descends at 2000 ft/min max even with spoilers at 100%. Was really floaty on landing and I struggled to get to my landing speed until about 3 DME on idle thrust with full flaps. Overshot my descent by a lot.

**Comment by Rameyuk** [comment]
I'm fine with the descent rate. I don't seem to overshoot my descent as long as I follow the ATC when they're not drunk or asleep on the job.

But I do have the problem with spoilers. After the Flight Dynamics changes to the dev build, deploying spoilers doesn't seem to slow down the aircraft. I know because after passing DECEL point and the aircraft tries to slow down from DES speed to APPR speed, the deceleration is happening at a very slow rate. Deploying the spoilers doesn't seem to affect the deceleration at all.

Is there a relation to the excessive engine thrust at idle from the update? I'm taxiing on idle thrust... is that normal?

**Comment by lousybyte** [comment]
On latest master, for me it descends at ~2200 normally and ~4500 with spoilers on, from FL200 to FL100.

**Comment by vlbreda** [comment]
@lousybyte: problem occured with dev-version of oct 23-10 19.00 CET. Stable version worked just fine.

**Comment by lousybyte** [comment]
Managed to replicate, seems the reason is that it's trying to maintain a certain SPD, so when you're on approach phase the target SPD is lower, thus the plane can't go down too fast without increasing the SPD. Will get tweaked I'm sure as mentioned above.

**Comment by vlbreda** [comment]
@lousybyte: thank you!

**Comment by gus74vv** [comment]
I don't think this should be considered a bug. As far as I know, the descent rates are within normal parameters for the descent phases of an a320. 
When the descent begins, at Mach 0.78 cruise speed, descent rate should be around 2500fpm. This rate of descent should be maintained until transition from Mach to IAS happens. 
At 10000ft, 250kias result in 1300fpm ROD.

*Sorry for my english

**Comment by vlbreda** [comment]
@gus74vv

**Comment by LissomPineapple** [comment]
We should leave this open so that the devs are aware of it.
