### ISSUE TITLE
[BUG] When choosing open Descent on Altitude Selector Knob  nothing happens. 

### ISSUE THREAD

**Issue by SM-396** [flybywiresim/a32nx#1519]
**Mod Version**
Dev Mod , last actual Build

**Describe the bug**
I pull the AP Height Hold Button to start an open Descent but nothing happens . No Descent start . 
Sometimes i have to press again the Height Hold again then again i pull the Button then sometimes it works . 

**To Reproduce**
1. I fly on my Cruising Altitude FL320 
2. I pull the FCU Altitude Selector Knob to initialize an open Descent. 
3. The Plane dont change his FL. Nothing happens. The Plane dont change his Cruising Height . 
4. When i press the Altitude Selector Knob to an Managed Desent the sometimes it works , sometimes not. 

**Expected behavior**
When i pull the Altitude Selector Knop to initialize an open Descent the height should change to the selected hight with an defined Sinkrate. 

**Actual behavior**
Nothing happens or only when i switch between Managed and open Descent. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by danbw9** [comment]
Sometimes you need to wait a while before it will initiate, but real plane behaviour is that it will wait until its at the speed before descending. You are correct in saying that its a bug when its at the speed and not reacting. This is just a little workaround until then..

**Comment by Carter633** [comment]
Open Descent usually - as I understand - triggers a delay because the Airbus reduces the throttle to what it'll need for open descent - then the nose comes down. Nose won't come down until the speed is at the appropriate level for the open descent as Dan mentions above too

If you want to trigger an immediate drop in the nose, select the altitude - selected Alt mod + then select a negative vertical speed figure and select that do you descend in VS mode instead of open descent.

**Comment by MisterChocker** [comment]
issue is outdated
