### ISSUE TITLE
[REQUEST] Shared Cockpit

### ISSUE THREAD

**Issue by ezanchi** [flybywiresim/a32nx#1577]
**Is your feature request related to a problem? Please describe.**
The A320neo is a pretty complex aircraft that is not designed to be flown by a single pilot. It would greatly benefit from distributing the workload with a fellow airman and for that we need a Shared Cockpit solution.

**Describe the feature you'd like to see implemented**
Either work with this plugin ([Your Controls](https://github.com/Sequal32/yourcontrols)) or develop something in-house to be able to share the cockpit with another simmer.

**Additional context**
In the real world, complex aircraft like the A320neo are certified for a 2-pilot crew operation because of the heavy workload inside the cockpit and redundancy.

**Comment by cuBeUrg** [comment]
Why not wait instead for the Microsoft Flight Simulator official shared-cockpit thing? I don't think this is necessary at this moment. There are more important things to do.

**Comment by ezanchi** [comment]
> Why not wait instead for the Microsoft Flight Simulator official shared-cockpit thing? I don't think this is necessary at this moment. There are more important things to do.

On the one hand I didn't know Microsoft was going to release a shared cockpit function.

And on the other, im not saying this should be prioritized above other things, just thought about.

**Comment by Rameyuk** [comment]
I think shared cockpit function is affected directly by the capability of the simulation engine. It's not the scope of the NX mod which simply improves the aircraft systems to get as close to the real aircraft as possible. Shared cockpit is a simulation function as a whole, because it's not just going to be applied here, but to all the aircrafts too.

And Microsoft/Asobo has already put this function into their future development roadmap. So it will get implemented eventually, so there's no need for the FBW team to do anything for this as it is a simulation engine update, not an aircraft level modification. When it's released, it'll work.

**Comment by Sequal32** [comment]
Hey, I’m the developer of YourControls, and I’m currently in the process of supporting the A32NX fully. It’s almost complete and will be released within the week.

**Comment by Sequal32** [comment]
Just released, should be pretty stable for now. https://github.com/Sequal32/yourcontrol

**Comment by LarrySheen** [comment]
Asobo has already declared that 'Shared Cockpit Functionality' is planned for further update but not urgent one. 
see :
https://www.windowscentral.com/microsoft-flight-simulator-dlc-updates-roadmap

**Comment by wpine215** [comment]
Closing as this functionality is provided through Your Controls plugin and soon through Asobo directly.
