### ISSUE TITLE
[BUG] PFD tapes background too bright

### ISSUE THREAD

**Issue by stevex77** [flybywiresim/a32nx#1813]
**Mod Version**

DEVELOPMENT
built: 2020-11-08T18:02:05+00:00
ref: refs/heads/master
sha: 9ecc85c0d81df306c5b66b2a29bc94aa9ab56ea1
actor: lukecologne
event_name: push 

**Describe the bug**

Background on PFD tapes (SPEED, ALTITUDE, V/S, HEADING) are too bright, causes information on it nearly unreadable.

**To Reproduce**

1. Spawn at gate, ideally evening / night
2. Power on the FPD. set brightness 50 - 100%
3. Observe all tapes / notice effort needed to recognize numbers

**Expected behavior**

Contrast between text and background on tapes should be higher, backgroud should be much darker.

**Actual behavior**

To bright background of tapes on PFD.

**References**

Screenshot from A32nx
![02](https://user-images.githubusercontent.com/51388935/98484705-b4521a00-2211-11eb-8e46-9905b91e718d.png)

Snip from YT video of A320neo cockpit
![01REF](https://user-images.githubusercontent.com/51388935/98484685-92f12e00-2211-11eb-8466-a29f6c507adc.png)

**Additional context**

Was this working before/when did the issue start occurring?
Not sure.

Is this a problem in the vanilla unmodded game?
Not sure.

Discord username (if different from GitHub):
SteveX77 [Z+0!]#1407

**Comment by lukecologne** [comment]
You should lower the brightness, try around 1/4 brightness

**Comment by stevex77** [comment]
@lukecologne with lower brightness set it's of course better. But I still believe that even thought brightness is set to max, all information should be clearly readable / contrast should be higher. The main reason is ergonomy / safety in the cockpit (important topic in Human performance & limitations).

See this IRL images for example (two different sources for objectivity):
![PFD](https://user-images.githubusercontent.com/51388935/98486691-46145400-221f-11eb-9d80-c25378172760.png)
![PFD2](https://user-images.githubusercontent.com/51388935/98486697-4b719e80-221f-11eb-96fc-7b502d246f81.png)

![PFD3](https://user-images.githubusercontent.com/51388935/98486702-50365280-221f-11eb-9bb2-fe56b4b15ca3.png)

Thanks for consideration.

**Comment by stevex77** [comment]
Btw. I use the brand new calibrated EIZO display, so I should see nearly accurate colors here.

**Comment by ntlgr** [comment]
Agree with the OP. The problem is not brightness, the problem is contrast between font and background. It takes some effort to read, while it should be instantaneous.

**Comment by MisterChocker** [comment]
Try same settings with daylight!

**Comment by MisterChocker** [comment]
![image](https://user-images.githubusercontent.com/1857322/98708290-4a588280-2381-11eb-8b68-382e0d33b2ee.png)

**Comment by stevex77** [comment]
OK, just tried in daylight and agree that it's better, so MSFS somehow adjusts cockpit brightness based on environmental lighting.

But in worse lighting conditions (like night), when instruments and visual recognition are generally more important, the contrast is still to low, making reading of these numbers harder. Especially for airspeed this is crucial. And I also want to fly in the night. :)

Will try how this behaves in vanilla A320 and let know. Also try to turn off the "eye adaptation" setting withing MSFS settings file.

**Comment by MisterChocker** [comment]
> so MSFS somehow adjusts cockpit brightness based on environmental lighting.

yup.

**Comment by stevex77** [comment]
I confirm that in vanilla A320neo this issue is also present, but probably because of darker backlight of whole ND the contract is slightly better (compare with my original post). Turning off eye adaptation setting doesn't affect this (both vanilla A320 and A32NX).

![PDF](https://user-images.githubusercontent.com/51388935/98743375-3bd58f80-23b0-11eb-96f7-ecb73753fcfc.png)

So maybe making background of these tapes slightly darker or making the background transparent (with alpha channel, if possible) may help?

**Comment by MisterChocker** [comment]
@stevex77, reduce brightness to 50% or lower...

**Comment by ischmal** [comment]
I noticed this with the awesome color changes added a while back, but was torn whether to make an issue of it or not. Now that someone else brought it up, I have to say I agree. 

I very much understand that keeping the PFD brightness down helps (and I've been doing this), but I think the contrast between the gray background and white text is still too low overall. It is _legible_, but you really have to (actively) keep the display as dim as possible in order to comfortably read it.

Compare the PFD to the ND and ECAMs in night lighting conditions:

![screen-brightness](https://user-images.githubusercontent.com/5350086/99041652-90137780-2548-11eb-84a8-b72c798f8565.gif)

At minimum brightness, the PFD is easiest to see, while the ND and ECAMs are okay, but a little dim. At 30% brightness, the ND and ECAMs are very clear and easy to read. On the PFD, you must really begin concentrating to read anything over the gray. 

At 50%, the ND and ECAMs are rather bright, but text remains quite readable, while on the PFD, it becomes physically uncomfortable to try and make out text over the gray. At max brightness, ND and ECAMs are still perfectly legible while the PFD's values are effectively washed out (contrast difference between the text and background is 5%).

Again, I have the utmost respect for the intent behind using this shade of gray and know a lot of effort went into it. Because the game does not play nicely with it, however, I sincerely think it would be better to make it darker out of consideration for the end-user's experience than perhaps a hardline devotion to realism (much like how a user can opt-out of the realistic IRS alignment time).

**Comment by ntlgr** [comment]
> I sincerely think it would be better to make it darker out of consideration for the end-user's experience

Fully agree. Having to reduce brightness really highlights the fact _there is an issue_, and we're using a workaround. IMHO realism should not be towards selecting the right Hex color value; it should be in delivering a realistic PFD reading experience.

Since the effort was already made to improve the colors, instead of arguing about it, why not select a background color that is better readable night and day?

**Comment by MisterChocker** [comment]
@ischmal 
> ![custom-color](https://user-images.githubusercontent.com/5350086/99049068-a1ae4c80-2553-11eb-9d2d-fb8f48b6fe4b.png)
> 
> (max brightness in early daylight)

Thanks for your response! Is that picture of your changes during daytime? Please show changes in same conditions as before.

**Comment by stevex77** [comment]
> @stevex77, reduce brightness to 50% or lower...
> I mean whats the point having PFD at 100% and ND at 10% brightness

My latest screenshot was from VANILLA a320, both DUs, PFD and ND was se to 100% In vanilla, outer ND knob sets overall ND brightness, inner knob is INOP. IN A32NX inner knob sets overall brightness, outer knob sets terrain/WX brightness.

I did this vanilla screen to show that in vanilla Airbus it's slightly better, probably because there is no backlight bleeding simualted (whete in a32nx it is)...

All my screenshots were taken at night.

**Comment by stevex77** [comment]
@ischmal really like result of your experiment! 👍 Will try myself with various light conditions.

**Comment by MisterChocker** [comment]
Brightness should not affect colors, however it does.

I have done some changes to improve the visibility

| Captain PFD (before) | FOs PFD (after) |
| ----- | ----- |
|  |  |
|  |  |
|  |  |
|  |  |
|  |  |
|  |  |
|  |  |

**Comment by ischmal** [comment]
@MisterChocker 

Sorry, you are right. I should have done that to begin with. Here's an equal comparison:

![screen-brightness-adjusted](https://user-images.githubusercontent.com/5350086/99078037-eef1e480-257a-11eb-811c-7db892e11855.gif)

I'm not necessarily standing by this color since I just chose a value roughly 50% darker than the current on the color picker. With reference images being all over the place, I can't say with any degree of confidence how bright it should be, I am also most definitely not qualified to assert how the plane should look or work.

**Comment by MisterChocker** [comment]
Brightness should not affect colors, however it does.

I have done some changes to improve the visibility

| Captain PFD (before) | FOs PFD (after) |
| ----- | ----- |
|![image](https://user-images.githubusercontent.com/1857322/99078033-fd152480-25bd-11eb-9ad3-ac8e251128b6.png)|![image](https://user-images.githubusercontent.com/1857322/99078077-0c946d80-25be-11eb-9e75-a85bd0a9b747.png)|
|![image](https://user-images.githubusercontent.com/1857322/99078171-38175800-25be-11eb-9a25-50019cb410e5.png)|![image](https://user-images.githubusercontent.com/1857322/99078140-26ce4b80-25be-11eb-866b-e038ac27782c.png)|
|![image](https://user-images.githubusercontent.com/1857322/99078298-79a80300-25be-11eb-9eb7-de25ba237528.png)|![image](https://user-images.githubusercontent.com/1857322/99078384-98a69500-25be-11eb-9718-015702ca0b39.png)|
|![image](https://user-images.githubusercontent.com/1857322/99078549-dacfd680-25be-11eb-9b10-a1bf1f9af608.png)|![image](https://user-images.githubusercontent.com/1857322/99078438-aeb45580-25be-11eb-92a3-446ad637ea77.png)|
|![image](https://user-images.githubusercontent.com/1857322/99078623-f804a500-25be-11eb-94b5-7de1995d2f44.png)|![image](https://user-images.githubusercontent.com/1857322/99078648-05219400-25bf-11eb-8b24-4bde7055c049.png)|
