### ISSUE TITLE
Thank you to all contributors! :smiley:

### ISSUE THREAD

**Issue by merlinblack** [flybywiresim/a32nx#1819]
As an end-user, I'd like to say **thank you** to everyone. I code in PHP and JS for a job so I know at least part of what is involved. Using the mod makes the A320 so much more enjoyable! :1st_place_medal: 

It also inspired me to make a [conky](https://en.wikipedia.org/wiki/Conky_(software)) script - using the ECAM font. For those that don't know what conky is - the screen clip below sits just above my wallpaper on my Linux desktop.

I'm hoping to contribute myself when I have a bit more time for 'extra' coding. :smiley: 

![A320 ECAM style conky](https://atkinson.kiwi.nz/img/A320_ECAM_Style_conky.png)

If anyone wants the script - tell me, I could make a repo for it.

**Comment by wpine215** [comment]
Thanks for your support! Would love the Conky script myself, and I'm sure others would too, so the repo sounds like a great idea.

Just a heads up, I'll be closing the issue just because we keep open ones only for bug reports/feature requests, but feel free to continue the discussion on our Discord, if you're not already a member! discord.gg/flybywire or feel free to DM me (Iceman#5540)
