### ISSUE TITLE
[BUG] DIST on F/PLN is again broken

### ISSUE THREAD

**Issue by Cthulhus** [flybywiresim/a32nx#1820]
**Mod Version**

DEVELOPMENT
built: 2020-11-09T05:36:29+00:00
ref: refs/heads/master
sha: 81fd900e3c331799a3413c05e2703580de0593d8
actor: Benjozork
event_name: push

**Describe the bug**

The Distance data of the dest Airport of the F/PLN was fixed earlier but is again broken
(https://github.com/flybywiresim/a32nx/pull/1622)

**To Reproduce**
1 : Make a flight
2 : Go to F/PLN page and check the DIST data on the bottom
2 : Data no longer uated

**Expected behavior**
Distance should reduce as we move forward on the flight plan

**Actual behavior**

Data is stuck

**References**

**Additional context**

Colors still need some tweaking, IMO the saturation is too high in some cases (green?, cyan?), sholdn't "burn out" pilot's eyes, shouldn't attract all the pilot's attention , but I'm not really sure about this...
High quality IRL reference needed.

**Was this working before/when did the issue start occurring?**
Yes

**Is this a problem in the vanilla unmodded game?**
Yes and was fixed with last FlyByWire team

**D username (if different f GitHub):**

**Comment by MrMe85** [comment]
afaik, this problem has always been there, and it seems to be either random or depending on the order with which you enter a flight plan, or the waypoints the flightplan is composed of.  I hope that it can be addressed, because not only does it affect any possibility of vertical profiles in a descent, but it is also an invaluable tool to mentally calculate a descent profile too without having to eyeball waypoints on the ND or using a third party app.

**Comment by Cthulhus** [comment]
Oh I see, so to avoid the issue, what should be set first ? Route or DEP/ARR and then the route ? I'll make some tests.

**Comment by ilyeshammadi** [comment]
Thank you for reporting this issue, we're working on changing the colors.

**Comment by lousybyte** [comment]
Should be fixed on latest master.
