### ISSUE TITLE
[BUG] Managed Speed not working correctly

### ISSUE THREAD

**Issue by Samsamtheambulanceman** [flybywiresim/a32nx#1854]
**Mod Version**
"Master"
Dev Installer

**Describe the bug**
Managed speed mode won't move past 260kts using AP, overspeed tape appears stuck at 280kts and not behaving as normal.

**To Reproduce**
Take off as normal, enter managed speed mode after take off and initial climb. Continue to climb, to wanted level, speed will not go past 260kts and impedes any stable climb.

**Expected behavior**
After 10,000 speed to go to selected managed speed (normally 285kts) and climb to CRZ at steady rate.

**Actual behavior**
After 10,000ft speed appears as selected on PFD but actual speed won't move past 260kts and Overspeed tape stays down at 280kts. Aircraft won't climb at any stable consistent rate.

**References**

**Additional context**

Seemed to be working fine prior to latest updates.

**Comment by CBGonzalez** [comment]
Doing first flight after MSFS update with latest dev version, don´t see any problem with speeds.

**Comment by jmwebslave** [comment]
Are you sure you don't have a constraint in the flight plan for 250kts/10,000ft?  It's very common, and I've seen managed speed will sit at 250kts on the climb in that case, until you hit 10,000 and then it'll jump up to the speed you expect.

**Comment by Samsamtheambulanceman** [comment]
I've tried it with and without an FP as I do them myself and not through the sim as I use Vatsim so no constraints.

Ill try again later when I'm home from work but I'll remove the mod and re install and see if it occurs and cap it if it does.

**Comment by jmwebslave** [comment]
Fair enough.  I've found when using VATSIM that when I enter a SID into the FMGC it'll add the constraints.

**Comment by Samsamtheambulanceman** [comment]
![20201111_220722](https://user-images.githubusercontent.com/74272583/98870003-81569300-246a-11eb-99a7-73ddbf23b7f1.jpg)
![20201111_220751](https://user-images.githubusercontent.com/74272583/98870021-89163780-246a-11eb-858a-45c843af72c5.jpg)
![20201111_220816](https://user-images.githubusercontent.com/74272583/98870038-8fa4af00-246a-11eb-9318-005929c54c50.jpg)

So really not sure what I'm doing wrong here. I have no FP except for directly toward EIDW. My overspeed strip is stuck at 280kts. Open climb won't climb at any decent rate.

Really don't know what I'm doing wrong. Yesterday the aircraft was climbing without issue. Throttle as you can see is in Climb. If I set the climb much higher than +2000 the climb just shoots up and down.

**Comment by jmwebslave** [comment]
Now it seems like you're describing a different problem to the one originally reported.

If it can't acquire the target speed then it won't climb or descend as far as I've been able to tell (to the extent that if you're in the middle of a descent and then wind back the speed it will stop the descent, then acquire the speed, then recommence the descent.  I'm told that's not what the real AC does, but MSFS made it this way.

Your overspeed strip being so low at that altitude is more interesting to me.  I'd suggest to you that the reason you're getting that low of an overspeed with no flaps is because your gear is down, since VLE on this aircraft is 280/.67.  Running in the sim with the gear down produces that result for me.  As soon as it finishes retracting I can manage more than a 1000ft climb rate.

**Comment by Samsamtheambulanceman** [comment]
You sir are quite correct. Theres a possibility my button bindings have been altered on my throttle maybe in the update and ruled out gear because I knew id pressed it. I will check my panels better in future!!

Tried another flight last night and it seems to be behaving so... I'll close this.

Thank you.
