### ISSUE TITLE
[BUG] Missing glide path indicators and locator

### ISSUE THREAD

**Issue by redgonzales** [flybywiresim/a32nx#1885]
**Mod Version**
<v. 0.4.1
 v0.4.1

**Describe the bug**
during the approach procedure the two magenta diamonds do not appear for location and glide path, in some cases it appears for a moment and then disappears again. Before the last updates of FS2020 it worked fine. Maybe up to v. 1.10.7.0? I do not remember. For example on the flight from LIRN to LIRF (ILS34L), or from LIMJ to LIMC (ILS35R-Z), but in general it always works badly.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by wpine215** [comment]
Please set at title

**Comment by Benjozork** [comment]
Version 0.4.1 is not supported with latest MSFS. Please try the development version and report back.

**Comment by redgonzales** [comment]
OK thanks

**Comment by Rameyuk** [comment]
The reason isn't because the ILS indicator doesn't appear, but because the ILS frequency isn't automatically tuned in when you assign the runway in the flight plan on the 0.4.1 stable version. By entering the frequency manually in the NAV RAD, the ILS signal will be detected the indicator should appear.

This ILS frequency populating issue doesn't appear in the latest Master build.

**Comment by jeremygovi** [comment]
@Rameyuk the ILS frequency populating issue is still present (tested with v0.4.2 build). However, thank's for the trick.

**Comment by MisterChocker** [comment]
closing since mod version was incompatible with game version
