### ISSUE TITLE
V speeds are too low

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#210]
The FMS V speeds are too low. For takeoff, the VR and V2 should be about 10 kt higher. For landing, VREF and VAPP should be about 15 kt higher. This is the root cause of alpha protection cutting in during flare and uncommanded rolls on final. As a guide, on glidepath, pitch should be about 3 deg nose up, with 10 knots or so buffer above amber band.

**Comment by ko-zone** [comment]
Hey,

We will have a member of the core development team review it ASAP. Will have more information regarding this soon hopefully!

Regards,
KO

**Comment by ThePilot916** [comment]
> The FMS V speeds are too low. For takeoff, the VR and V2 should be about 10 kt higher. For landing, VREF and VAPP should be about 15 kt higher. This is the root cause of alpha protection cutting in during flare and uncommanded rolls on final. As a guide, on glidepath, pitch should be about 3 deg nose up, with 10 knots or so buffer above amber band.

Did you notice these lacking speed amount as a rough constant with different GW too or does it have scale up by more than 10/15 for increasing GW(note: weight factor is already accounted for but I wanted to know if you need the ref speeds to increase as a factor of weight too or just 10/15knots will do it).

**Comment by toffee2000** [comment]
Now they're too high actually. 140 kt VAPP at default weight. Should be 5 kt above amber band at all weights. VREF is at the amber band exactly. TLDR: VREF = VLS CONFIG FULL, VAPP = VREF + 5

**Comment by ThePilot916** [comment]
Okay, I'm working on this right now, VAPP is currently at VLS+5. If you can let me know correctly what changes are needed for v1,v2,vr,vapp,vref,vls I can incorporate it now.

**Comment by toffee2000** [comment]
I’m not sure about takeoff, sorry. Will get back to you.

**Comment by JackZ974** [comment]
Good luck with the determination of take off VSpeeds. 
There is at least three methods to determine them, from PERF tables (very conservative), to balanced field length method, up to the newest Airbus method (used in App like Flysmart) which has not published AFAIK their method nor tables nor algorithm to determine these. 
Proper VSpeed depends on many parameters, including the runway ASDA/TORA, and the possible presence of obstacle in the 1st segment trajectory path. It's Airport related, every runway has its set of data.
T
he older methods yields to a V1 and all the set of derived data being much lower to stay on the safe side, when using PERF Tables, as tables are kinda universal. PERF Tables which are no longer published in the latest versions of the FCOM, BTW...

**Comment by toffee2000** [comment]
![0D1E19E4-67E5-4542-9DCF-5A833A3E3E73](https://user-images.githubusercontent.com/70193215/91824525-7e227800-ec6d-11ea-8abc-88bc268d1eb5.jpeg)
![9D4ABA47-D8CA-4A76-BDD0-82168C48AEEC](https://user-images.githubusercontent.com/70193215/91824529-7f53a500-ec6d-11ea-810e-716dda37214e.jpeg)
Some pictures of A320 CEO TO PERF. Do you want anything else. No NEO unfortunately.

**Comment by toffee2000** [comment]
Still too high VREF and thus too high VAPP. VREF is equivalent to the top of the amber band (130 kt at default weight). FMC VREF is wrong. VAPP is VREF + 5, so 135 in this case.
![image](https://user-images.githubusercontent.com/70193215/91850179-afac3b00-ec8f-11ea-8fa2-f7726f3a2051.png)

**Comment by toffee2000** [comment]
That said, I think flap lift is too low. Pitch should be 5-7 deg at VAPP for level flight and 2-4 deg on glidepath. At present pitch is too high at 5 kt above amber band. This would also explain the weird takeoff rotation behaviour. Too many factors to say for sure unfortunately.

**Comment by JackZ974** [comment]
> 
> 
> ![0D1E19E4-67E5-4542-9DCF-5A833A3E3E73](https://user-images.githubusercontent.com/70193215/91824525-7e227800-ec6d-11ea-8abc-88bc268d1eb5.jpeg)
> ![9D4ABA47-D8CA-4A76-BDD0-82168C48AEEC](https://user-images.githubusercontent.com/70193215/91824529-7f53a500-ec6d-11ea-810e-716dda37214e.jpeg)
> Some pictures of A320 CEO TO PERF. Do you want anything else. No NEO unfortunately.

Come on Bro. You're using the DEMO version of FlyDamart; which is unusable.

**Comment by toffee2000** [comment]
That was just an example. For landing, my comments stand.

**Comment by PCGamesF1Tech** [comment]
Do we have any access to how speed are calculated at all?
Just throwing in some numbers:
Vs1g, Vref vs. Vls, factor 0.94, reductions in allowed minimum speeds due to protections,.... 
Maybe Asobo is using one model for the A320 as well, could be wrong here...

**Comment by ThePilot916** [comment]
We do have access to how speeds are calculated in the sim, it can be updated as needed. But we can only do so once we have some concrete details on what adjustments are required. Lesser lift on the over all flight model is also a known issue.

**Comment by lousybyte** [comment]
Related #854, #855

**Comment by donstim** [comment]
Is this issue possibly still being worked? In a comment above @ThePilot916 seemed to indicate we have the capability of changing the MCDU computed speeds. Maybe it would be best to start off with the VLS and VAPP speeds since these are the easiest.  VLS can be determined from this chart of VLS vs Gross Weight provided by @MisterChocker in this pull request:  https://github.com/flybywiresim/a32nx/pull/1295
![image](https://user-images.githubusercontent.com/70166617/96356667-c0c9d380-10a6-11eb-8fca-24cb7866a44c.png)
 From an A320 Flightcrew Training Manual:
The VAPP is defined by the flight crew to perform the safest approach. It is function of the
aircraft landing weight, slats/flaps configuration, wind conditions, use of A/THR, icing conditions.
In most cases, the FMGC provides a correct VAPP value on the MCDU PERF APPR, when
tower wind and FLAPS 3 or FLAPS FULL landing configuration have been inserted.
The flight crew can insert a lower VAPP in the MCDU PERF APPR, down to VLS, if landing
is performed without A/THR, without wind and no ice accretion. In case of strong or gusty
crosswind greater than 20 kt, VAPP should be at least VLS +5 kt; the 5 kt increment above VLS
may be increased up to 15 kt at the flight crew's discretion.
The flight crew should keep in mind that the wind entered in the MCDU PERF APPR considers
the wind direction to be in the same reference as the runway direction e. g. if airport is magnetic
referenced, the crew will insert magnetic wind. The wind direction provided by ATIS and ATC is
given in the same reference as the runway direction whereas the wind provided by VOLMET,
METAR or TAF is always true referenced.
VAPP is computed at estimated landing weight while the aircraft is in CRZ or DES phase,
provided that the F-PLN is correctly sequenced and inserted in the MCDU. When the approach
phase is activated, VAPP is computed using current gross weight. Managed speed should be
used for final approach as it provides Ground Speed mini guidance, even when the VAPP has
been manually inserted.
In a general manner, the VAPP value is the sum of the VLS and the APPRoach CORrection

The APPRoach CORection is the highest of:

- 5 kt in the case of Autothrust ON
- 5 kt in the case of ice accretion in CONF FULL or 10 kt in CONF 3
- 1/3 of the headwind component (excluding gusts) and a maximum of 15 kt

**Comment by donstim** [comment]
And here are the F, S, and Green dot speeds that should be indicated on the PFD
![Screenshot (154)](https://user-images.githubusercontent.com/70166617/96400410-7c613500-1185-11eb-9a08-e48f2d766ebe.png)
