### ISSUE TITLE
[BUG] Altitude and speed decrease slowly

### ISSUE THREAD

**Issue by phildeg31** [flybywiresim/a32nx#2203]
**Mod Version**
"built": "2020-12-02T17:20:24+00:00",

**Describe the bug**
When asking to decrease altitude and speed at the same time, both decrease very slowly. It seems to be not managed correctly.

**To Reproduce**
Reduce altitude in managed mode
Reduce the speed  when altitude is decreasing.

**Expected behavior**
Altitude and speed shall decrease faster.

**Actual behavior**
I did the same flight than I did in a real A320 simulator with a pilot but I have to do actions earlier because altitude and speed decreased very slowly in game with the dev mod.

In general, when I reduce only the altitude, everithing seems fine and altitude is decreasing faster:
![Speed and altitude  1](https://user-images.githubusercontent.com/74733393/100988125-a90fb700-354f-11eb-8fc9-99d9e372e2c8.JPG)

But when I reduce also the speed, everithing is decreasing slowly:
![Speed and altitude  2](https://user-images.githubusercontent.com/74733393/100988679-436ffa80-3550-11eb-8428-852c0cedd1a7.JPG)
![Speed and altitude  4](https://user-images.githubusercontent.com/74733393/100988699-48cd4500-3550-11eb-9f9f-6c8994f85371.JPG)

In this example it took more than 10 nautical miles to decrease 2000 feets and 55 knots. It is longer than in the real A320 simulator.

If a do the same actions at the same moment than I did in the real A320 simulator, then I do not reach the altitude and the speed when it is expected but later.

If a real pilot can test and confirm my feeling because it seems not normal to me, based on my experience in the real A320 simulator, but maybe it is normal.

**Comment by MisterChocker** [comment]
looks normal to me, in fact lets to some math.
descending 2000ft at 200kt needs 6nm, (I'd actually add 1nm because we are still above FL10) however to get there we first need to decelerate.
When using current cas, we get 14nm (I'd add 1nm as before, makes 15nm)
When we compare both pictures we can see a difference of 33.5 - 19.8 = 13,7 which matches the calculation before. Probably another 1nm for level off at FL080.

**Comment by vlbreda** [comment]
This is a known issue. IMO it is caused by a too high idle thrust performance. This is probably done to get a realistic taxi performance (taxi at idle thrust), but descent and decel-behaviour is not very realistic now. You can improve this by:

* change the drag_coef_zero_lift in the flight_model.cfg file to 0.043.
* change thrust_scalar in the engines.cfg file to 0.92

**Comment by MisterChocker** [comment]
@vlbreda again, if you want to collaborate please join our discord and do so. I think the approach you take is helping nobody.

**Comment by vlbreda** [comment]
@MisterChocker: please no offense! If you think it is usefull you can try the changes I mentioned above, If you do not want to or find another solution, it's fine with me as well.

**Comment by lve0200** [comment]
its useless, he doesn't want to listen. Check #1295

**Comment by Benjozork** [comment]
@lve0200 please keep unrelated personal disagreements out of GitHub.

**Comment by Benjozork** [comment]
@vlbreda I really suggest you come discuss on our Discord with @MisterChocker about your concerns. We want to listen but GitHub is not the appropriate place to debate flight model changes as we use it strictly for objective discussion about issues and PRs.

**Comment by vlbreda** [comment]
@Ive200: I'm sure MrChoker has the same intentions as we all have: making the best A320 possible. The descent rate issue takes some time, that's for sure. Seems MSFS can't pair taxi at idle thrust with realistic descent rate. Hope some kind of solution comes up in the next stable version!

**Comment by phildeg31** [comment]
I I booked a new real A320 simulator session with a pilot to compare and to take pictures or a video. I will do the same flight with the same constraints and will compare.
Before that, I will try to get an opinion from an Air France pilot where I work.

**Comment by Benjozork** [comment]
> I booked a new session in real A320 simulator with a pilot to compare and to take pictures or a video. I will do the same flight with the same constraints and will compare.
> Before that, I will try to get an opinion from an Air France pilot where I work.

Hello, can you contact us on Discord ? That is a very interesting opportunity for us. Ping me someperson#4953.

**Comment by vlbreda** [comment]
@Benjozork ; Hi Benjamin, thanks for the discord invitation. I'm afraid however I am of very little use there. Have given some input on this subject, as stated, it's up to you whether to use it or not!
@phildeg31: that's nice, hope it gives some new insights!

**Comment by krangerich** [comment]
> looks normal to me, in fact lets do some math.
> descending 2000ft at 200kt needs 6nm, (I'd actually add 1nm because we are still above FL100 by 340ft) however to get there we first need to decelerate.
> When using current cas, we get 14nm (I'd add 1nm as before, makes 15nm)
> When we compare both pictures we can see a difference of 33.5 - 19.8 = 13.7nm distance to VELIN which comes close to the calculation before. Probably another 1nm for level off at FL080 (as predicted).

Does it make a difference if 
a) an aircraft first descends 2000ft with 290kt, then decelerated to 220kt
b) an aircraft first decelerates to 220kt, then descends 2000ft
c) an aircraft descends 2000ft and at the same time as decelerates to 220kt?

I'd guess, that a) would result in the fastest time to accomplish both, since this would allow the steepest angle and b) would be the slowest, since descending near green dot speed should take much longer?

**Comment by MisterChocker** [comment]
> I'd guess, that a) would result in the fastest time to accomplish both, since this would allow the steepest angle and b) would be the slowest, since descending near green dot speed should take much long

actually no, the slower you fly the shorter the distance you need for your descent.

**Comment by N1EL** [comment]
My view is that
The FL080 is a ALT CST,  so if you have high speed you will get there faster hence the high V/S to descend in time for the FL080 CST at VELIN,   But if you slow down the speed the V/S is able to reduce because its got more time before it reaches the FL080 point at VELIN??

Does it do that with no ALT CST on the flightplan??

Also the first screenshot has not ALT CST straight to FL030 where the two other screenshots have a FL080 CST.

**Comment by phildeg31** [comment]
I will do again the flight with selected mode only for altitude (so FL30) and then only with managed mod (so with FL80 constraint for VELIN). VELIN is an approach point so I cannot update or delete the constraint..

**Comment by donstim** [comment]
> @Ive200: I'm sure MrChoker has the same intentions as we all have: making the best A320 possible. The descent rate issue takes some time, that's for sure. Seems MSFS can't pair taxi at idle thrust with realistic descent rate. Hope some kind of solution comes up in the next stable version!

I'm sorry, but you are simply wrong about this. The  thrust at a given N1 can be specified differently at different speeds. Taxi speed is much different than flight speeds. Idle thrust at taxi need not have anything to do with idle thrust in flight.

**Comment by donstim** [comment]
> I tested in selected mode to simulate an approach.
> 
> I reduced only altitude to 4000 feet in selected mode:
> ![Speed and altitude 12](https://user-images.githubusercontent.com/74733393/101136185-3cf38880-360d-11eb-82ca-a92b8ad02753.JPG)
And you can see that you have a very reasonable descent rate in open descent at that speed
> Here the selected vertical speed seems not to be taken into account so I cannot simulate a faster descent (why?). The -20 disappeared after few seconds.

Because you are in open descent. If you want to be in V/S mode, you have to select that mode in addition to dialing in the vertical speed. You can open the window and dial in a V/S, but if you don't select the V/S mode, the dialed in speed disappears. Try that in the simulator when you are there.
> I reduced the speed to 180 knots (the aim in a real approach is to be with flaps 2 before the alignment point):
> ![Speed and altitude 13](https://user-images.githubusercontent.com/74733393/101136980-64972080-360e-11eb-8b16-6c00b439c2e0.JPG)
> When I did the flight in real A320 simulator, the speed reduction had been engaged only 10 nautical miles before the alignment point during the descent to be with flaps 2 just before the alignment point but I don't remember wat was the altitude at this moment so I will check next time. Here I started the speed reduction quicly to see the behaviour when altitude and speed are decreasing at the same time.
> 
> I reached the altitude and the speed approximately 20 nautical miles after the begining (for -3000 feet and -70 knots):
> ![Speed and altitude 17](https://user-images.githubusercontent.com/74733393/101138434-78dc1d00-3610-11eb-891a-e89bc98de572.JPG)

Be careful about parsing autopilot behavior and the flight model. We don't have our own autopilot (yet). The managed vertical mode is not fully and correctly implemented yet, and the behavior of the selected vertical mode appears to have been changed in the latest Asobo update. It used to change pitch rather aggressively to fly the selected speed, now it seems to be a bit too passive, leading to more difficulty in decelerating (or sometimes even maintaining speed) on descents. This can lead to longer distances to descend and decelerate. Hopefully, we can better address this when we have our own autopilot and can tune it and the flight model together.

In the meantime, any data you can collect from your simulator session may be helpful in doing that.

**Comment by phildeg31** [comment]
ok so that can be an explanation for my feelings. I will do a flight in the A320 simulator with photos or a video if I can and I will do the same flight after on Flight Simulator with the mod. I will make a return with the observed differences.

I still have 4 sessions of 1 hour to do on the A320 simulator including the next (19 december). I am not a pilot but if I can help ;).

**Comment by Aarondodd88** [comment]
I can also confirm. On approach with full flaps and power idle, the airspeed slows down by 4kts in 13seconds then. You can fly the approach from the final approach fix with no engines and full flap without losing any airspeed. Move Thrust to 42% and airspeed doesn't increase. Adding more flap angle increase's the lift coefficient under the same angle of attack, at the expense of higher drag, which equates to more thrust due to drag. You can notice this on landing the most, when you retard to thrust idle, flare and maintain level flight and the aircraft doesn't fall onto the runway, in fact you still have huge amounts of elevator and aileron control and can climb out again, this is due to no form drag from the flaps or very little.

**Comment by donstim** [comment]
At Vapp, full flaps, and established on the glideslope, N1 will typically be in the low 40's or high 40's, depending on weight. Reducing thrust to idle will lead to either a speed reduction, a vertical speed increase, or both. I tried your example of shutting my engines down at the final approach fix and ended up stalling and crashing well short of the runway. Video:  https://1drv.ms/v/s!Ajsy7Ey4_8uFyBLtyyUd_XqhSZym?e=qRXqGu

I also tried your example of retarding to idle early, flaring, then maintaining level flight. I made it to the end of the runway before stalling again. At Vref, which is the speed over the threshold, the airplane, by regulation, has a 23% margin to stall and plenty of elevator control authority. It also must have a 40 degree bank angle capability, so there should be plenty of roll capability as well.  Transport category airplanes are not like GA airplanes where you basically stall the airplane at landing. You must fly the airplane to the runway, using the flare to reduce your descent rate before touchdown.

Try flaring at 20-30 feet, followed by reducing thrust to idle.  There does appear to be too much ground effect in MSFS, which currently appears to be hard coded in, and could lead to floating more than it should.

If you don't mind, could you also check to confirm that your flight model in MSFS - options - general - flight  model is set to "modern." Some folks have had their flight model set to legacy by one of the Asobo updates. Otherwise, could you provide a video showing your concerns?

**Comment by MisterChocker** [comment]
> any airspeed and still climb out at 110kts after flaring.

I should point out that the airspeed is not a good reference, I can pitch up at almost any speed and you get a positive vs as a result.

**Comment by phildeg31** [comment]
Hi,
I did the flight in the A320 simulator. I am uploading the videos now and I will put a link here.

I will do the same flight in Flight Simulator with the mod tomorrow (cfbw because I have the thrustmaster quadrant).

The flight has been done with managed mode only.

**Comment by Benjozork** [comment]
> 
> 
> @Benjozork ; Hi Benjamin, thanks for the discord invitation. I'm afraid however I am of very little use there. Have given some input on this subject, as stated, it's up to you whether to use it or not!

I was asking @phildeg31.

**Comment by Benjozork** [comment]
> 
> 
> Hi,
> I did the flight in the A320 simulator. I am uploading the videos now and I will put a link here.
> 
> I will do the same flight in Flight Simulator with the mod tomorrow (cfbw because I have the thrustmaster quadrant).
> 
> The flight has been done with managed mode only.

If you have access to A320 simulators, that is very interesting for us. Feel free to share anything you find useful.

**Comment by phildeg31** [comment]
I sent you an invitation in discord. Normally you must have received it.

**Comment by MisterChocker** [comment]
@phildeg31 which level has the simulator? It's important because of the accuracies of the results.

**Comment by phildeg31** [comment]
What do you mean by level?

It is an A320 simulator used for pilot training and also accessible by individuals by paying sessions.

**Comment by phildeg31** [comment]
Here is the link: https://youtu.be/Z7s89YvUexs

**Comment by donstim** [comment]
Okay, I tried repeating your simulator flight using MSFS. First , a few notes/caveats:
1. I am not familiar with LFBD and could not find the approach you were using, so I just tired to find something similar
2. I don't know what constraints you were trying to follow in managed altitude mode, and since our VNAV isn't done yet, I just tried to match your altitude profile using vertical speed.
3. It appears to me that the simulator you were flying was not a neo. For the VLS speed shown in the quick shot of the MCDU you gave us, the S and Green dot speeds were significantly different than those for a neo.
![Screenshot (455)](https://user-images.githubusercontent.com/70166617/102706929-1a877f00-424b-11eb-963e-a71aa01b2a88.png)
![A320 Operating Speeds](https://user-images.githubusercontent.com/70166617/102706937-2d9a4f00-424b-11eb-84d8-97a54353b8cf.png)

4. MSFS doesn't have a realistic range for the ILS signals, so I could not capture and fly them as soon as you could. However, I continued to try to match your vertical speed. (1300 fpm on the glideslope seems a little odd to me.)

That having been said, and admittedly I was not perfect in recreating your fight (first try), I did not see any difficulty in flying the same profile.

https://1drv.ms/u/s!Ajsy7Ey4_8uFyBnBfH_Xh1x-9XiT?e=6WusY3

**Comment by phildeg31** [comment]
I confirm it is an A320 simulator and not an A320 neo simulator. 

Is there a big difference?

For the approach and the route, we made some changes because of time. I will give waypoints and constraints later because I have to check photos for that.

**Comment by phildeg31** [comment]
I did the test and that's OK for me.

I had some differences like the top of descent that was 20 miles before the BMC35 waypoint instead of 10 miles in the A320 simulator but if I respect the TOD in game, the descent was good in my opinion.

The only difference I noticed was on the speed reduction towards green dot after the deceleration point which was not as fast as in the simulator.

**Comment by donstim** [comment]
The TOD symbol in game right now is known to be off. It's being worked on along with VNAV capability.

Regarding the speed reduction difference, the neo is a little more slippery than the ceo that you flew in the simulator. I have not been able to find ceo descent/decel data like we have for the neo, so I can't quantity exactly how different they are,  Were you using V/S mode at the time to match the altitude profile? 

I thought it was interesting that the simulator did not comply with the 250 knot restriction below 10,000 feet, he had you intercept the glide slope at such a high altitude, didn't have you go to CONF 1 until you were descending on the glide slope, then had you lower the gear while still in CONF 1.

**Comment by phildeg31** [comment]
For altitude management it is OK so I think I can close this ticket.

Can you just take a look on the speed reduction rules please? I was not able to change to flaps 1 because the speed decreased just above the flap exit symbol (yellow/brown equal symbol) and stayed above until altitude was reached (3000ft).

**Comment by donstim** [comment]
The A320neo we are modeling does not have the continuous descent (CDA) option. I don't know if any of the neos have it yet.

I think the speed issue is an autopilot issue. Like you said about your simulator flight, the descent is favored over the speed, but even more in MSFS. You can work around it by going to V/S mode and reducing your descent rate to allow the speed to go down. This shows that the flight model is capable of doing it, but the autopilot does not allow it if you are in open descent mode.

**Comment by phildeg31** [comment]
Ok thank you :). Do you want me to close this ticket as you did a correction for altitude management?

**Comment by donstim** [comment]
Yrs, please. Thank you! (Merci!)
