### ISSUE TITLE
[BUG] QNH & QNE wrong indication

### ISSUE THREAD

**Issue by Kimbyeoungjang** [flybywiresim/a32nx#2205]
**Mod Version**

latest master(2020/12/3)

**Describe the bug**

QNH is showed when choose IN HG but it is not.
also, QFE is showed when choose HPA but it is not

**To Reproduce**

1. start aircraft
2. change IN HG to HPA
3. see PFD

**Expected behavior**

QNH show when choose IN HG

**Actual behavior**

Both mode(INHG and HPA) showed QNH
![image](https://user-images.githubusercontent.com/23118756/101013636-f28bf080-35a7-11eb-8066-7b6e99f2d5a3.png)
![image](https://user-images.githubusercontent.com/23118756/101013659-f91a6800-35a7-11eb-8d24-044f068dbd79.png)

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by beheh** [comment]
I'm really not sure what this issue is about.

> QNH is showed when choose IN HG but it is not.
also, QFE is showed when choose HPA but it is not

In your screenshots QFE is never shown on the PFD, so the bug report does not make sense. You're also missing the full template: Was this working before/when did the issue start occurring? Is this a problem in the vanilla unmodded game?

I think you might be confusing QFE vs. QNH with IN HG vs. HPA? Those are two completely independent choices, once describes the barometric reference (sea level vs ground level/height) and the other sets the unit (Huygens vs Hectopascal). Both those choices can be made on the FCU independently.

**Comment by Kimbyeoungjang** [comment]
> Huygens

![image](https://user-images.githubusercontent.com/23118756/101017909-12261780-35ae-11eb-8e1e-ae175558b744.png)

because i working with pfd.

that code mean when inhg knob selected, showed like QNH 29.92
when hpa knob selected, showed like QFE 1013 isn't it? or that value changed by other factor?

**Comment by Kimbyeoungjang** [comment]
> > Huygens
> 
> ![image](https://user-images.githubusercontent.com/23118756/101017909-12261780-35ae-11eb-8e1e-ae175558b744.png)
> 
> because i working with pfd.
> 
> that code mean when inhg knob selected, showed like QNH 29.92
> when hpa knob selected, showed like QFE 1013 isn't it? or that value changed by other factor?

because when i working with qnh flashing, aircraft sometimes show QNH and sometimes show QFE randomly 

i was airborn 8,000ft on sea.

**Comment by beheh** [comment]
The baro knob has 3 different settings:
- pull to toggle STD/actual value
- push to toggle between QNH/QFE
- rotate at the bottom to switch between IN HG/HPA

The button in the sim supports all these 3 different settings. They are unrelated to each other. For example, you can operate QNH in IN HG, you can operate QNH in IN HG, or QFE in IN HG etc.

**Comment by N1EL** [comment]
I agree with the others,  Both screen shots show the QNH, 
The top shot is set at IN HG 
The bottom shot is set to HPA
This is an issue.
