### ISSUE TITLE
Autopilot and FD Problem with Speed

### ISSUE THREAD

**Issue by Hor1463** [flybywiresim/a32nx#2219]
After TO the aircraft ignore the speedlimits with Version 0.42 and MSFS 2020 update. Putting in the AP doesn´t mater, the speed goes up to 300 knt under 10000 Feet. Why does the MCDU Menue dosen´t work in this version. The unsave version has the oportunity to read the METAR in ATSU?
Roland

**Comment by Hor1463** [comment]
Next issue, the aircraft is slowly shaking from left to right in climb.
Roland

**Comment by Benjozork** [comment]
>Why does the MCDU Menue dosen´t work in this version. The unsave version has the oportunity to read the METAR in ATSU?

It's a feature of the development version staged for 0.5.0.

As for your other issues, you need to open proper bug reports because you completely ignored the template we provided you with. Also, do not open one report for multiple problems. Your instability issue in flight is already reported in #2005.

If you are not familiar with using GitHub I recommend you ask for help on our Discord server instead.
