### ISSUE TITLE
[BUG] wrong TRIP init fuel prediction 

### ISSUE THREAD

**Issue by airfirefighter** [flybywiresim/a32nx#2324]
**Mod Version**
built: 2020-11-13T18:49:49+00:00
ref: refs/heads/master
sha: 72e7b0c830e17d7984b3aca2dd852cce8ca7662c
actor: Benjozork
event_name: push

**Describe the bug**
![image](https://user-images.githubusercontent.com/71919620/101682415-45641d00-3a6c-11eb-86e7-82ddab117567.png)
as u can see in the image the TRIP/TIME its the total of 0.3+1.3+0.9+2.1= 4.6 /0218.this is wrong if this is the block time for fuel prediction u must not add the total of MIN DEST FOB 2.1 .the same if its the prediction of consumption for the trip without  altn and reserves...only for the 02:18 .so in the flight i just did  i arrived at the approach with consumed 3.3 kg of fuel (this is the fuel needed for a flight of 2:18 because 4.6 - 1.3 alternative =3.3 kg 
![image](https://user-images.githubusercontent.com/71919620/101687279-ef46a800-3a72-11eb-8779-0c0d2dc276cc.png)
as u can see also in this video 
https://www.youtube.com/watch?v=D7HjVlvKd8o at 5:59   at the trip if add RTE+ALTN+FINAL+MIN u dont have trip as u have here 
**To Reproduce**
in fuel prediction add RTE+ ALTN+ FINAL+ MIN= TRIP  

**Expected behavior**
the TRIP must calculate the fuel needed for the time from take off to land at the airport.No any additional fuel.

**Actual behavior**
the trip fuel have the correct time of flight but not the fuel needed for the flight (have more that needed) its the total of RTE RSV, ALTN, FINAL , MIN DEST FOB

**References**
abbove

**Comment by Benjozork** [comment]
> **Mod Version**
> it doesn't matter

We need the version you are running to rule out some logic changes in the code. Please provide it 😄

**Comment by airfirefighter** [comment]
> > **Mod Version**
> > it doesn't matter
> 
> We need the version you are running to rule out some logic changes in the code. Please provide it 😄



> > **Mod Version**
> > it doesn't matter
> 
> We need the version you are running to rule out some logic changes in the code. Please provide it 😄

done sorry!! for me still doesn't matter 😄😄 lol

**Comment by Benjozork** [comment]
See ? Your build is a month old ! Try updating and see if the issue is still there. We'll see if there's anything we can improve that we haven't fixed yet.

**Comment by airfirefighter** [comment]
> See ? Your build is a month old ! Try updating and see if the issue is still there. We'll see if there's anything we can improve that we haven't fixed yet 🙂

how i update it every day from the downloader! im sure for ur great work thats why iam a a32nx lover!!!

**Comment by airfirefighter** [comment]
i delete everything and reinstall from the downloader. the predictions are the same.i thing there is an error.As i mention above the trip is 4.6 and i use 3.3 so the trip 4.6/ 2:18    is  the total of fuel used 3.3 and fuel need for alternative airport 3.3+1.3= 4.6 something that not correspond to trip time 2:18

**Comment by Lucky38i** [comment]
> **Actual behavior**
> the trip fuel have the correct time of flight but not the fuel needed for the flight (have more that needed) its the total of RTE RSV, ALTN, FINAL , MIN DEST FOB

Trip time only corresponds to the required fuel needed to go from the origin to the destination. It does not account for any of the extra bits you suggested needed to produce the trip fuel. 

Bear in mind the fuel consumption is currently off, in the plane. The fuel predictions for the MCDU is based off the real aircraft. It also looks like you manually entered your own min dest FOB as signified by the text being big rather than small, same goes for the alternate.

I don't know the exact Air Distance, current plane weight, nor your cruising altitude so I can't recreate your flight. However, I do have your flight time and based on that, I can take a guess at the fuel needed for for the flight.

Your flight time is stated as 2H and 18M, Based on the image below, the required fuel is between 3.7Tons - 4.4Tons without any corrections for the aircraft's current weight which is shown in the **corrections** table. I think it's safe to say that the fuel predictions are close enough to what they need to be.

Just to clarify fuel prediction is produced from one of those static values + a deviaiton. The deviation is `(ZFW + Final Fuel + Alternate Fuel - Reference Weight (on the table)) * The correction value based on FL & airdistance`
![1 (30)](https://user-images.githubusercontent.com/26572019/101761471-197c8200-3ad4-11eb-9667-c575b5967b1d.png)

**Comment by airfirefighter** [comment]
![image](https://user-images.githubusercontent.com/71919620/101769156-396d6f00-3aef-11eb-940f-04e39d595820.png)
![image](https://user-images.githubusercontent.com/71919620/101769209-4c803f00-3aef-11eb-91aa-61c76e0635e2.png)
hi m8! those are the image without any manually add! my opinion its 3.4 and 4.4 so 1 tone  is a big difference if we said that the plane consume 1200kg per h more or less.Maybe iam wrong tell me to delete this issue post and i will if u thing that everything is ok.

**Comment by Lucky38i** [comment]
Yes but did you read the performance charts I submitted? it goes in hand with what I said about corrections based on weight. If you try changing min dest fob, final, rsv or altn you'll notice that trip fuel doesn't change.
