### ISSUE TITLE
[BUG] ? Following Flight Plan after arrival entered ? Possible user error?

### ISSUE THREAD

**Issue by johnwillimas** [flybywiresim/a32nx#2350]
**Mod Version**

Master

**Describe the bug**

When en route, following entry of arrival detals to the MCDU aircraft back tracks to previous waypoint.

**To Reproduce**

1. Carry out flight LGIR to LGAV
2. Approaching waypoint KEA, atc advises approach. 
3. Enter approach into MCDU and press INSERT

**Expected behavior**

Following press of INSERT aircraft should continue on to next way point.

**Actual behavior**

Aircraft commences return to KEA and then resumes plan (effectively 360 degree turn)

**References**

**Additional context**

Maybe an operator input problem but I have followed 320 Sim Pilots video tutorials.

Was this working before/when did the issue start occurring?

I feel this has been continuous since first stable release.

Is this a problem in the vanilla unmodded game?

Not known.

Discord username (if different from GitHub):

**Comment by WoodyWoodsta** [comment]
I have this as well, currently running the development version. I do believe this to be a bug at the Asobo level as well, since I have experienced this in G1000 and G5000 FMS's. If ATC gives me the approach early enough, the route remains intact, but if ATC gives me an approach which starts at a waypoint I've already flown, it restarts the entire approach. It just so happens that ATC in no way anticipates your approach requirement long enough before so it happens to me almost every time.

**Comment by carlosgaucho** [comment]
I have similar issue using A32nx developer builds for last few weeks. KIAH - KTUS ils11 approach, instead of going to last waypoint in flight plan, automatically turns directly towards airport heading. If I remove the A32nx folder and use the standard a320 with msfs, this is not an issue.

**Comment by WoodyWoodsta** [comment]
@carlosgaucho I think what you are actually referring to is captured in https://github.com/flybywiresim/a32nx/issues/2345. This issue is describing something different.

**Comment by carlosgaucho** [comment]
@WoodyWoodsta thanks, you are correct

**Comment by DaBeLG** [comment]
tip the cj4 mod solves this to enter the waypoint on the vector msfs enters in the ap

maybe tip!

https://www.youtube.com/watch?v=I2Darcr8HZA

**Comment by DFWSupertrooper** [comment]
The duplicate waypoints are entering into the MCDU on the A32NX mod v.5 stable.  This has occurred for me 100% of the flights since v.5 install where STAR is configured.  To be clear - the waypoints are already in the MCDU flight plan twice - once as part of the filed route from MSFS and once as part of the actual arrival.  Sometimes it also adds another separate leg of the same STAR as well.  All have to be cleared on approach to remove the duplicates and bad legs leaving only the correct filed one as intended.
