### ISSUE TITLE
[BUG] CoPilot NAV knobs not working after last MSFS update

### ISSUE THREAD

**Issue by Marenostrum66** [flybywiresim/a32nx#2639]
**Mod Version**
 last master build 2020-12-23T05:47:30+00:00 

**Describe the bug**
1.  Copilot nav knobs rotate but does not affect the range and mode in the NAV display
2.  NAV display is synced with the Pilot range knobs 
Before the last MSFS update both copilot knobs worked independently

**To Reproduce**
1. from cold and dark setup the aircraft and the IRS. When NAV display pops up, move the copilot knobs: they will rotate but the copilot nav display will not change 
2. move the pilot knobs: they will act on both NAV displays 

**Expected behavior**
copilot and pilot knobs have to work independently in the relative nav display

**Actual behavior**
both pilot/copilot knobs rotate but only the pilot knobs act on both NAV displays simultaneosly

**References**
the image shows the copilot nav display with the same range of the pilot nav display accordingly with the pilot range knob: copilot range knob is set to 20 to another range but it deos not acts on the copilot nav display
![20201223 range knob](https://user-images.githubusercontent.com/74383127/102978292-94965d00-4504-11eb-8298-879012201c9d.JPG)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?
do not know

**Comment by pareil6** [comment]
Also reproduced this - both displays are controlled by the captain range/mode knobs (and VOR/ADF switches)(, copilot switches have no effect.

**Comment by wpine215** [comment]
Related #2640

**Comment by DFWSupertrooper** [comment]
I concur...the same observed.

**Comment by pareil6** [comment]
For the benefit of anyone more able to debug this than me - both screens are connected to the correct switches and are rendering in the background, but the assignment for VCockpit01/VCockpit02 in panel.cfg seems to be getting applied to both actual displays (ie. I can switch to the co-pilot PFD/MFD by swapping the Index to 2 instead of 1). A quick search hasn't found anything obvious for why it's broken, but someone who knows how the panel config maps onto the model will be better placed to debug that than I am.

**Comment by Benjozork** [comment]
We know how to resolve the issue, but have not decided yet if we will for performance reasons.
