### ISSUE TITLE
[BUG] A32NX dev and stable not compatible with new Test Pilot livery.

### ISSUE THREAD

**Issue by TenPatrol** [flybywiresim/a32nx#2712]
**Mod Version**
2020-12-25T10:12:36+00:00

**Describe the bug**

**To Reproduce**
1.EPWA - c&d
2.turn on: ext power, bat 1&2
3.ADIRS - nav
4. turn on pumps
5. turn on apu and apu bleed

**Expected behavior**
Without new livery  (Test Pilot) everything ok.

**Actual behavior**
With new livery (Test Pilot) not working properly:
**EFIS Control Panel**
- buttons - cstr, vor D, WPT,NDB,ARPT.
- selector - plan, arc,nav,vor,LS
- range selector

- FO screens always white

**References**
**With Test Pilot livery.**
![obraz](https://user-images.githubusercontent.com/71746362/103140916-fa453d80-46ec-11eb-87dd-815005f1b7de.png)

![obraz](https://user-images.githubusercontent.com/71746362/103141011-886df380-46ee-11eb-851b-415325896dce.png)

**Without Test Pilot livery**
![obraz](https://user-images.githubusercontent.com/71746362/103141044-0af6b300-46ef-11eb-89e4-db8c6de171d8.png)

![obraz](https://user-images.githubusercontent.com/71746362/103141145-3332e180-46f0-11eb-9c86-d12cdffbdbca.png)

When did the issue start occurring?
After update to game version 1.12.13.0

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): _Patrol#9513

**Comment by wpine215** [comment]
Unfortunately, the test pilot livery includes its own version of panel.cfg (in order to change the registration font color to white), and that overwrites our own panel.cfg which is needed for separated F/O displays and EFIS.

Because Microsoft/Asobo have decided to package the test pilot livery in an encrypted FSARCHIVE file type (like the 787), there is nothing we can do to resolve this - we recommend reaching out to them and expressing your concern.
