### ISSUE TITLE
ECAM FUEL page is wrong

### ISSUE THREAD

**Issue by Airbusinsider** [flybywiresim/a32nx#28]
![SD FUEL 320 NEO](https://user-images.githubusercontent.com/70146837/91046705-33738100-e619-11ea-8fa2-0ad629d38944.jpg)

The A320 NEO has the jetpumps of the A321.

**Comment by JackZ974** [comment]
interresting. Do you have the FCOM of the Neo?

**Comment by Airbusinsider** [comment]
Yes, ACT is optional. All stuff with the * in triangle is an optional item.
Yes, I have the FCOM for Neo.

**Comment by Curtis-VL** [comment]
According to real pilots, there are different versions of the Neo, the version in FS2020 has a different pump design to the one referenced above; This can be seen by the 2 center fuel pump P/B's on the overhead panel, the other design only has 1 P/B for the fuel pump.

If this is still an issue, please join our Discord to discuss this further! Closing as the issue as it is old issue, please create a new issue if there is further evidence to say otherwise, thanks! 👍

**Comment by Curtis-VL** [comment]
Scratch that, re-opening issue after further investigation with some pilots; I think we were just misunderstanding it? Looks like all Neo's use the same and newer fuel system?

I can't guarantee this will be fixed any time soon though! This is a big problem and will be in the todo list for a very long time I'm afraid. Changing the model of the aircraft is a big deal!

**Comment by Curtis-VL** [comment]
This is a tough one to label! I'm going to label it as a 'bug-vanilla', as it's a vanilla bug, even though we've edited the fuel panel... Becauseeeeeee, it requires us to re-model part of the aircraft to fix the vanilla bug to fix our own bug. If you followed that. 👍
