### ISSUE TITLE
[REQUEST] MCDU - PRINT option for ATIS/METAR/ARCARS

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#2803]
**Is your feature request related to a problem? Please describe.**

Maybe it is possible to connect the MCDU to the printer to print ATIS/METAR´s etc.
Also It would be very realistic when the printer automatically prints when a "company message" arrives, like an option IRL.  (may with an option for en-/disabling)

Again, thanks to all of you developers from FlyByWireSim for this awesome Project and all your hard work!

**Describe the feature you'd like to see implemented**

-Option to Print METAR´s/ATIS´s etc
-automatically and manual print-option, when "company Message" has arrive after a request (mostly WX/ATIS/ACARS)

**References**

like IRL the displayed message could be printed by the printer after hit the PRINT button, or it prints automatically when a "company message" arrived.

**Additional context**

Discord username (if different from GitHub):

**Comment by Rameyuk** [comment]
It would be nice if pressing the PRINT button would auto-populate the necessary fields in the PERF page for the approach conditions. I agree with the real printing option though.. Even though I won't be using it, since I prefer paperless processes. Gosh I can't imagine how much paper I would be wasting just for printing METARs in a simulator. But that's just me.

**Comment by beheh** [comment]
The printer integration has been done by #3135. Please open a separate request for the auto-population.
