### ISSUE TITLE
[REQUEST] Possible wrong values in flight model.cfg file

### ISSUE THREAD

**Issue by ghifede89** [flybywiresim/a32nx#2912]
**Is your feature request related to a problem? Please describe.**
There are some values in the flight model.cfg ( [AIRPLANE GEOMETRY] ) file that may be wrong.

**Describe the feature you'd like to see implemented**

- empty_weight = 90400 ; Empty weight, (LBS) ---- should be 90389 (references: attached document from airbus + simbrief acft configuration)

- wing_root_chord = 21 ; Wing root chord croot (FEET) ---- should be 19.91 (Reference "General aircraft dimensions" sheet 2 of 2)

- htail_area = 200 ; Horizontal tail area (SQUARE FEET) ---- should be 268.74 (Reference: manual calculation using scaled drawing of a320 neo. method: [(10.86+4.07) * 18]/2= 134.37 (referred only to one side...both sides= 268.74) )

- htail_span = 41.3 ; Horizontal tail span (FEET) ---- should be 40.85 (Reference: "General aircraft dimensions" sheet 1 of 2)

- elevator_area = 150 ; Elevator area (SQUARE FEET) ---- should be 73.37 (Reference: manual calculation using scaled drawing of a320 neo. method: split total area in parallelogram plus triangle. (17 * 1)+(16.9 * 2.33)/2= 36.68 (referred to one side...both sides= 73.37) )

**Now the datum and C.G. side.**
I am not sure about following data took from [AIRPLANE GEOMETRY] section of the flight model.cfg file because datum should be 2.54m (8.33 ft) fwd of the aircraft nose (I attached a reference image as a starting point to talk about it).
I am assuming FS uses a reference datum position somewhere above or just a little fwd of the wing because it seem coincident with "wing_pos_apex_lon" value.
I think this can possibly affect longitudinal behaviour of the aircraft so i wanted to point this thing out to discuss the whole thing with you, i also provided some modified data.

- reference_datum_position = 0, 0, 0 ; Position of reference datum relative to FS(0,0,0) (FEET), z, x, y ---- datum could be moved 8.33 ft fwd of the acft nose

- wing_pos_apex_lon = 0 ; Longitudinal (z) position of wing apex w.r.t reference datum (FEET) ---- wing_pos_apex_lon could be moved -48 ft aft of datum

- htail_pos_lon = -70 ; Longitudinal (z) position of horizontal tail  w.r.t reference datum (FEET) ---- htail_pos_lon could be moved -124 ft aft of datum

- vtail_pos_lon = -65 ; Longitudinal (z) position of vertical tail  w.r.t reference datum (FEET) ---- vtail_pos_lon could be moved -118 ft aft of datum

If my intuition is correct there also may be other values to modify in [AIRPLANE GEOMETRY].
Let me know what you think.

**References**

![Screenshot (181)](https://user-images.githubusercontent.com/76997018/103812330-a9bfcf80-505e-11eb-8875-68dd61960d23.png)
![Screenshot (182)](https://user-images.githubusercontent.com/76997018/103812340-adebed00-505e-11eb-8243-3e2e32993bc0.png)
![Screenshot (183)](https://user-images.githubusercontent.com/76997018/103812346-afb5b080-505e-11eb-81bf-1a6a64215573.png)
![Screenshot (184)](https://user-images.githubusercontent.com/76997018/103812354-b2b0a100-505e-11eb-8839-783e5a15aabb.png)
![mass-and-balance-16-728](https://user-images.githubusercontent.com/76997018/103812392-bfcd9000-505e-11eb-8534-dab3fcfd5d4a.jpg)

**Comment by MisterChocker** [comment]
cc. @donstim

**Comment by donstim** [comment]
With the new flight modeling system being used by MSFS, the aerodynamic forces and force distributions are now determined in large part by the airplane geometry as set in the flight_model.cfg file. The airplane geometry also needs to be matched with the 3-D model defined for the airplane.  What this means is that the airplane geometry is supposed to first be matched up with the 3-D model, then  the (relatively few) aerodynamic parameters that continue to be used by the modern flight model need to be "tuned" to provide realistic airplane performance. So, any changes to the geometry variables need to be checked to see if they cause inconsistency issues with the model, then to see if any of the aero parameters need to be tweaked.

Because of this, in making changes to the flight model, I have generally "accepted" the incorrect Asobo geometry values as being part of a "package" that, if necessary can be tweaked through the aero variables without affecting the model, which we currently do not have access to. The only geometry values we have changed so far to match the real airplane are those that have either no or limited affect on the model, or the changes were small enough as to not be noticeable on the model, AND, they either did not affect the aero performance or they were related to changes that we were making in the aero performance and therefore the aero parameters were being changed anyway and could be tweaked to be consistent with the geometry changes.

I am concerned that making the suggested changes to the geometry variables will cause issues in matching with the 3-D model, and will need extensive testing to ensure that they either don't affect the airplane's performance, or that the aero parameters will need to be tweaked to retain the intended performance with the geometry changes.

**Comment by ghifede89** [comment]
(I tried replying directly the email I got from you via GitHub but it is the first time I reply to a comment here so I think I did something wrong). 

Ok, I understand the problem you described. 
With a custom a320 3d model maybe it would have been easier. 

Anyway, if you feel that I can help you by doing these geometry calculations for the a380 (which I am sure will have a brand new 3d model) I would be happy.

Thank you for your reply and for the edit!!

**Comment by derl30n** [comment]
@donstim is this still relevant?

**Comment by donstim** [comment]
> @donstim is this still relevant?

Not really. All geometry values were re-checked recently and revised as necessary. The revised values for the wing root chord and the horizontal tail span are the same as those suggested by the author of this issue. Empty weight depends on operator configuration. The value we are currently using was chosen to be consistent with the passenger cabin layout we chose. Tghe horizontal tail area is from a more reputable source than estimating it from drawings. The only geometry value that may still be debated due to a lack of good sources is the elevator area.

Regarding the reference datum -- the reference datum for use in MSFS is entirely arbitrary. It need not be the same reference datum used by the airplane manufacturer. Since the every positional setting in the flight model.cfg file is relative to the reference datum position, one just has to make sure that these positional entries are consistent with the choice of the reference datum position. It is usually easier to use the airplane manufacturer's reference datum if the manufacturer's position entries for all the other objects relative to that reference datum are also known, but there is no need to do this.

**Comment by derl30n** [comment]
Thanks for your response, so I'll go ahead and close this issue, if necessary one may open an issue for the datum.
