### ISSUE TITLE
[BUG] the CRUISE page no longer appears

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/a32nx#3020]
**Mod Version**
master
```
{
  "built": "2021-01-13T04:35:18+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}
```

**Describe the bug**
Instead of the CRUISE page, the ENGINE page is stuck on the lower ECAM during both climb and cruise.

**References**
![image](https://user-images.githubusercontent.com/3490872/104463981-b5594c00-55b2-11eb-859c-574c465d3252.png)
![image](https://user-images.githubusercontent.com/3490872/104463995-ba1e0000-55b2-11eb-98d0-65238a64299c.png)

**Additional context**
~~Yesterday (12-01) this was still working fine, so probably some of the commits made during that day broke it.~~

**Comment by lukecologne** [comment]
Can you confirm the engine mode selector was in NORM, and not in start?

**Comment by Venorcis** [comment]
> Can you confirm the engine mode selector was in NORM, and not in start?

Ah that's probably it actually, I had a severe icing warning, telling me to set it to IGN/START. It was already reverted when taking the screenshots though.

**Comment by lukecologne** [comment]
It takes a few seconds to disappear again

**Comment by Venorcis** [comment]
> It takes a few seconds to disappear again

No, the lower ECAM is really stuck in ENGINE now for the whole flight, even with the engine mode selector set back to NORM.

**Comment by Khitiara** [comment]
Can confirm this issue on my flights, was able to fix the issue sometimes (though its kinda unreliable) by selecting the status ECAM page and then hitting the all button once the light for the status page fades fully in

**Comment by Berstad** [comment]
Also experienced this issue. I think it was due to forgetting to switch the eng mode to Norm until after takeoff. @Khitiara's solution fixes it, sort of, although if you use any of the other ECAM pages it will default back to Engine again. Also "All" doesn't seem to work when the ECAM is bugged like this.

**Comment by Aseinsha** [comment]
Just to add to this if I may, whenever engine mode knob is moved to the Ignition position and then back to Normal after take off, ( can be due to icing conditions during climb, cruise, or decent) the lower ECAM page will stay on the engine page and no matter what I seem try I cannot get it go back to cruise. 

ECAM should go back to cruise after moving engine mode knob to Normal.

**Comment by 2hwk** [comment]
I'll have a go at reproducing and fixing.
