### ISSUE TITLE
[BUG] RTO Autobrake Max Logic Not Working

### ISSUE THREAD

**Issue by BritishAvgeek** [flybywiresim/a32nx#3042]
Version: **Master**

{
  "built": "2021-01-14T01:24:34+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**
About a month ago a re-logic of the autobrake was being worked on and everything was working well during testing for this (I was one of the QA testing that). During today's recent test on an unrelated PR, I went ahead and conducted 3 RTOs but noticed every time the Autobrake MAX didn't switch to decel and actually apply the brakes.

I checked against 50kts, 75kts and 100kts on each occasion but at no time did it take over the moment the throttle was moved rearwards down to idle. Everything else (speedbrake for e.g.) deployed as expected but Autobrake Max did not.

**To Reproduce**

1. Spawn C&D, set up for the departure and select Autobrake Max
2. Begin the takeoff roll, when thrust set and rolling, bring throttle to idle - observe for the PFD and "the effect of braking"
3. Try at multiple speeds

**Expected behavior**
During takeoff roll, throttle drops to idle - brakes to automatically be applied on Max

**Actual behavior**
During takeoff roll, throttle dropped to idle - speedbrake deployed as expected but there was no braking at all (not even Low) until I manually braked

**References**
N/A

**Additional context**
N/A

Was this working before/when did the issue start occurring?
Not sure - the QA tests I did for the PR a month or so ago worked fine from memory but the test today gave me cause to perform RTOs to re-check specific things prior to departure and that's when I noticed this

Is this a problem in the vanilla unmodded game?
Likely

Discord username (if different from GitHub):  BritishAvgeek#1436

**Comment by Uppi93** [comment]
Same problem as described above on latest dev version.

**Comment by donstim** [comment]
There is something wrong with the initialization of the setting. If I select max autobrake, then deselect, then re-select it, it works.

**Comment by MStallen** [comment]
(in DEV)
If I select autobrake Max then I also set offset 2F80 to 0 (initial it's 1). As soon as I use the brakes then offset 2F80 switches back to 1 and though the autobrake Max stays on, it won't work on a rejected T/O.
I programmed that on release off my brakes the offset 2F80 switches back to 0 and then the autobrake work every time.

This also explains if you reset your autobrake just for T/O that it also works, because you then set 2F80 back to 0.


(2F80 was originally the autobrake settings)

**Comment by MStallen** [comment]
After solved my problem with the autobrake on t/o. I'm working on the landing, because it doesn't look that autobrake is working there. Pushing lo or med set also 2F80 to zero, so that's not the problem. But on landing I have no decelaration (also no decel lights).
I'm also looking for the lvar or offset, where you can see that the autobrakes are working (decel light on). Can't see any change in a var in the model behaviour when decel lights come on and als offset 0C46 (Autobrake_Active) is not changing.

**Comment by JEP795** [comment]
> works

Hey Don,

I was testing it today and it seems like this is the issue. If spawning cold and dark, follow all procedures attempt RTO it works. If spawning on runway, you need to press the button off and turn back on to initialize. If you land and use your auto brakes, or perform an RTO at any point in time, you will not be able to perform an RTO following any prior activation of the auto brakes. I have not tested it by shutting aircraft engines down as you would in a turnaround, but I can confirm I can’t get the Max auto brakes to deploy at any point after any auto brake setting has been used in the same flight.

**Comment by Road-to-Hell9** [comment]
Will there be a fix or is the Solution just to turn Autobrakes Max off and on again?
