### ISSUE TITLE
[BUG] Overflow with flight plan coordinates

### ISSUE THREAD

**Issue by Saschl** [flybywiresim/a32nx#3076]
**Mod Version**

Latest master/ will provide details

**Describe the bug**

The current flight plan manager calculates the delta of two waypoints with the following calculation`: Math.abs(lastLong - `this.latLong.long)`
It seems like longitude is represented in values from 0-180 and -180-0
When two waypoints are in the border regions (e.g 178 and -178) the calculation gives wrong results and basically create a plan in the wrong direction .
**To Reproduce**

1. Enter NZDA/NTAA as destination/departure
2. 
3.

**Expected behavior**

Around 2000nm distance

**Actual behavior**

Around 8000nm distance is displayed 

**References**

**Additional context**

Will provide a better description once I’m on my pc again. 
Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by kiokio0987** [comment]
I actually flew it and I think the problem is the same as (#2962).
Here is a VFR map with the issue.
![WS000022](https://user-images.githubusercontent.com/75520968/104832842-9a9b1600-58d7-11eb-9403-3d160fe8af3a.JPG)
![WS000021](https://user-images.githubusercontent.com/75520968/104832847-a090f700-58d7-11eb-86c6-da9fac70ffed.JPG)

**Comment by Saschl** [comment]
You’re right mine’s probably a duplicate of  #2962. I’ll close this one and add comments on the other report. Thanks!
