### ISSUE TITLE
FMA no SINGLE/DUAL for CAT 1 & CAT 2

### ISSUE THREAD

**Issue by PCGamesF1Tech** [flybywiresim/a32nx#312]
~~The FMA for CAT 1 and CAT 2 approaches is wrong, it shouldn't show "SINGLE/DUAL". 
The SINGLE/DUAL concept only applies to CAT 3 approaches and aircraft behaviour and pilots reaction in case of failures during different stages of the approach.~~

EDIT:
The FMA combination of CAT 1/CAT 2 with SINGLE/DUAL is wrong. 
It only shows when CAT 3 is announced as well

**Comment by Curtis-VL** [comment]
Thanks, will correct!

**Comment by Curtis-VL** [comment]
Ah, actually, I already fixed this! #289

**Comment by JackZ974** [comment]
Sorry, but I disagree. 

SINGLE/DUAL MODES are merely an information about the Current Autopilot and airplane approach and landing capabilities, considering the fact that some systems have to be doubled and available for AUTOLAND (Fail Operational). 

The plane doesn't really know if we are performing a CAT 1, 2 or 3A approach. The FMA just say: I can do up to CAT 3DUAL since all the systems required for this have been tested and are OK. Each FMGC computes it's own landing capabilities, and the FMA will display either CAT 1, CAT 2, CAT 3 SINGLE (Fail passive) or CAT 3 DUAL (Fail operational) depending on the results of these tests

 One can perform in CAT 1 weather conditions an AUTOLAND for practice, as long as certain criteriaes are met and the ATC is ok  with that, and of course CAT 3 DUAL is displayed on the FMA..

**Comment by PCGamesF1Tech** [comment]
All correct! 👍🏻
The FMA just doesn't show SINGLE/DUAL if there's only CAT 1 or CAT 2 announced on FMA (for example when flying with APPR armed, AP 1+2 on but still about more than ~5000ft above the ground)

**Comment by JackZ974** [comment]
Corrected on PR#330 (hopefully)

**Comment by JackZ974** [comment]
Yep SINGLE/DUAL is only for CAT 3. 
In PR#330, I have modified the display to reflect this, depending on the number of A/P used and if the A/THR is engaged.
Do you have any source about this 5000ft threshold?

**Comment by PCGamesF1Tech** [comment]
Great! And sorry for the confusion 🙄 (wrote "approaches" , really meant "indications" ...)

**Comment by JackZ974** [comment]
> 
> 
> Great! And sorry for the confusion 🙄 (wrote "approaches" , really meant "indications" ...)
> 
> And the other way around:
> When taking over manually during approach on final the FMA reverts to "CAT 1"
> (some colleagues announce it, some don't)

yeah, should be working as is, since i linked the CAT1 to no PA at all in PR#330

**Comment by PCGamesF1Tech** [comment]
Cool! I'm so excited to give it a try (this whole project at all)

**Comment by Curtis-VL** [comment]
The logic in that pull request isn't correct I'm afraid!

I was discussing it earlier with some pilots in the Discord and reviewing their documents.
As @JackZ974 said, it's based on the systems capabilities. Currently, as there's no failures, you'll always be in CAT 3, or CAT 1.
CAT 1 would be no autopilot, CAT 3 is the only one capable of 'DUAL', as CAT2 doesn't require both to be enabled.

Please join our Discord to discuss this further so we can figure it out with some pilots. 👍

**Comment by blitzcaster** [comment]
@Curtis-VL does the sim differentiate between CAT 1, 2 and 3? Because I just landed at local airport which only have CAT 1 IIRC, but it says CAT 3 during approach. Or is it only supported on the latest dev branch?

**Comment by PCGamesF1Tech** [comment]
The real A/C will always show CAT 3 DUAL if everything is working, on any ILS beam, there is no "detector" for what kind of ILS you are flying. 
It's the aircraft telling us what it is able to do. 

CAT2 & 3 just need more equipment on the ground (stby ILS transmitter, ILS accuracy checks, backup power, runway lighting, ... ) and larger areas around the runway free of aircraft and ground equipment (metal) that could distort the ILS signals.
But that's an airport concern, if they manage this they eventually will get an upgrade to higher categories after some time (if needed and authorized).
