### ISSUE TITLE
[BUG] MCDU did not show/use actual Navigraph cycle 2101

### ISSUE THREAD

**Issue by FGrabi** [flybywiresim/a32nx#3233]
**Mod Version**

{
  "built": "2021-01-28T03:45:39+00:00",
  "ref": "",
  "sha": "",
  "actor": "ZigTag <17077422+ZigTag@users.noreply.github.com>",
  "event_name": "manual"
}

**Describe the bug**

Loaded the actual Navigraph AIRAC cycle 2101 with "NAVIGRAPH" tool into the community folder. Starting a flight, checked in MCDU the version. Showed and used (wrong STAR approach VOVLU2A at SKBQ - unknown waypoints D210F and CF05) wrong cycle 2014. 

**To Reproduce**

1. Load actual 2102 into community folder
2. Start a flight at any airport you like
3. Check in MCDU the cycle

**Expected behavior**

Fresh loaded cycle should be shown and loaded

**Actual behavior**

see above

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes
Is this a problem in the vanilla unmodded game?
Don't know, did not check

Discord username (if different from GitHub):

**Comment by Saschl** [comment]
The Airac cycle is currently hardcoded by Asobo. Afaik it cannot be fixed (until Asobo brings an update) as there's no possibility to get this information inside the sim.

**Comment by DFWSupertrooper** [comment]
> The Airac cycle is currently hardcoded by Asobo. Afaik it cannot be fixed (until Asobo brings an update) as there's no possibility to get this information inside the sim.

Out of curiosity, why do we have the Navigraph NavData Beta program update the sim every month if the sim isn't using the newest data?  Where is it going then?  Not doubting you...just curious if it's not actually updating the sim's navigation data.  Is the sim taking in new data for planning but simply not coding the correct AIRAC number each update??  

Maybe that's why there's a monthly "small nav update" where they catch it up later??

**Comment by ThatRedMelon** [comment]
Navigraph updates the actual navdata of the sim, so all your routing etc will be navigraph. The issue is that there's no way to update the navdata date displayed on the data page of the MCDU, so while the navdata updates, the date doesn't. It's only updated when Asobo update the default data in the sim.

**Comment by Saschl** [comment]
You were right with the second assumption. Maybe I was not clear enough :D So the data is being used, it's just this string that is only updated when MS drops their navdata update.

**Comment by Awemeter** [comment]
> You were right with the second assumption. Maybe I was not clear enough :D So the data is being used, it's just this string that is only updated when MS drops their navdata update.

Afirmitve

**Comment by Awemeter** [comment]
The issue has been solved since the latest msfs update. Just update to rev 3 2101 and it should work

**Comment by tracernz** [comment]
> 
> 
> The issue has been solved since the latest msfs update. Just update to rev 3 2101 and it should work

Confirm it works with the new cycle (2102).
![image](https://user-images.githubusercontent.com/9995998/109242741-8d5f3880-7840-11eb-9231-939aac16cd44.png)

**Comment by FGrabi** [comment]
Yes, confirm that it works.
I believe, that this is not related to the last MSFS update. Navigraph changed the data format since 2101 rev 3. Found this in the "release notes" from Navigraph:
We are still working actively with this project. The following revisions to the data format have been released since AIRAC 2101:
•	Revision 3
o	AIRAC date (from-to) on the FMC ident pages are now set correctly.
o	Minor frequency & boundary improvements.
o	Route altitude minima set to unlimited for UNKN type.
