### ISSUE TITLE
[BUG] Buttons on Autopilot bar so HDG, SPD, and ALT not turning midflight

### ISSUE THREAD

**Issue by rh5588** [flybywiresim/a32nx#3423]
**Mod Version**
Latest Dev Version

**Describe the bug**
Midflight the buttons and knobs on the autopilot bar would not turn so I can't do any vectored turns by ATC on approach for example

**To Reproduce**
1. Get up to cruise 
2. Start your descent 
3. Try and turn using autopilot 

**Expected behavior**
Expected the aircraft to turn 

**Actual behavior**
The aircraft stayed on current heading and only turned when I overtook the aircraft by manually turning the aircraft myself. 

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): Rhys#5777

**Comment by mreza1st** [comment]
I confirm that! The plane doesn't follow the MCDU flight path and the other functions don't work mid flight to correct it. Unfortunately the AP and MCDU have deteriorated significantly over the past few week! Although the frame rate has improved a lot and stutters are pretty much gone which is nice. But without a good MCDU and AP that follows the flight path, it's not a good system! Don't claim this is related to dead zone, etc. because it's not. It's a fairly recent (2-3 weeks) issue.

**Comment by Benjozork** [comment]
Please keep the discussion on topic about additional information and leave rants / complaints out of the comments section. IF you do not want unexpected problems, do not use a **DEVELOPMENT** version.

**Comment by lukecologne** [comment]
Is this still an issue?

**Comment by rh5588** [comment]
No
