### ISSUE TITLE
[REQUEST] Chronometer panel working RUN and GPS switches

### ISSUE THREAD

**Issue by GlitchedYT** [flybywiresim/a32nx#3465]
**Is your feature request related to a problem? Please describe.**

Negative

**Describe the feature you'd like to see implemented**

Refer to title of request

**References**

In Sim:
![Screenshot 2021-02-10 160037](https://user-images.githubusercontent.com/56449691/107574844-21809d00-6bbd-11eb-9f3c-7725586348cb.png)
IRL
https://www.youtube.com/watch?v=xczl6YiLRl0&ab_channel=CHOXON2CHOXOFF

**Additional context**
 N/A

Discord username (if different from GitHub): Glitched

**Comment by kiokio0987** [comment]
The description of Elapsed Time (ET) has already been requested in #3238 .
In this post, please write a reference for the GPS switch.
The FCOM is shown below. I can't explain it because I don't know the details.
![WS000024](https://user-images.githubusercontent.com/75520968/107778309-488aca80-6d87-11eb-9d25-cf5af311fe9b.JPG)
![WS000025](https://user-images.githubusercontent.com/75520968/107778316-4aed2480-6d87-11eb-9cee-2ef3aad7ea5b.JPG)
![WS000026](https://user-images.githubusercontent.com/75520968/107778320-4c1e5180-6d87-11eb-8867-9d312f9d5fde.JPG)
![WS000027](https://user-images.githubusercontent.com/75520968/107778327-4cb6e800-6d87-11eb-85d0-7dbfb0f85de9.JPG)

**Comment by BlueberryKing** [comment]
This has been addressed in https://github.com/flybywiresim/a32nx/pull/3794.
