### ISSUE TITLE
[BUG] Plane Not Filling in ILS frequency in RAD/NAV page When spawned in on ILS approach

### ISSUE THREAD

**Issue by Darlack6** [flybywiresim/a32nx#3696]
**Mod Version**
{
  "built": "2021-02-23T05:59:34+00:00",
  "ref": "fbw",
  "sha": "fa3e284a9e4a0aa07c0582ca5e2a88a9689b1f9f",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
When spawning in on approach, the plane does not want to follow the ILS and instead follows NAV

**To Reproduce**
1. Spawn in on approach at any airport with the ILS approach (in the main menu)
2. Turn on AP, and Approach mode, check PFD and see if it catches the LOC and GS

**Expected behavior**

The plane should fly the ILS when spawned in on the ILS

**Actual behavior**
Spawn in on approach and let the AP fly the ILS without having to reprogram the MCDU.

**References**
A video of me spawning in at CYYZ and the ILS approach to 33R

https://www.youtube.com/watch?v=PyOS1WpUFJY

Seems as though the ILS frequency isn't inputed: 

![image](https://user-images.githubusercontent.com/78220630/108930131-535d1f00-7613-11eb-926c-8315de46dfd5.png)

**Additional context**

Was this working before/when did the issue start occurring?
The issue started happening 2 weeks ago

Is this a problem in the vanilla unmodded game?

No

Discord username: Darlack#3281

**Comment by Awemeter** [comment]
You have to enter the ils freq

**Comment by dc1ps2** [comment]
I also found that after loading the SimBrief flight plan through the AOC menu in the past, after setting the approach method, the ILS frequency will be automatically brought in, but why is it not automatically brought in after the latest version update, must self Enter ILS frequency? I think this is what the questioner wants to express!

**Comment by Darlack6** [comment]
> You have to enter the ils freq

When you spawn in on the ILS approach before, you never had to fill it in, it was automatically set. It seems odd that you would have to enter the ILS frequency every single time.

**Comment by tracernz** [comment]
Have you tried with https://github.com/flybywiresim/a32nx/pull/3599 (merged to dev 4 days ago)?

**Comment by Darlack6** [comment]
> Have you tried with #3599 (merged to dev 4 days ago)?

Just downloaded the PR for #3599, it still doesn't autofill the ILS frequency 

**Media**

![image](https://user-images.githubusercontent.com/78220630/109058300-d7191900-76b0-11eb-91ff-d699d3f59df7.png)

**Comment by AirbusA320Pro** [comment]
If I'm honest, it looks like the aircraft is behaving correctly in the "real world" scenario. I can't comment about previous A32NX versions, but if there's no approach selected in the FMGC, the LS pushbuttons aren't selected, then it will revert to basic modes. When you engage the autothrust and AP, the aircraft is going to target the FCU selected ALT of 5000'.

**Comment by Darlack6** [comment]
> If I'm honest, it looks like the aircraft is behaving correctly in the "real world" scenario. I can't comment about previous A32NX versions, but if there's no approach selected in the FMGC, the LS pushbuttons aren't selected, then it will revert to basic modes. When you engage the autothrust and AP, the aircraft is going to target the FCU selected ALT of 5000'.

Normally I would completely agree with you, the only thing is the LS button won't affect the AP following the GS and LOC. The problem is when you spawn in on a ILS approach (Not a full flight) it should have the LS frequency dialed in (as it's a ILS approach), and once you select APP mode it should follow the ILS. This used to work in previous versions of A32NX, and this is the only way I can "practice" landings

**Comment by FGrabi** [comment]
In my opinion, this has nothing todo with the Simbrief import. The ILS frequenzies are related to the ILS Approach procedure for the specified runway. So it must be "linked" with Departure Data that one need to enter, after the simbrief import created a flightplan (from Airport to Airport without any SID, STAR or Approach procedures). We, as pilots, need to add these informations after we did the final plan - maybe in Navigraph. So I believe - and please correct this if you know better - that the ILS freq is linked inside the Navigraph data. Just today the new AIRAC cycle 2102 is released and need to be loaded (if you want to fly on actual data) into SIMbrief and MSFS2020. I cheked it with the actaul Dev FBW Mod and with old and new AIRAC data on a flight to EDDH (Rwy15). Loaded via simbrief the FP, entered the ILS15 Approach and checked the RAD/NAV page. ILS frequenzie was entered. BUT: Sometimes I found approach procedures (don't know which airports anymore), where one can choose the correct procedure (checked Charts against the waypoints and track in MSFS, everything like written/painted in the charts) but in RAD/NAV no frequenzie was added. So I need to add this Information from the chart by hand. This happens sometimes. Don't know if this a failure (missing information) in the AIRAC data or within the ASOBO Modell and the "loading" of the AIRAC from the community folder?
Best is you follow the A32X Checklist (available on flightsim.to). There you'll found in the "Cockpit Preparation" Checklist the following points:
MCDU Setup:
- ATSU Init Request
- ATSU Perf&Weight Load
- INIT (Page 1)
**- F-Plan
- RAD/NAV**
- INIT (Page 2)
- PERF

and check this with the OFP from simbrief and the SID, STAR, Approach charts. I always need to do this, because most of the time I fligh on IVAO and the ATC controllers sometimes have their own plans (because of traffic, weather or other).

**Comment by Darlack6** [comment]
> In my opinion, this has nothing todo with the Simbrief import. The ILS frequenzies are related to the ILS Approach procedure for the specified runway. So it must be "linked" with Departure Data that one need to enter, after the simbrief import created a flightplan (from Airport to Airport without any SID, STAR or Approach procedures). We, as pilots, need to add these informations after we did the final plan - maybe in Navigraph. So I believe - and please correct this if you know better - that the ILS freq is linked inside the Navigraph data. Just today the new AIRAC cycle 2102 is released and need to be loaded (if you want to fly on actual data) into SIMbrief and MSFS2020. I cheked it with the actaul Dev FBW Mod and with old and new AIRAC data on a flight to EDDH (Rwy15). Loaded via simbrief the FP, entered the ILS15 Approach and checked the RAD/NAV page. ILS frequenzie was entered. BUT: Sometimes I found approach procedures (don't know which airports anymore), where one can choose the correct procedure (checked Charts against the waypoints and track in MSFS, everything like written/painted in the charts) but in RAD/NAV no frequenzie was added. So I need to add this Information from the chart by hand. This happens sometimes. Don't know if this a failure (missing information) in the AIRAC data or within the ASOBO Modell and the "loading" of the AIRAC from the community folder?
> Best is you follow the A32X Checklist (available on flightsim.to). There you'll found in the "Cockpit Preparation" Checklist the following points:
> MCDU Setup:
> 
> * ATSU Init Request
> * ATSU Perf&Weight Load
> * INIT (Page 1)
>   **- F-Plan
> * RAD/NAV**
> * INIT (Page 2)
> * PERF
> 
> and check this with the OFP from simbrief and the SID, STAR, Approach charts. I always need to do this, because most of the time I fligh on IVAO and the ATC controllers sometimes have their own plans (because of traffic, weather or other).

So sorry for the late reply, even after updating to AIRAC 2102 (even used navigraph's airac loader for msfs) the ILS frequency still did not auto-filled. I've tried basically everything now, and still can't get it to work.

**Comment by BalaBalaYi** [comment]
Same problems with dev(e34ae7d). I'm sure this is used to work in v0.5.3(stable).
