### ISSUE TITLE
FD problem after takeoff on some airports

### ISSUE THREAD

**Issue by kutak11** [flybywiresim/a32nx#4104]
**Mod Version**

545c472 (custom)

**Describe the bug**

There is disagree between FD and planned route after takeoff (SID). 

**To Reproduce**

1.  Load at LKPR rwy24 or rwy06 and select SID (VOZ2A or VOZ2E)
2. Perform normal take off and look on FD.
3.

**Expected behavior**

To fly SID correctly how it is loaded on MCDU and displayed on ND.

**Actual behavior**

When NAV mode is activated lateral part of FD forced me to turn from rwy centerline to align different inbound course to the first waypoint of SID than it is displayed on ND which is correct. 
It seems it creates "starting waypoint" as airport refrence point not the rwy or present position when NAV is activated after take off.  
I can only prevent this bug by flying manualy until reach first waypoint or select Direct on DCT page to the first waypoint when on runway.

**References**

![FD bug](https://user-images.githubusercontent.com/72166387/112385133-89afbc00-8cef-11eb-9b94-47ecd263466f.jpg)

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by kgaviation** [comment]
I think I may be experiencing a similar issue myself.

Are you experiencing an issue where the aircraft banks left and right as soon as you engage the AP after takeoff? In other words, it doesn't just continue flying straight and smoothly transition. Even if the FD is centered when I engage the AP, it just banks left and right, back and forth to correct itself. Idk if this could be related, but I've been having that issue ever since the sim update a couple weeks ago. Something's kind of buggy with the AP it seems. It's not a deadzone issue.

But, IIRC, one airport I departed from recently had the FD set to the side like you have a screenshot of when it should been centered after flying runway heading. I can't remember what airport this happened at though, but it caused the AP to bank harshly after takeoff to follow the line.

**Comment by kutak11** [comment]
yes I experience two different issues with FD. One is that you describe.
1) When I follow FD best I can and after switching AP sometimes there is sharp turn left/right then slowly returning back to original route
2) The second I posted here, SID is acutally on side after departure.. It looks it starts as airport reference point.. strange is there is discrepancy with route displayed on ND. It helps only put DCT in MCDU before take off. 
It is problem of MSFS probably, CRJ from Aerosoft is OK with this particular AP issue.

**Comment by kutak11** [comment]
This is how it looks with community folder empty... veeery strange

![Microsoft Flight Simulator Screenshot 2021 03 26 - 19 20 39 35](https://user-images.githubusercontent.com/72166387/112677111-9821e300-8e69-11eb-8d55-ab9387045f78.png)

**Comment by kgaviation** [comment]
> 1. When I follow FD best I can and after switching AP sometimes there is sharp turn left/right then slowly returning back to original route

This is my problem exactly. Everytime I engage the AP, even if my FD is perfectly centered, it will immediately enter a sharp left or right bank, then it will bank the opposite direction to correct itself and as you said slowly return to flying the correct route.

Apparently the AP is buggy and there's nothing they can do to fix it. Ya gotta love it don't you.

**Comment by lukecologne** [comment]
I'm going to close this as the version used is pretty out of date. Not sure if this has been resolved, if it is still an issue in the newest release, please open a new issue.
