### ISSUE TITLE
Custom AP constantly and violently pitches up and down

### ISSUE THREAD

**Issue by UNSCJohn-117** [flybywiresim/a32nx#4165]
**Mod Version**
Latest Experimental (as of 7:30PM CDT, 3/27/21)

**Describe the bug**

AP oscillates up and down violently starting at 16,000ft

**To Reproduce**

1. Start a flight from the gate (using SimBrief integration)
2. Takeoff (started at KBOS on the HYLND5 SID)
3. Wait until about 16,000ft

On a related note, you can disconnect and reconnect AP; problem goes away upon disconnect, and comes back on reconnect.

**Expected behavior**

AP should not induce heavy motion sickness and continue climbing steadily to CRZ

**Actual behavior**

AP constantly and violently bounces up and down

**References**

https://youtu.be/YTr877Villk (apologies for low framerate, my specs are terrible)

**Additional context**

Was this working before/when did the issue start occurring?
This was not an issue on the previous iteration of the experimental build (FBW only, no custom AP), it only appeared after the latest update with the custom AP

Is this a problem in the vanilla unmodded game?
Unsure

Discord username (if different from GitHub): Discord: John-117#1457

**Comment by kgaviation** [comment]
I could be wrong, but I believe that the custom/experimental version is constantly being updated and improved. I posted a bug report earlier regarding the new custom AP transitioning to waypoints along the FP incorrectly. My issue is not the same as yours that you describe, but it is similar in nature, in regards to the AP. In my case, the aircraft would bank in the wrong direction when reaching the next waypoint. If the FP is to turn right, the aircraft will initially bank left (in the wrong direction) for a few seconds and then bank back in the correct direction. I noticed it has a tendency to bank back and forth until it eventually flies straight and level with the FP, until the next waypoint. The AP should obviously not behave this way and I believe it is a known issue with the LNAV system.

As for your issue, possibly there's also an issue with the VNAV system? I'm sure they will look into your issue like they are doing mine.

While the new custom version is really nice and realistic otherwise, this is why I've always avoided the custom version of the mod because of the many initial bugs, whereas the stable version is essentially bug-tested and bug-free. Once the bugs get worked out though, and hopefully soon, the new custom version is going to be great though. Guess we just have to be patient.

**Comment by aguther** [comment]
(apologies for low framerate, my specs are terrible)

There you have it!

**Comment by aguther** [comment]
> I could be wrong, but I believe that the custom/experimental version is constantly being updated and improved. I posted a bug report earlier regarding the new custom AP transitioning to waypoints along the FP incorrectly. My issue is not the same as yours that you describe, but it is similar in nature, in regards to the AP. In my case, the aircraft would bank in the wrong direction when reaching the next waypoint. If the FP is to turn right, the aircraft will initially bank left (in the wrong direction) for a few seconds and then bank back in the correct direction. I noticed it has a tendency to bank back and forth until it eventually flies straight and level with the FP, until the next waypoint. The AP should obviously not behave this way and I believe it is a known issue with the LNAV system.
> 
> As for your issue, possibly there's also an issue with the VNAV system? I'm sure they will look into your issue like they are doing mine.
> 
> While the new custom version is really nice and realistic otherwise, this is why I've always avoided the custom version of the mod because of the many initial bugs, whereas the stable version is essentially bug-tested and bug-free. Once the bugs get worked out though, and hopefully soon, the new custom version is going to be great though. Guess we just have to be patient.

Well it's like sh*t in sh*it out. It behaves this way due to the input it gets. I changed now the input I use and it should be much better now. I invite you to try again.

Overall we are aware of that and that's the reason why a custom FPM, custom LNAV and VNAV is being worked on.

Given the fact how much pain the default AP has created I'm impressed to see how people almost only see the issues right now. I really think it's already an improvement in so many areas, and that was the reason to not longer hold it back. It's amazing to see how a lot more flaws with the default AP seem to be acceptable.

**Comment by UNSCJohn-117** [comment]
I’ll try again soon with a newer version (and if the problem persists I’ll downgrade to the Dev branch until I can upgrade).

Unfortunately recent storms knocked my internet out, so I’m waiting on my ISP to fix it, so it’ll be a few days before I can try again.

**Comment by kgaviation** [comment]
I just completed a 5 hour flight to Hawaii with the latest version and the AP was great. It was honestly a flawless flight. It banked the correct direction when reaching waypoints and flew really smoothly with no violent pitching or banking. If I were you, it may just be a case of downloading a more updated version of the mod. This solved my problem.

**Comment by Spartan3001961** [comment]
My last 3 flights have been the same. The flights were flawless, and then about half way down the GS, it started a violent pitch up and down. It did settle down in the end, and landed in Autoland mode perfectly. I was using the Autoland feature at Oslo 01L.

I have downloaded and installed the latest version Experimental version tonight and did the same flight, and it happened again.
I create my plans via SimBrief and everything is set up as its supposed to be in the MCDU. Out of the 4 flights now, with 2 of them, I get a brief stall warning which then cancels itself as the plane settles down.

The one thing I have noticed is that it happens when the RA hits around the 1000ft. I'm going to try another another flight tomorrow night but without the Autoland and see what happens.

**Comment by UNSCJohn-117** [comment]
Welp, between getting out internet  back, replacing a fried router, starting a new job, and converting old liveries to the new format, I have successfully passed 16,000ft without the induced motion sickness.

I did have an interesting glitch in the FPL on the same SID as last with the plane going off the route and making a huge loop right after passing HEARR (a DCT got me back on track but still odd nonetheless).

But as far as this issue is concerned, I believe it's all good (I'll have to see what APP does before I close for good).

Tested today, 4/10/2021 @ ~4:00PM CDT, latest experimental build
