### ISSUE TITLE
FBW cannot/will not hold cruise altitude

### ISSUE THREAD

**Issue by jakecminihan** [flybywiresim/a32nx#4273]
**Mod Version**

The latest stable version from the installer - v0.5.4

**Describe the bug**

LNAV and VNAV work perfectly from takeoff and throughout the climb. Upon reaching the cruise altitude, it just goes absolutely mad - it will bounce between +- 6000ft of the target altitude doing a good few thousand FPM.

**To Reproduce**

1. I'm not sure - it's happened both times, and I've not done anything weird. I have attached both .pln files though
2. Upon reaching ~ cruise altitude, the aircraft will massively exceed the target altitude and pitch hard down (-5000fpm) to correct and then overshoot again (the process continues) or it will begin to S-turn laterally

**Expected behaviour**

The aircraft should enter CRZ mode and cruise along happily without spilling the virtual coffee

**Actual behaviour**

The aircraft overshot the target FL, pitched hard down to compensate, overshot again, pitched up in a continuous loop, while also ignoring the LNAV path and just going in circles

**References**

Screenshot:
![Screenshot_111](https://user-images.githubusercontent.com/62210689/113512306-f3379200-955b-11eb-8f8d-56f879469934.jpg)
Video:
(I'll see if I can try and video this)
Flightplans used:
[A32NX FPs.zip](https://github.com/flybywiresim/a32nx/files/6254756/A32NX.FPs.zip)

**Additional context**

Was this working before/when did the issue start occurring?
It's always been like this - I've tried 2 flights and had the same problem each time.

Is this a problem in the vanilla unmodded game?
Not sure what this means - I've not used the autopilot on any of the vanilla aircraft so couldn't comment

Discord username (if different from GitHub): 10pastnein#6436

**Comment by Valastiri** [comment]
To solve the issue of going in circles: 
![image](https://user-images.githubusercontent.com/1619968/113512417-23505680-9597-11eb-90f0-7757679b1181.png)

Additionally may also solve the cruize alitude issue. 

The reasoning is due to micro inputs from your controller of choice not disconnecting the AP. 

Also see -> https://docs.flybywiresim.com/start/reported-issues/

**Comment by jakecminihan** [comment]
> To solve the issue of going in circles:
> ![image](https://user-images.githubusercontent.com/1619968/113512417-23505680-9597-11eb-90f0-7757679b1181.png)
> 
> Additionally may also solve the cruize altitude issue.
> 
> The reasoning is due to micro inputs from your controller of choice not disconnecting the AP.
> 
> Also see -> https://docs.flybywiresim.com/start/reported-issues/

Thank you for responding! I'd already tried that and it didn't seem to make a difference, I've moved it up to 30% and will try again...

**Comment by jakecminihan** [comment]
Okay, I might have found the issue. The previous occurrences I believe happened when inserting a direct to/tinkering with the flight plan. I recreated the flight with a 30% dead zone and had no issue for ~ 3 hours. Near the end of the flight, I inserted a direct to and this sent it absolutely haywire; the aircraft trimmed extreme (~ 12 degrees up) and climbed 8,000 feet dropping to ~ 90kts; from what I'm aware, the expected response of the A320 in the instance of a stall is the dropping of the nose and application of TOGA. I've attached a video and a picture; the flightplan I was using was the LOWWBIKF.pln and I was about halfway between RATSU and some lat/long custom waypoint; I asked for a direct to ASRUN and this created the issue. Given the flight was successful up until this point, I would say it's that. I'll do another trial flight and try and capture footage as I insert a direct to.

If there are any logs that I can provide or other sources of data, please do let me know.

![Screenshot_1](https://user-images.githubusercontent.com/62210689/113521663-d5d1ea80-9592-11eb-9cdf-9635d105e26a.jpg)
_This is a screenshot taken in the first few seconds after the Direct To command was issued_

Video link: https://vimeo.com/532940240
_After this happened I disconnected the autopilot and levelled out the aircraft; after relinquishing control, this is what happened. Trim reached 13.5 degrees up at an altitude of 42,000 feet and a speed of 90kts before the aircraft appears to stall. The 5,500 ft climb was made in some 40 seconds, a climb rate of about 8000 fpm._

**Comment by jakecminihan** [comment]
Update: it appears that this issue is cased even just by clicking on the direct to page

**Comment by MisterChocker** [comment]
AP was disengaged during the entire length of your video.

> Update: it appears that this issue is caused even just by clicking on the direct to page

Just by clicking the DIRTO page, nothing to the AP should happen. I find it very unlikely that this related in any way to the DIR TO page itself.

**Comment by TwattyBollox** [comment]
I would also be aware of the NUM 5 key ... if you have pressed any of the NUM keys, 1-9 can move the cockpit stick slightly.
That stick is NOT auto centred, so it will stay pressed until your jockstick is moved, or the NUM 5 key is pressed (recentre stick) --- it is also difficult to se if it HAS been moved.
It has caught me out a few times when I was in external camera view, then switched back to find it was banking over one way or the other from the AP line.
Also trim ... if you have a trim set on the joystick/throttle, when the AP disconnects, that could take over at the setting on the jsk/thr and in my case, it definitely over-rides the AP trim (as do all inputs from my controllers while AP is engaged).

I am going to use SPD=SPD/MACH, FD=Flight Director, THR=Throttle, CLB=climb, FLP=Flaps, WP=waypoint

In the second screenie, you have a crosswind of 132kts !!
You appear to have two green AP lines coming from your aircraft; one to ASRUN and one DIR ?
In your case, ASRUN is the WP enabled, as shown in the right screen ASRUN 307° 234.5 NM 13:52 (est arr time)
You appear to have FLP set to 1?
FD appears to be indicating a descent to FL340 from 346 is programmed
It shows THR is in CLB?
**But** SPD is in managed mode, and reducing to 230kts?
One reason I suggest is because in managed SPD mode, setting FLP1 will cause the aircraft to slow to 230kts
Similarly, there appears to be some confusion of the aircraft heading.
The yellow (where it is pointing) = 317.5°?
The green (where it is heading) = 311.5°?
The WP heading seems to require 307°?
At the same time the aircraft is in a bank to the left, which implies to me that there is a great deal of right rudder being applied.

Is any of that correct?
I mean a crosswind of 132kts, from 322° could explain a lot of that, but not the FLP1 setting.
Are these different version of A32NX? THe first seems to be using the green ATL blue CLB in the FD, while the second appears to be using the boxed ALT*, which could suggest the throllte was not in CLB mode.
Similarly, the first has the green text THR CLB while the second MACH

I would delete the A32NX folder completely, and use the DEV version from a week ago, before the fork into a new aircraft if you want to use a livery.
Or, the new dev one and the new aircraft if you don't care about liveries.

That stable release is a bit susceptible to strangeness. You can also use the MFD in CTRL page mode, so you can see where the ailerons/rudder/elevators/flaps are set. That way, if something strange IS going on, you have a good chance of seeing what it is.
This is why I changed to the dev version: https://youtu.be/ZeisIFn79D8?t=2212 or https://youtu.be/yE-h1x-FsEM?t=1481

**Comment by MisterChocker** [comment]
> Similarly, there appears to be some confusion of the aircraft heading.

The Green indicates the track (which is affected by wind)
The Yellow indicates the heading.

You can clearly see that the FD is requesting pitch down, but an input is making a pitch up input. (the AP does what the FD shows)

**Comment by TwattyBollox** [comment]
>"The Yellow indicates the heading."
Yeah, that's what I wrote above, but in a slightly dumbed down way, using "pointing" and "heading (to)", sorry if I confused you :¬)

Once again, the important part is NOT that, it is that the drift which the aircraft took did not line up the track to the WP bearing of 307° (which implies something other than the AP is fiddling with the controls)

**Comment by jakecminihan** [comment]
Okay, I believe I have found the problem - I was using Right Shift + Up/Down arrow keys to translate up and down in the cockpit which MSFS reads as the NUM keys. Clearing the NUM key aileron/elevator assignments has solved the issue, and explains why there was a continued input even though I wasn't knowingly touching the controls.

The second screenshot showed a weird direct to line - this happens occasionally when inserting a DIR command but doesn't seem to affect the aircraft.

**Comment by TwattyBollox** [comment]
> Okay, I believe I have found the problem

Glad you found it in the end :¬)

**Comment by jakecminihan** [comment]
> > Okay, I believe I have found the problem
> 
> Glad you found it in the end :¬)

Thank you, and thank you to everyone else for helping! Also, huge thanks to the FBW team for an incredible aircraft! I'll close this now.
