### ISSUE TITLE
AUTO BRK LO hardly works

### ISSUE THREAD

**Issue by SIXOSN** [flybywiresim/a32nx#4290]
**Mod Version**

Experimental 7682da2

**Describe the bug**

The deceleration effect of LO AUTO BRK is very insignificant

**To Reproduce**

1.Landing on the runway normally(REV FULL, GND SPLRS ARMED, FLAP FULL, LO AUTO BRK)
2.
3.

**Expected behavior**

Stop in a reasonable area

**Actual behavior**

Almost used up the KDEN 35R runway before stopping

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Only this version has this problem
Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):SIXONS

**Comment by MisterChocker** [comment]
Following your description, this sounds like the autobrake did not engage at all, did you checked the autobrake button to display `decel`?

**Comment by SIXOSN** [comment]
> Following your description, this sounds like the autobrake did not engage at all, did you checked the autobrake button to display `decel`?

Yes, I am 100% sure that I was AUTO BRK in LO at the time

**Comment by MisterChocker** [comment]
Did the button indicated (in green) decel?

**Comment by SIXOSN** [comment]
> Did the button indicated (in green) decel? (other than (in blue) on.

Sorry, I didn't take a serious look at the time to see if the green light was on, but what I can confirm is that I saw the blue light on the LO during the approach. But shouldn't ATOU BRK automatically brake and slow down when it is ON when it is grounded?

**Comment by SIXOSN** [comment]
> Did the button indicated (in green) decel? (other than (in blue) on.

Sorry, I didn't take a serious look at the time to see if the green light was on, but what I can confirm is that I saw the blue light on the LO during the approach. But shouldn't AUTO BRK automatically brake and slow down when it is ON when it is grounded?

**Comment by MisterChocker** [comment]
Yes they should but sadly this currently is not always working and we need to take a closer look and improve things as we go on.

**Comment by cchard360** [comment]
I did a flight into KBUF and it felt like the Auto Brk Lo was not working due to very little deceleration even with reverser. I didn't see DECEL lights up on PFD or brake switch but I didn't check anything else before applying manual brakes so I don't know if it was just lower than I expected at the Lo setting.

I just did a test flight into KDEN and recorded it: https://youtu.be/OStLJCcBFJA  With Auto Brk Lo armed on touchdown the brakes apply and slow the plane (did a little reverser but mostly in idle the plane slowed to a stop on its own and brakes got hot) but the DECEL indications on the PFD and brake switches never turn on. If needed I can test some other configs. 

Conclusion so far: DECEL indicators not working, Auto Brk Lo working.

{
  "built": "2021-04-25T21:48:00+00:00",
  "ref": "master",
  "sha": "27b2defa3b8fdaea677a653b961105892c6f20b6",
  "actor": "Benjozork",
  "event_name": "manual"
}

**Comment by cchard360** [comment]
Another recording: **https://www.youtube.com/watch?v=SficZkbwiwc**  Landing at KSAW with Auto Brk Med, no reverser. Brakes worked on touchdown and the DECEL light on button turned on but then flickered a few times before turning off. DECEL never appeared under the speed tape.

**Comment by MisterChocker** [comment]
> DECEL never appeared under the speed tape.

Because there are no autobrakes on the FMA in that version. As you can the FMA doesn't indicate `BRK MED` and therefore also does not display decel.

**Comment by mightywarriorr** [comment]
> I started using MSFS 2020 recently, so i only got The A32NX a few days ago. I have noticed that the autobrake doesnt work at all. I arm it and i can confirm that on the FMA, but upon landing with weight on both wheels and ground spoilers deployed the Decel light never lights up. Is that a known issue or just a problem with my install?

I was using the old stable version when i said the autobrakes werent working, and they really werent working back then because if i didnt manually brake the aircraft it wouldnt be able to stop on 3 Km runway. Nowadays i am using the developtment version and the autobrakes do work but the decel light does not light up as cchard360 pointed out. Ive only used Autobreak Low. I will try Medium to check if Decel Lights up.

**Comment by cchard360** [comment]
> > DECEL never appeared under the speed tape.
> 
> Because there are no autobrakes on the FMA in that version. As you can the FMA doesn't indicate `BRK MED` and therefore also does not display decel.

Ah yes. I see that now. Ty. 

Let me know if any other recordings of the switch light behavior would help.

**Comment by N1EL** [comment]
Could the sim be really sensitve to your brake pedals? so although you are not commanding or pushing the brake on your rudder pedals, even using a bit of rudder after landing may trigger it to deactive the autobrake??

**Comment by cchard360** [comment]
I don't have pedals. I use a button on the joystick. 

In any case it's very clear the auto brakes are working it's just the Decel light behavior on the button is weird.

**Comment by 2hwk** [comment]
@crocket63 Davy, will this be fixed by PR #4970 ? If so link it so we can close, thanks.

**Comment by crocket63** [comment]
> @crocket63 Davy, will this be fixed by PR #4970 ? If so link it so we can close, thanks.

Definitely, we'll have the correct deceleration provided that the surface conditions allows it.
