### ISSUE TITLE
A320nx not loading anymore after computer change

### ISSUE THREAD

**Issue by jimihendrix272** [flybywiresim/a32nx#4507]
New computer, re-downloaded and installed MSFS2020, used the FlyByWire Installer and Stable tab.

"flybywire-aircraft-a320-neo" is in the Community folder and in there are the normal folders and json files etc. in there.
When I run the sim, it's obvious that A320nx has not loaded.
It was so wonderful before but now back to the original MS version...
Hope you can help.
https://prnt.sc/11phqzy

**Comment by tracernz** [comment]
You still didn't fill the template: https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report.md

The #support channel on Discord is better suited to this type of question. You will find a new option in your MSFS aircraft selection called "FlyByWire Simulations A320neo (LEAP)". Try to select that rather than "Airbus A320neo".

**Comment by jimihendrix272** [comment]
Yes, was thinking of selecting a different A320 last night. I think that could be the reason, will try it later today.
Thanks again.


On 19 Apr 2021, at 22:21, Michael Corcoran ***@***.***> wrote:


You still didn't fill the template: https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report.md <https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report.md>
The #support channel on Discord is better suited to this type of question. You will find a new option in your MSFS aircraft selection called "FlyByWire Simulations A320neo (LEAP)". Try to select that rather than "Airbus A320neo".
