### ISSUE TITLE
EFB/FlyPad light/dark mode.

### ISSUE THREAD

**Issue by ghost** [flybywiresim/a32nx#4601]
**Is your feature request related to a problem? Please describe.**
No, just a "nice to have" feature request.

**Describe the feature you'd like to see implemented**
I think it would be cool to have an option for the EFB FlyPad to have a light and dark mode themes, kind of like how an iPad has a light and dark mode.

**References**
N/A

**Additional context**
Again, similar to how an iPad has the option to use either a light or dark mode, which can help viewability in some lighting conditions.

Discord username (if different from GitHub): N/A

**Comment by antonyisoardi** [comment]
Could also consider have an auto that works something like how an iPad will switch from Light to dark to light based on sunset sunrise etc.

**Comment by ErickSharp** [comment]
Will be picking up this request soon.

**Comment by notl3ks** [comment]
> Will be picking up this request soon. 

Good man! It'll be a good handy little feature. Wether it's used irl I don't know, but a lot of pilots as far as I'm aware use Apple iPad (Android too possibly?) which has the dark & light modes on them, so I figure the same could be applied to the EFB. I think it potentially would make a little difference when flying at night, because the screen can be distracting sometimes when in your peripheral vision.
