### ISSUE TITLE
Cannot calibrate throttles via FSUIPC and EFB

### ISSUE THREAD

**Issue by sandonov** [flybywiresim/a32nx#4654]
Aircraft Version
Development `e8a6794`

Describe the bug
Throttles do not extend within the full range. Trying to calibrate via the EFB but the range sits in the middle and cannot go further down. 

To Reproduce
Start A32nx with FSUIPC running
Set axis in FSUIPC to Throttle1 and Throttle2 direct to FSUIPC calibration
Start EFB throttle calibration

Additional context
I am using Honeycomb Bravo Throttle quadrant
The full range works on the Stable version `0.60`

**Comment by aguther** [comment]
I cannot reproduce the problem:
https://youtu.be/x2O8Bpq_N3o

**Comment by sandonov** [comment]
Thanks for the video. Very interesting that it happens on my end. I will contact FSUIPC support...

**Comment by aguther** [comment]
Does it look and work different on your end than in my video?

**Comment by sandonov** [comment]
@aguther Yes, for me it works different. Do you mind checking this video please. Looking forward to hearing from you!
https://www.youtube.com/watch?v=ay_BX2IU4uo

**Comment by aguther** [comment]
> @aguther Yes, for me it works different. Do you mind checking this video please. Looking forward to hearing from you!
> https://www.youtube.com/watch?v=ay_BX2IU4uo

Ok, it looks like for me, but you need to calibrate them properly. Instead of the full range from -1 to 1 you only can use the range from 0 to 1.

There are two event types in MSFS that can be used:
- `THROTTLE<n>_SET`
- `THROTTLE<n>_AXIS_SET_EX1`

Those are also used in assignment inside MSFS, but unfortunately MSFS internal assignment and FSUIPC seem to send different event ranges for the throttles. So when I fix it for FSUIPC people using internal assignment will run into issues (worse than being only able to use range 0 to 1).

So I suggest to do it as I did, you closely how I calibrated my throttles in the video.

The other option would be to send the axis directly to the sim as normal axis. In that case I recommend using the  `THROTTLE<n>_AXIS_SET_EX1` event type.

**Comment by sandonov** [comment]
Thanks for the explanation. I was trying to do exactly what you described... calibrate the throttles in the EFB from 0 to 1 range, but I think I have failed to press Save and Apply .... :( 
Everything works as expected after I pressed the button now. Thanks for you time!

Regards
