### ISSUE TITLE
Ailerons not working 

### ISSUE THREAD

**Issue by nrsproj** [flybywiresim/a32nx#4694]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-01T22:21:52+00:00",
  "ref": "master",
  "sha": "b63c33db9b402dd4188cdf341e224eeaa71d6a57",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

After pushback and engines on, ailerons are not working (even when plane is airborn).

### Expected behavior

ailerons were supposed to work to turn the plane left or right

### Steps to reproduce

1. cockipt and flight preparation
2. pushback
3. start engines
4. before rolling issue with ailerons

### References (optional)

Video:

https://youtu.be/EEWOiT5QpaU 

### Additional info (optional)

This issue start occurring with the latest update off a32nx
I'am using keyboard

**Comment by aguther** [comment]
Please read the doc „Ailerons are not working when using the keyboard“:
https://docs.flybywiresim.com/start/autopilot-fbw/

**Comment by nrsproj** [comment]
> 
> 
> Please read the doc „Ailerons are not working when using the keyboard“:
> https://docs.flybywiresim.com/start/autopilot-fbw/
> 
> The issue is right now, that the events for the Ailerons are either not fired (`AILERONS_LEFT`, `AILERONS_RIGHT`) or are not recognized (`AILERON_LEFT`, `AILERON_RIGHT`, `AILERON_CENTER`) by SimConnect and so we‘re unable to catch them.

Hello Aguther!

Thank you for your answer.

This problem is only in the developer version? since in the stable version it works fine! If so, is it still an asobo problem?

Do i really need a joystick?

**Comment by aguther** [comment]
The reason why it's working on stable is because it does not have a custom fly-by-wire system. At the moment the only way to implement such a custom system is by catching and masking the events for controls inputs, process them in the custom system and write the output to the sim.

Now this works for all the controls, but as mentioned there is an issue with the Aileron events. We forwarded the info about this to MS/Asobo and hope it will be fixed in an upcoming update.

**Comment by suitea101** [comment]
Hi, someone mentioned using FSUIPC7 to temporarily fix the keyboard ailerons problem. Can someone guide me how to exactly do that? I am used to flying by keyboard also and prefer for now to continue using it.
