### ISSUE TITLE
Fuel flow not being sent to Simulator

### ISSUE THREAD

**Issue by joaogalaio** [flybywiresim/a32nx#4703]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

In Development and Experimental version, it seems the Fuel Flows is not being sent to the Simulator. Reporting this because the fsuipc doesn't have FF value in this two versions but has in the Stable 0.60 version.

### Expected behavior

Connected with fsuipc don't have Fuel Flow return.

### Steps to reproduce

1. Put Development or Experimental versions in the sim with Engines turn on.
2. Connect FSUIPC
3. With FS interrogate or any other application that reads fuel flow offsets verify the values is always 0.

### Discord Username (optional)

galaio

**Comment by MisterChocker** [comment]
The following SimVar contains information regarding fuel flow for each individual engine `L:A32NX_ENGINE_FF:` + engineNo.
The default unit is kg.

**Comment by aguther** [comment]
A gentle hint: the experimental version is not updated anymore. Please switch to development version.

Beside that, the sim currently does not allow to tune the fuel flow so the values would be significantly less realistic. We don't like that either, but it's like it is. We are happy to change if the SDK of the sim allows to do so.

**Comment by Taz5150** [comment]
Exactly as Andreas has explained. Due to the constraints in the fuel flow (and many other parameters) within the Sim, we have to rely on custom LVars and disregard internal variables. That means fuel consumption has to be redone (which already is) and many other things, but you get closer to reality.

That being said, internal Sim fuel flow should NOT be zero. It has been linearized but needs to be above 0 in order for other parameters, such as CN2, to be taken into account. Please check with SimVar viewer the value for fuel flow; I do not have FSUIpc for MSFS, although have a lot of experience in P3D (both free and premium versions).
