### ISSUE TITLE
Can't engage AP, HDG mode won't work either

### ISSUE THREAD

**Issue by franchiceddhu** [flybywiresim/a32nx#4738]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-05-07T04:42:07+00:00",
  "ref": "master",
  "sha": "b1b1f1376f0b0ac154e9420b8ffabf2961dd0772",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

I was flying at FL390, everything nominal. Sim stable at 35+ FPS. At a certain point, and apparently without any input from my side, I found myself at 40000 ft (maybe turbulence or a lag spike?), so the warning went on. Then I noticed my AP1 was disengaged. 

When I tried to reengage it, AP instantly disengaged. Using my dedicated button on my HOTAS, it only triggers A/THR, but AP just keeps on disconnecting. Even HDG mode, either managed or selected, doesn't work at all.

I instantly checked my dead zones and they seem correctly set up. Besides that, my T1600M also has a light when inputs are being given on it, and it's always shut off. I even tried to disconnect every USB device except for mouse and keyboard, since they have no bindings to flight controls.

### Expected behavior

AP1 is meant to reengage after regaining control of the aircraft and leaving any flight controls to neutral. HDG mode, when selected, should point the aircraft to the desired heading ahead of wind correction.

### Steps to reproduce

1. Crusing at FL390
2. Headwind at 60-70 kts
3. No inputs given
4. I found myself at 40000 ft
5. AP1 just disconnects instantly after I try to enable it
6. HDG mode doesn't work

### References (optional)

In the video, you can see me trying to connect AP1, engaging/disengaging FD, fiddling with HDG mode, without any success.

At 2:00 mark, I pressed the assigned AP button on my throttle, and it established AP for a while. It was not the first time I've been trying with that button, but it was the only one it seemed to work after 30+ minutes of trying everything.

https://youtu.be/bEHgX_BxKcY

---

My .fdr files are in this dropbox. The biggest one should refer to my flight. I don't really know about the small one tho, it has the same date and time as the bigger one, so I uploaded it as well.

https://www.dropbox.com/sh/05xrtwi9cz4swhi/AADz7rpix9L9ZR0PjFU72cqQa?dl=0

### Additional info (optional)

Never had such a problem, and I've been using this mod for months (in the last 45+ days I had regular 4-5 hours flight every day).

It was my first flight after updating at the latest DEV version available this morning (it's been 4-5 days since the last update from my side).

**Comment by aguther** [comment]
Looking at the video you are in high alpha protection law and it's intended that AP cannot be engaged anymore as long you're in that protection. To exit the protection, stick forward input is needed, then you can again engage the AP.

I will take a look at the FDR file later what might have been a reason that it happened. MSFS tends to sometimes create extreme altitude changes during cruise or maybe a turbulence was happening.

**Comment by aguther** [comment]
Ok, I did take a look at the FDR file and tbh I have no explanation from the data I see. What I see is that alpha was increasing and due to this the plane was going into alpha protection law. So for the environment the plane has been in, correct behavior.

Now the question is how can we explain that environmental data? My guess would have been turbulence, but at least from the data I have it seems not. My last guess would be an updraft or something like that causing it. I will check if I can capture this in the FDR file in the future (if an simulation variable exists, at least you can see it in the dev mode). There was also no icing or anything, check everything that might have an influence and I did not see any spikes in there, even not oscillations similar to the ones that can be seen in alpha (there are really spikes in, see blue line).
 
![GitHubIssue_4738_1](https://user-images.githubusercontent.com/6629914/117514513-53bf5200-af94-11eb-8224-30816d42adcd.png)
![GitHubIssue_4738_2](https://user-images.githubusercontent.com/6629914/117514516-5457e880-af94-11eb-861b-71faf4e8be89.png)
![GitHubIssue_4738_3](https://user-images.githubusercontent.com/6629914/117514517-54f07f00-af94-11eb-8634-7707c9f8d28b.png)
![GitHubIssue_4738_4](https://user-images.githubusercontent.com/6629914/117514519-54f07f00-af94-11eb-8e45-dfde7aef51c8.png)
![GitHubIssue_4738_5](https://user-images.githubusercontent.com/6629914/117514521-55891580-af94-11eb-8384-d59346513f79.png)
![GitHubIssue_4738_6](https://user-images.githubusercontent.com/6629914/117514523-55891580-af94-11eb-9677-d97766046454.png)
![GitHubIssue_4738_7](https://user-images.githubusercontent.com/6629914/117514525-55891580-af94-11eb-9645-d0df7921ffdf.png)
![GitHubIssue_4738_8](https://user-images.githubusercontent.com/6629914/117514526-5621ac00-af94-11eb-82ae-d988e224e78f.png)
![GitHubIssue_4738_9](https://user-images.githubusercontent.com/6629914/117514527-5621ac00-af94-11eb-9a47-4d2dcf928832.png)
![GitHubIssue_4738_10](https://user-images.githubusercontent.com/6629914/117514529-56ba4280-af94-11eb-82f5-cabf8a7776a1.png)

**Comment by franchiceddhu** [comment]
Thanks for your commitment. Tbh it's the first I got into this behavior, so I had no clue about alpha protection - nice opportunity for me to learn something new. However, this kind of sudden "turbulence" that drives me 1000 ft off cruising altitude isn't new - I might say it strikes 1/10 or 1/8 of the flights. Since it happens randomly most of the times I am not there spectating the event. I hope that I might catch it in video. Most of the times, I just reengage autopilot, return to CA and resume normal navigation.

**Comment by aguther** [comment]
This sudden increase of altitude is even not in the data, that’s the strange thing. Or at least not before alpha protection kicks in.

Yeah we did not announce it yet that it now has alpha protection and high speed protection law.

But in the past I already made my experience with alpha in MSFS. In the beginning of custom autopilot I used alpha also for the calculation of the flight path angle and therefore the FPA law. Turned out that in some cases people got strange behavior. So I switched that. Let’s see how it goes…
