### ISSUE TITLE
BSCU Rudder Pedals Nose Wheel Steering Angle Restriction

### ISSUE THREAD

**Issue by itscongq** [flybywiresim/a32nx#4791]
### Aircraft Version

Development

### Description

The current rudder pedals does not have the restriction like the real aircraft does(6 degrees max), real world operators only use hand tiller when taxing on the ground because the BSCU restrict the N/WS from rudder pedals input to only 6 degrees, which makes rudder control to stay on the centerline when T/O not realistic and very sensitive.

### References (optional)

"
The BSCU transforms the orders into N/WS angle. That angle has the following limits:
- Ruder pedals: max 6 degrees,
- Hand wheels: max 74 degrees.
"

### Additional info (optional)

Would be nice if we can add in a separate axis for hand tiller

### Discord Username (optional)

@CongQ#9443

**Comment by aguther** [comment]
In my opinion a very good suggestion. I'm already watching this since the beginning, but for the moment it does not make sense to work on it. The issue is simply that we cannot properly implement it because the steering **axis** is missing and the rudder seems to be connected in a strange way with the nose wheel.

So let's hope with will come soon with one of the next sim updates and then we can start working on it. It will also need changes to the ROLLOUT law of the autopilot and maybe also changes to the flight model.

**Comment by crocket63** [comment]
That would be a good candidate to one of the first hydraulic actuator simulated.
But as you say, if using masked input "KEY_STEERING_SET" also sets the rudder..... Seems we cannot do it until a new update...

**Comment by lukecologne** [comment]
The problem is the other way around, the rudder always affects the steering, and there is no way to disable that behavior

**Comment by crocket63** [comment]
> The problem is the other way around, the rudder always affects the steering, and there is no way to disable that behavior

Oh :/.  Even if masked input for steering event ?
