### ISSUE TITLE
View currently connected ATC from vatsim/ivao

### ISSUE THREAD

**Issue by ZeroKaa** [flybywiresim/a32nx#4899]
### Aircraft Version

Experimental

### Description

I would like to implement a page "ATC" in the EFB to display the list of currently available controllers from VATSIM (phase1) and IVAO (phase2)
I already started the implementation on :
- this project
- the api project
- the api client project

### Discord Username (optional)

ZeroKaa

**Comment by ZeroKaa** [comment]
![image](https://user-images.githubusercontent.com/8239933/119453761-0c78e580-bd38-11eb-8db7-7c8c2a97fc26.png)

**Comment by St54Kevin** [comment]
Very nice idea! I think we need to use the space avail better in this case because the list can get very long. Also maybe sort them like they are in vPilot (Tower, ATIS, Center etc). I think I would prefere a list rather than big buttons in this case. We can discuss that in discord, I usually have some ideas for improving designs like that :)

**Comment by ZeroKaa** [comment]
Hello. The list should not be that long as I only list the atc close to the plane. So should airport near the aircraft and radar sorted by distance between the plane and the atc. 
My id in discord is the same then here. Feel free to contact me I really need design help to make it better
Thanks a lot

**Comment by MisterChocker** [comment]
Since we konw the origin/destination, we can also actively look for these.
Maybe also filter for flight phases.
Maybe also filter relevant frequencies.
Maybe also display ATIS freq.

Examples:
- Preflight: Order (if available) DELIVERY, GROUND, TOWER, (maybe depature)
_if none of these are online: DEP -> CTR_
- TakeOFf: TOWER, DEP _(if not online CTR)_
- Climb: DEP _(maybe only for x nm away from origin)_, CTR
- Cruise: DEP _(maybe only for x nm away from origin)_, CTR
- Descend: CTR, APR _(maybe only when x nm away from dest)_, TWR _(when within x nm of field)_
- Approach: APR, TWR, GND
- DONE: DELIVERY _(if not avail -> GND, if also not avail TWR and so on)_

**Comment by ZeroKaa** [comment]
Great ideas @MisterChocker .thanks
How do you know the current  flight phase ?

**Comment by Kimbyeoungjang** [comment]
> Great ideas @MisterChocker .thanks
> How do you know the current flight phase ?

you can find that from simvar
<img width="808" alt="스크린샷 2021-05-26 오후 2 55 11" src="https://user-images.githubusercontent.com/23118756/119609346-63fb7c00-be32-11eb-8a86-3a3f6ed55cda.png">

**Comment by ZeroKaa** [comment]
Great thanks for the info. I think I will try to start soon to deliver something and plan a phase 2 where you can choose to see all the atc in range or the one based on you fpl and current phase so user can have both of them

**Comment by St54Kevin** [comment]
> Great thanks for the info. I think I will try to start soon to deliver something and plan a phase 2 where you can choose to see all the atc in range or the one based on you fpl and current phase so user can have both of them

Great. Keep in mind, that you always want to know the frequency of the next phase. So being in approach phase you might need to know also the ground freq to preset it. Or when on ground at DEP you want to know departure / center freq etc.

**Comment by scoopscode** [comment]
> I will probably create the PR today. What's the process to get the change approved and to know if it will be part of a specific release ?

Once the PR is made, maintainers of this project will review the code and find any sort of issues that could potentially cause more issues. After a code review and maybe even changes, they will assign the PR with labels for QA testing. Once QA testing results have been received, you will either have to modify your code or it'll be ready to merge into the master branch/development version.

**Comment by Saschl** [comment]
You just create the PR, someone will review it, it will be tested and then merged to master :) That way it will be on dev and part of the next stable release. Also for future reference: you can create a draft PR that indicates better that you're already working on that topic. That way it's easier for other developers to see that you're already on it and it can prevent that the work is done twice ;)

**Comment by ZeroKaa** [comment]
I created the PR : https://github.com/flybywiresim/a32nx/pull/4919
but I think it keep on failling to validate the name. I updated it to respect the "feat: " in the start of the title.

**Comment by Saschl** [comment]
That's okay, the check doesn't run again when changing the title, but it's not a problem for now. We either trigger it manually or it runs again with the next commit

**Comment by ZeroKaa** [comment]
Great. thanks for your help !

**Comment by ZeroKaa** [comment]
PR Requested : https://github.com/flybywiresim/a32nx/pull/4919
