### ISSUE TITLE
PRK BRK ON/OFF not detected by various ACARS programs

### ISSUE THREAD

**Issue by Neirius** [flybywiresim/a32nx#5006]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-04T14:58:44+00:00",
  "ref": "master",
  "sha": "53b18c2f5a2c65254b5e4edaadf8ba64e6d1ff34",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Hi guys,

For the past few Dev versions I have been noticing that the various programs I use to track my flights (UVAcars and VAS ACARS) don't detect when I have my PRK BRK ON even though it is detected when I use different airplanes.

Have there been any changes the past few days that might have affected this?

Thanks in advance,

BR

### Expected behavior

Starting a flight, with my PRK BRK ON and engines stopped my flight status immediately goes to the Taxi Out mode

Reciprocally when parking on stand, after PRK BRK ON and engines shut down my status remains Taxi In and never arrived at gate

### Steps to reproduce

I only use these 2 trackers so I don't have way to compare with other ACARS programs but any one that does detect the various stages of a flight should be good to reproduce this behaviour

**Comment by MANFahrer-GF** [comment]
I can also confirm the error

**Comment by donstim** [comment]
@crocket63

**Comment by crocket63** [comment]
Hi, 
This is due to the fact we are not reporting in the variable "PARKING BRAKE POSITION" as parking brake is now disabled in default FS2020. A320 indeed doesn't have any cable parking brake system.

The var corresponding to the parking brake lever is now "A32NX_PARK_BRAKE_LEVER_POS" and it reports the position of the lever only. 
I understand this is not ideal for compatibility, but I did not find a possible work around yet, as disabling parking brake in FS2020 makes us unable to write to standard PARKING BRAKE POSITION variable.

**Comment by Benjozork** [comment]
Closed as partly out of scope and explained above
