### ISSUE TITLE
[REQUEST] Real Rate of Climb (RoC) and Rate of Descente (RoD) implementation

### ISSUE THREAD

**Issue by Sierramike71** [flybywiresim/a32nx#504]
**Is your feature request related to a problem? Please describe.**
I experienced a quite high climbing rate after take off till cruise level and the same for Rate of Descente

**Describe the feature you'd like to see implemented**
Is it possible the Auto Pilot use the standard RoC and RoD, I am quite suprise to have a 4000 fts/mn climbing after Take off.

**References**
see attached picture from EuroCTRL : https://contentzone.eurocontrol.int/aircraftperformance/details.aspx?ICAO=A320&ICAOFilter=a320

**Additional context**
none

**Comment by taintotain** [comment]
The rate of climb commanded by the autopilot varies depending on which climb mode it's in and the weight of the aircraft. There is no "standard" rate of climb. In open climb mode, the aircraft will pitch to maintain the selected airspeed at climb thrust (around 90% N1). If the aircraft is light, this can easily be in the 6000 ft/min range with target speed set to 250 kts.

The page you reference is a bit misleading. After rotation, pitch is adjusted to maintain speed and rate of climb will be whatever it needs to be to maintain that speed at TO/GA thrust. During climb to cruising altitude, managed climb mode is typically used instead of open climb. In this mode, the autopilot will follow a climb profile such that the target altitudes at each waypoint are reached, commanding whatever rate of climb is needed to do so (while respecting the managed speed). So, you see, rate of climb is not constant for given phases of flight in any way.

**Comment by Sierramike71** [comment]
Ok thanks for the feedback
