### ISSUE TITLE
AUTO LAND light is backwards

### ISSUE THREAD

**Issue by Illuminati270** [flybywiresim/a32nx#5090]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-10T09:49:19+00:00",
  "ref": "master",
  "sha": "1578f4fa852800ef1d7c46ad6460f21bf92a2c3a",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

Autoland light is backwards

### Expected behavior

Texture should be red background with black words

### Steps to reproduce

1. Turn on the light test and compare with the photo

### References (optional)

![image](https://user-images.githubusercontent.com/85410344/121652624-36d5dd00-ca72-11eb-99af-e89eeacadcca.png)

### Discord Username (optional)

Illuminati

**Comment by aguther** [comment]
As far as I know it’s also flashing and not steady, is that correct?

I’m not sure if this Bug is fixable.

I tried already to get it flashing - it was barely visible then, I think this is an issue in relation to the engine. Therefore I kept it steady.

In regards to model/texture I have no idea if that can be done.

**Comment by Illuminati270** [comment]
> As far as I know it’s also flashing and not steady, is that correct?
> 
> I’m not sure if this Bug is fixable.
> 
> I tried already to get it flashing - it was barely visible then, I think this is an issue in relation to the engine. Therefore I kept it steady.
> 
> In regards to model/texture I have no idea if that can be done.

Correct.

On the light test it will be steady;
When you press it, the light starts flashing (and if the LS is turned on, the GS/LOC deviaton dots will flash as well).
Actual loss of autoland capability will do the same.

What a pity the texture can't be fixed :(

**Comment by aguther** [comment]
I check with our designers/modelers if that can be done.

As I said, also the flashing right now is not fixable. I tried it already, and then it was not visible at all. As far as I understand it’s something related to how the visual engine of MSFS treats lights.

**Comment by tracernz** [comment]
What is the period/frequency of the flash? I have made the evac lights flash okay with 1 second period (IIRC), but if you want to go too fast you run into an issue with the emissive texture fading in, rather than immediately going to full brightness. It's maybe possible to make the button illuminate red... if there is enough room left on the texture... I have one idea, and if that fails it would require some Tyler magic, or have to wait until we can edit the model directly in blender.

Whatever the case, it would be difficult to get it correct without a much higher resolution reference pic of the button illuminated, and not illuminated.

**Comment by sidnov** [comment]
@tracernz Looks like a transparent button to me https://soarbywire.files.wordpress.com/2020/08/351e6-img_1291.jpg?w=2048&h=1536

**Comment by sidnov** [comment]
Some more refs https://sim-on-a320.com/pin-out/131vu-130vu-glareshield-panel/

**Comment by Illuminati270** [comment]
@aguther 

Yeah, I was about to ask about the FS capability to deal with that... I noticed that the lights were coming on and off in a very "fancy" way. Then I realised it is just the same way as the FS2020 turns on the lights.

@tracernz 

Well, I'd say it flashes >1<3 times per second. But if you can make at the same rate as EVAC command, that'd be great already!


@sidnov 

By transparent, I'm guessing you're relating it to MD-11's landing gear lights! Which is not the case. The Airbus' autoland lights are solid black when off and solid red when on! (Second photo of your second link is an excelent representation of it!)
