### ISSUE TITLE
ISIS auto brightness

### ISSUE THREAD

**Issue by AntoineXWB** [flybywiresim/a32nx#5101]
### Aircraft Version

Development

### Description

Hey,

There is a light sensor on the A320NEO on the ISIS (Integrated System Instrument Standby, here PFD shown on this screen). The brightness is therefore adjusted according to the ambient light.

It is a small black square.

![Capture d’écran (99)_LI](https://user-images.githubusercontent.com/81491742/121789492-b086db80-cbd6-11eb-99b0-f175477ce4b1.jpg)

### Discord Username (optional)

AXWB#8487

**Comment by BlueberryKing** [comment]
While it seems quite hard to extract the ambient brightness from the sim for a proper implementation, I am thinking it might be possible to get somewhat realistic behavior by just using the local time of day to get an estimate for the amount of daylight in the cockpit. This obviously won't take into clouds into account or something like the dome lights, but I'll see what I can do.

**Comment by MisterChocker** [comment]
@BlueberryKing Keep in mind that the day hours differ from season to season and from place to place...

**Comment by AntoineXWB** [comment]
You can not use the time with is use for the weather in the sim ?

**Comment by sidnov** [comment]
> While it seems quite hard to extract the ambient brightness from the sim for a proper implementation, I am thinking it might be possible to get somewhat realistic behavior by just using the local time of day to get an estimate for the amount of daylight in the cockpit. This obviously won't take clouds or something like the dome lights into account, but I'll see what I can do.


I've gone through this a little over a week ago, local time works best for places closer to the equatorial line. In situations like flying in Norway or similar locations, sometimes there's barely any light at noon. I did get a suggestion from a user in the comments (https://github.com/flybywiresim/a32nx/pull/5018) to use the available lat/lon to calculate sunrise and sunset. Maybe you might be interested in a similar approach, if so, I can work out a way to create a common utility which can be used across the mod for the so-called "brightness sensor" effect

**Comment by BlueberryKing** [comment]
I am still looking at what variables are available, but as @MisterChocker correctly pointed out there's a lot to consider. Polar nights, etc. Aside from the fact that I have to figure out how to have an automatic setting, but also allow pilots to adjust brightness using the buttons.

**Comment by BlueberryKing** [comment]
I have implemented a basic auto brightness system for the ISIS. Just like the chrono in #5018, the system switches between a night and a day brightness setting, however I check for daytime by computing sunrise/sunset for at the coordinates of the airplane using this algorithm: https://edwilliams.org/sunrise_sunset_algorithm.htm instead of just using 6:00 and 18:00.

I handle the brightness increase/decrease buttons by simply adjusting the day/night setting depending on the time of day.

This system seems to be working fine, but can also be tuned a bit if need be.

How do you want to proceed, @sidnov? For now, I have put in the sunrise/sunset calculation in the `A32NX_Util.js` file, but I think it would be wise to put it into a separate file as the calculation is a bit extensive and could be done cleanly by implementing some helper methods and making it usable across the mod as you mentioned. Let me know if you want me to open a PR to see my code and potentially merge it with yours.

**Comment by sidnov** [comment]
@BlueberryKing Sounds good. Putting the code in a common file would definitely help multiple components. You can go ahead an open up a PR, I'll adapt mine according to it once I'm through with exams at university.

Before that, had a couple of questions.
For the ISIS, how do you plan to have both auto and manual brightness systems implemented, I'm kinda sure that if you override with manual buttons, it should remain that way, atleast till the next major lighting change. Are there any sorts of performance impact with the algorithm? Is the algorithm accurate enough to match the conditions in places with significantly different day/night cycles?

**Comment by tracernz** [comment]
> For the ISIS, how do you plan to have both auto and manual brightness systems implemented, I'm kinda sure that if you override with manual buttons, it should remain that way, atleast till the next major lighting change. Are there any sorts of performance impact with the algorithm? Is the algorithm accurate enough to match the conditions in places with significantly different day/night cycles?

It'd be interesting to know how sophisticated the real one is... is the manual adjustment just an offset against the auto-brightness, similar to how a phone screen works (although they're smarter than that  I reckon)?

**Comment by BlueberryKing** [comment]
I have now opened a draft PR (#5115). Regarding your questions, @sidnov:

> For the ISIS, how do you plan to have both auto and manual brightness systems implemented, I'm kinda sure that if you override with manual buttons, it should remain that way, atleast till the next major lighting change.

I describe this in the PR. If my explanation is not clear, feel free to look at the code.

> Are there any sorts of performance impact with the algorithm? 

I don't have a lot of experience with this. Here are my thoughts: The sunrise/sunset algorithm is quite extensive, but at the end of the day it's just mathematical operations; no API calls, file IO or anything. This is what computers are incredibly fast at, so I don't think the impact should be that significant. However, it's still worth optimizing what can be optimized. At the moment, I update the brightness every 3 seconds, but this rate can be decreased if needed.

Furthermore, instead of using the proper trigonometric functions, it is possible to implement low order approximations of these if needed, since we do not need maximum numerical accuracy.

What it comes down to is quantitatively measuring the performance impact somehow, but I don't know how I would do that.

> Is the algorithm accurate enough to match the conditions in places with significantly different day/night cycles?

I have put just the algorithm into a quick JS script to test it out and it seems pretty good, particularly for polar regions too. If people notice the brightness switching too early or too late, it is also possible to tune the algorithm with pretty much one parameter.

**Comment by AntoineXWB** [comment]
> > For the ISIS, how do you plan to have both auto and manual brightness systems implemented, I'm kinda sure that if you override with manual buttons, it should remain that way, atleast till the next major lighting change. Are there any sorts of performance impact with the algorithm? Is the algorithm accurate enough to match the conditions in places with significantly different day/night cycles?
> 
> It'd be interesting to know how sophisticated the real one is... is the manual adjustment just an offset against the auto-brightness, similar to how a phone screen works (although they're smarter than that I reckon)?

The real one works as follows:

The sensor is a simple light sensor, during the ground tests before delivery, it is asked to test it simply by putting his hand in front. The sensor reacts quickly and lowers the brightness and returns to its normal brightness when you take your hand away.
In some configuration like when starting the aircraft, the sensor does not work directly, but I do not yet know why. I can try to take a video, but it is very difficult since it is prohibited and there are a lot of people on the station.
However, you can increase and decrease the brightness manually, the default one corresponds exactly to reality. Unfortunately I was not able to test this action in addition and see how the auto brightness reacts.
If I can do it, I'll test it on an airplane.

Unless a pilot on Discord sends the video before me ^^

**Comment by AntoineXWB** [comment]
Hey, I have a video to help you in #private references on Discord.
