### ISSUE TITLE
Refuel Time Option Not Saving

### ISSUE THREAD

**Issue by AviationSpotter** [flybywiresim/a32nx#5110]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-13T20:38:36+00:00",
  "ref": "master",
  "sha": "68dfae0ec88ef384acd87da748f52e66f59d9d7e",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

If left refuel time option to either "Instant" or "Fast" then the EFB will save to that option after exiting. Only one option will not save and that is the "Real" option. This occurred when I tried out the other options and afterwards my "Real" option would never save after exiting.

### Expected behavior

Refuel time options should save to Real as like it saves with Instant and Fast options. (If anything especially the "Real" refuel time option should save due to the fact that it will be used the most).

### Steps to reproduce

1. On the EFB, navigate to Dispatch -> Fuel
2. Set your refuel time to either Instant or Fast and afterwards set back to real
3. Go back to the main menu and load back in the aircraft (do not use the restart button as it's not the same as a complete exit)
4. Head back to EFB, navigate to Dispatch -> Fuel

### References (optional)

A video showing the bug

https://user-images.githubusercontent.com/72807945/121829934-df15bc80-cc91-11eb-844d-dfd33f4fbbdf.mp4

### Discord Username (optional)

Aviation Spotter#9102

**Comment by BlueberryKing** [comment]
I am pretty sure the issue here is that this `if` returns false if `simVarValue` is 0, because 0 is falsy in JS and we use 0 to indicate the refuel rate "real".
https://github.com/flybywiresim/a32nx/blob/5f697b19d622af507ec5ca4854c253d375e105c8/src/instruments/src/Common/persistence.tsx#L75-L77
Easiest fix would be to encode refuel rate "real" with a value other than 0, e.g 3. However I suspect that this could cause issues other parts of the code base using persistent variables.
