### ISSUE TITLE
Windshield Wipers stop above certain speed

### ISSUE THREAD

**Issue by komp1821** [flybywiresim/a32nx#5238]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-29T09:04:22+00:00",
  "ref": "master",
  "sha": "51c06af09bb23ab0d9d79c8e224306ad71c09087",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

The windshield wipers appear to be inhibited above a certain airspeed (about 250 kts?) 

### Expected behavior

They are not inhibited. There is nothing in the wiring diagram that would prevent movement.

### Steps to reproduce

1. Fly < 250 kts - turn on windshield wiper - wiper operate
2. Fly > 250 kts - turn on windshield wiper - wiper does not operate.

### References (optional)

See references channel in Discord.

### Discord Username (optional)

komp#1821

**Comment by Beedan1G** [comment]
Not really a bug, as no aircraft would be able to turn them on above a certain speed in the real world since they would snap off due to the speed and force, also at that speed the rain it pushing up words and cleaning as you go through it.

Also wipers don't work anyways in MSFS as it doesn't clear the windows I believe that is a MSFS issue tho as tried wipers on the default A320 and other aircrafts and the rain doesn't clear with them on they are stuck there as if it is a texture
