### ISSUE TITLE
APU cannot be started on battery

### ISSUE THREAD

**Issue by ajs117** [flybywiresim/a32nx#5265]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-01T14:38:08+00:00",
  "ref": "master",
  "sha": "2a23f44e7faf992b6345bbae8bae43ab2031e022",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

APU cannot be started on battery.

ECAM screen should come on on battery on to monitor APU.

### Expected behavior

APU can be started on battery.

ECAM screen should come on on battery on to enable monitoring of APU startup.

### Steps to reproduce

1. Battery 1 and 2 on
2. Try to start APU
3. Note ECAM screen is not on

**Comment by komp1821** [comment]
The ECAM screen cannot come on because it is not powered in this situation. This is intended and matches the real life behavior.

The APU is starting nevertheless. Watch out for the ON light in the start pushbutton. This is your only indicator for APU start on batteries only. You can also pay attention to the sound of the start contactors being engaged and later disengaged.

**Comment by 2hwk** [comment]
Cannot reproduce, am able to start the APU on battery only power. ECAM screens not being on is intentionally modelled as this is what would happen in the real aircraft, as there is not enough power available.
