### ISSUE TITLE
Unable to reach higher altitude

### ISSUE THREAD

**Issue by Rodolfo1942** [flybywiresim/a32nx#5300]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Istwert (29780 Fuss) der Höhe stimmt nicht mit dem Sollwert (z.B. 30000 Fuss) überein.
![20210710_195110](https://user-images.githubusercontent.com/87265205/125194319-09d34080-e251-11eb-8244-cd8a1df5bf27.jpg)

### Expected behavior

Eingestellte Höhe und erreichte Höhe sollten übereinstimmen.

### Steps to reproduce

Flug EDDK nach EDDM. Eingestellte Höhe 24000 Fuss bei Höhe bei 23780 ging es nicht mehr weiter auf die eingestellte Höhe.

### References (optional)

![20210710_195110](https://user-images.githubusercontent.com/87265205/125194473-c2997f80-e251-11eb-862b-55dbbbff10ed.jpg)

### Discord Username (optional)

Rodolfo1942

**Comment by globin** [comment]
Translating; Aeroplane did not reach altitude for the autopilot.

Did you use real weather? There are bugs where the temperature is too high and higher altitudes can't be reached due to reduced performance. Sadly cut off from the screenshot. If this is the case please use a weather preset.

Hast du "echtes Wetter" benutzt? Es gibt Bugs damit und die Temperatur zu hoch ist und durch reduzierte Engine-Performance die gewünschte Höhe nicht erreicht werden kann. Ist auf dem Screenshot leider abgeschnitten. In dem Fall am besten auf ein Wetter-Preset umstellen

**Comment by MisterChocker** [comment]
@Rodolfo1942 

Bitte sende uns ein Bild vom lower ECAM.
Außerdem kontrolliere einmal ob die Flugphysik bzw Flugmodell in den Einstellungen vom Sim auf Modern steht.

_Please send us a picture of the lower ecam, also ensure the modern flight model in the simulator settings is selected_

**Comment by Rodolfo1942** [comment]
Abflug EDDK, Höhe 5000 Fuss, erreichte Höhe 4880. Wetter nicht live.
5000 Fuss müßte er locker erreichen.
Außerdem weicht der Kurs ab Vor Col vom Flugplan des msfs2020 ab. Fliegt geradeaus immer weiter.
Flugpläne mit Simbrief erstellt, fliegt er einwandfrei ab.
Der Fehler trat wahrscheinlich auf, nachdem ich den FBW A320N bei msfs2020 upgedatet hatte, mittlerweile wieder gelöscht.
FBW A320N wurde mittels Installationsprogramm neu installiert (Stable).

**Comment by globin** [comment]
Kannst du bitte Screenshots von PD, ND und beiden ECAM-Displays anhängen, sonst ist das unmöglich zu debuggen, evtl noch den Flugplan selber.

Could you please attach screenshots of PD, ND and both ECAM displays, maybe even the flight plan from simbrief itself? Otherwise it will be near impossible to debug this.

**Comment by Rodolfo1942** [comment]
Habe auf MODERN umgestellt, Höhe, im Foto zu sehen, wird erreicht.
Der Flugplan, im msfs2020 erstellt, wird vom Flieger nicht abgeflogen. Ab Vor COL immer weiter geradeaus.
![20210712_112916](https://user-images.githubusercontent.com/87265205/125266415-1b2a5480-e306-11eb-914e-c0e77c2df6d3.jpg)
![20210712_111843](https://user-images.githubusercontent.com/87265205/125266440-1f567200-e306-11eb-9ec2-1191a9980c41.jpg)
![20210712_111230](https://user-images.githubusercontent.com/87265205/125266460-22516280-e306-11eb-9360-67c99aa2afb6.jpg)
![20210712_112540](https://user-images.githubusercontent.com/87265205/125266477-25e4e980-e306-11eb-9cd5-98099e7a98f4.jpg)

**Comment by MisterChocker** [comment]
Closing since issue resolved.

For the `aircraft not following flight plan` issue open a new issue since github only supports on issue per issue.

GER:

Issue wird geschlossen da das ursprüngliche Problem behoben wurde.
Für das Problem `Flugzeug folgt dem Flugplan nicht` bitte ein neues Issue öffnen.
