### ISSUE TITLE
[BUG] When adjusting brightness knob screens go into self test mode

### ISSUE THREAD

**Issue by starvingjavi** [flybywiresim/a32nx#531]
**Mod Version**
Master

**Describe the bug**
After having electrical power on the airplane and after the screens have done their self test, if the brightness knobs are re adjusted the screens will go back into self test mode.

**To Reproduce**

1. During any point of the flight
2. Lower brightness knob of PFD
3. Turn brightness back up

**Expected behavior**
Screen should continue to display what it was displaying before

**Actual behavior**
Goes into self test mode and you have to wait for the screen to restart

**Comment by AdenFlorian** [comment]
it is supposed to go into self test when turning the brightness knob all the way off and then back on, because turning the knob all the way off turns the screen off. I just tested on master and I don't see it going into self test when just changing the brightness a little bit. If you have a reference that says otherwise please post or link it, thanks!
