### ISSUE TITLE
[BUG] Altitude  to descent 

### ISSUE THREAD

**Issue by griffon55** [flybywiresim/a32nx#540]
**master**

**plane not to descent I must to use speed brake**

**enter lower altitude and click to managed altitude plane not to descent if speed is too fast about speed managed I must to use speed to reduce speed before airplane descent**

1.insert lower altitude 
2.click managed  altitude 
3.

**must to descent even if speed not at managed speed**

**plane not descent if I don't use speed brake**

**References**

**Additional context**

**Comment by TheTreeThatGrows** [comment]
Dont use managed to descent, use selected altitude to descent. If you want to descent with the managed one, you would have to set that in the MCDU

**Comment by tomber42** [comment]
> Dont use managed to descent, use selected altitude to descent. If you want to descent with the managed one, you would have to set that in the MCDU

Yes..aet desired altitude and pull the alt knob ..this activate open decent

**Comment by griffon55** [comment]
Because with aerosoft a320 managed altitude plane descent immediately

**Comment by griffon55** [comment]
I just try selected  altitude and the same issue I must to use speed  brake to descent

**Comment by TheTreeThatGrows** [comment]
Need to wait for a bit, if not then juste use vertical speed to descend.

**Comment by griffon55** [comment]
Aerosoft  a320  no wait plane descent  right now even managed

**Comment by TheTreeThatGrows** [comment]
Yeah its because the default a320 neo on msfs is very unrealistic atm. This mod fixes some of the issues including selected altitude descent. Normally you would have to pull the knob every time you want to change altitude, but this mod makes it so that you dont have to. For now just use vertical speed to descend, and selected altitude to ascend. Shouldnt be a problem using selected altitude with the mod activated tho.

**Comment by MisterChocker** [comment]
fixed by now
