### ISSUE TITLE
Speed, Fuel Burn and Auto switch to Mach Speed Selection

### ISSUE THREAD

**Issue by noobielameo** [flybywiresim/a32nx#5480]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-30T08:31:00+00:00",
  "ref": "master",
  "sha": "35319ba865066bd2b1d8603cfb43ec9dbc340353",
  "actor": "beheh",
  "event_name": "manual"
}
```

### Describe the bug

Normal - Cruise at FL300, Speed 260, Fuel 40kg/min
Bug - Speed reduced to 220 and fuel burn increased to 110kg/min, repeated issue.
causing fuel to run out a lot sooner.
Speed selector auto switch to mach.
![Speed Drop Fuel Burn High](https://user-images.githubusercontent.com/88166629/127658616-ee8b5f39-6e0e-4b31-90fb-9aaba1fa1388.jpg)

### Expected behavior

Cruising speed and fuel burn at FL300
![Normal Fuel Burn](https://user-images.githubusercontent.com/88166629/127658559-6ab0666a-59aa-443d-ad60-0b63d12e6c82.jpg)

### Steps to reproduce

Check flap and airbrake are off.
Reduced flight altitude to FL280 and maintain same speed selection 260
Climb to FL300 with speed selection 290 - stays normal for a while and the issue appears again

**Comment by NUTTTTTTTT** [comment]
MSFS live weather bug, not specific to FBW and supposed to be fixed in their hotfix update today.  Please see our known issues site before raising issues. https://docs.flybywiresim.com/ 👍 

**MSFS Weather - Poor climb performance/Low airspeed/High fuel flow:**
https://docs.flybywiresim.com/start/reported-issues/#msfs-live-weather
