### ISSUE TITLE
Air Speed Glitches Above A Certain Altitude & LVR CLB thrust not registering

### ISSUE THREAD

**Issue by BainCat1** [flybywiresim/a32nx#5508]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-31T20:53:08+00:00",
  "ref": "master",
  "sha": "12dd02fba9f16606942a76176c73dfb3da230cfa",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

After a certain altitude, the airspeed will either jump up or down a drastic amount. this typically happens during cruise for me. 

This might have a correlation with the LVR CLB not registering when thrust is set to CLB. This is shown when LVR CLB blinks white on the Primary Flight Display.  

### Expected behavior

Ground speed is supposed to be smooth and not jump. 

LVR CLB blinking is supposed to disappear on the flight display when thrust is set to CLB

### Steps to reproduce

1. Set Thrust to CLB and wait to reach cruise Alt & notice the ground speed drastically jumping
2. When Thust CLB is set, notice LVR CLB blinking in white in the top left corner of the flight display

### Additional info (optional)

My apologies if this is a known issue.

**Comment by donstim** [comment]
If LVR CLB is blinking, then you do not have your thrust levers in the CLB detent. The FMA (what you see at the top of the primary flight display) shows whether or not you are in the right detent, not the position of the thrust levers as viewed in the cockpit. To sync these positions, you need to calibrate your thrust levers by using the calibration tool in the Electronic Flight Bag (EFB).  See https://youtu.be/8yZuv2L4jPA for how to do this.

You say that airspeed will jump up or down a drastic amount and then refer to ground speed. True airspeed and ground speed are linked in that the difference between them is the wind that is acting in the direction parallel to the airplane's flight path. If you are using live weather, there is currently a bug that causes large swings in wind speeds as well as exceedingly high temperatures the higher you go. Until this bug is fixed my Microsoft/Asobo, when you encounter it, you should consider using a preset or custom weather condition rather than live weather.

**Comment by abuelo007** [comment]
I was going to lock for a similar bug submission, but I found this one.
I'm adding the video to show exactly what is happening.

Behaviours as follow, fliying between FL313 and FL310:
- I was at 290 IAS FL313, while adjusting to FL310 suddenly drop to IAS 240, wind start behaving strangely changing direction frecuently, and also fuel cossumption peaked above 4000 kg/h on each engine.
- Going back to FL313, everything comes back to normal

Of course GS and TAS start behaving strange, and altimeter also instead of showing an increase in altitude while having vertical speed start showing a decrease on altitude.

Please see the video both videos compeltely and review all indicators in the screen, with what I just mentioned

https://user-images.githubusercontent.com/88299309/127798019-e8bd99a4-41e3-4a46-bc04-288ce63b7d86.mp4


https://user-images.githubusercontent.com/88299309/127798024-5b84d81a-848a-45d3-9883-50486c5d76cf.mp4

**Comment by Benjozork** [comment]
As said above, live weather is problematic. Please specify whether you are using or not.

**Comment by abuelo007** [comment]
> As said above, live weather is problematic. Please specify whether you are using or not.

I was using live weather flight from Washington to Charleston.

**Comment by donstim** [comment]
You can see a dramatic wind shift in both videos.

**Comment by abuelo007** [comment]
> You can see a dramatic wind shift in both videos.

Again it only happen while changing the altitude. If you stay on the same altitude nothing happen. I was staying at FL300 for 20 minutes and nothing happened but IAS was 240 and wind showing irregular changes in direction constantly, which could be the case on waht you are mentioning, but why just trying to move down or up  300 feet shows are dramatic chaging in all parameters, meaning:

- Wind stabilization or not
- IAS changing from 290 to 240 or viceversa
- Fuel consumption from/to 1xxx-2xxx from/to 4xxx per engine

If that is the real behaviour on the indicators and system, it is ok. I'm not a real Airbus pilot :-)

**Comment by abuelo007** [comment]
My apology, It seems I didn't read before that there was a bug already identified. Thank you !!!!

**Comment by Benjozork** [comment]
To be clear, the issue is with MSFS.

the work around is to choose a weather preset for now.

**Comment by aguther** [comment]
MSFS Live Weather Bug / Throttles not correctly calibrated.
