### ISSUE TITLE
[REQUEST] Pack and Air Conditioning Functionality 

### ISSUE THREAD

**Issue by iRetroSpex** [flybywiresim/a32nx#553]
**Is your feature request related to a problem? Please describe.**
This request is not related to a problem. 

**Describe the feature you'd like to see implemented**
Adding the functionality for the Pack switches means that the bleed air from either the APU or Engines can be used to air conditition the cabin and pressurize the aircraft above 10,000 ft. This is a vital switch and function for any aircraft.

**References**
Not Applicable

**Additional context**
Not Applicable

**Comment by lcalaresu** [comment]
I would be very happy to develop a complete packs system and conditioning system. 
This could fill the BLEED and COND pages ... maybe even some info on pages here and there.

Until the PRESS page is finished, we can consider the inlet and outlet doors to always be open (even on take-off / landing)... when decent pack controllers will be modelised, we might be able to be more precise.

In any way, a **zone controller** will need to be modelised to monitor the temperature in the 3 zones. It then sends signals to the **pack controllers** to set the air temperature delivered by the packs.
Cold air is delivered by the packs and is sent to the 3 zones by the **mixer unit**.
Hot bleed air is added via 3 trim air valves (cockpit, fwd and aft) to acheive the demanded temperature in each zone.
**Pack 1** valve, **pack 2** valve and **Hot air** valve should also be modelised.

Then, we will need an "**zone temperature** model" to estimate how the air will heat up within the different zones, depending of the "_zone duct temperature_", the current _zone temperature,_ and the volume of the zone.

**Cabin fans** are fitted to reduce the bleed air requirement (and therefore, save fuel). They establish an air flow between the zones and the mixer unit. There is no ECAM indication about those cabin fans in normal operations, but they need to be modelised in order to calculate more precisely how the air will heat up within the zones.

The following buttons will also need to be activated on the overhad panel : 
    - air cond panel : PACK1, PACK2, PACK FLOW, HOT AIR, 
    - ventilation panel : CAB FANS

**Comment by Emile31** [comment]
So is there someone developping this ?
If needed I can support as testing air system is part of my day job.

**Comment by lcalaresu** [comment]
Indeed i am. Will let you know when it is ready to be tested (I am a bit busy at work this week... I don't work much on it these days).

**Comment by Emile31** [comment]
OK perfect !
So you have all info you need I guess

**Comment by tareksabet** [comment]
fixed by #1209
