### ISSUE TITLE
Thrustmaster airbus thrust controller 

### ISSUE THREAD

**Issue by hickmannick1** [flybywiresim/a32nx#5530]
### Aircraft Version

Development

### Build info

```json
<ModelBehaviors>
    <Include RelativeFile="../Airbus.xml"/>
    <Include RelativeFile="../AirlinerCommon.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_ADIRS.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_ATC.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_Autopilot.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_Elec.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_Engine.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_FCU.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_Fire.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_MCDU.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_Misc.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_Handling.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_Printer.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_RMP.xml"/>
    <Include RelativeFile="../generated/A32NX_Interior_Sidestick.xml"/>
</ModelBehaviors>
```

### Describe the bug

Thrustmaster airbus controller won't calibrate with flight pad. 

### Expected behavior

Used to run perfect, now won't calibrate to all speed levels including reverse thrust

### Steps to reproduce

Downloading lastest version and world update 5
Stable Version 6.2 works fine

### Discord Username (optional)

hickmannick1

**Comment by hickmannick1** [comment]
The throttles move but won't calibrate to the right positions. I'll try and get screen shots for you.

**Comment by hickmannick1** [comment]
[Toga.pdf](https://github.com/flybywiresim/a32nx/files/6932004/Toga.pdf)
[REV Idle.pdf](https://github.com/flybywiresim/a32nx/files/6932005/REV.Idle.pdf)
[REV full.pdf](https://github.com/flybywiresim/a32nx/files/6932006/REV.full.pdf)
[Idle thrust leaver.pdf](https://github.com/flybywiresim/a32nx/files/6932007/Idle.thrust.leaver.pdf)
[Idle.pdf](https://github.com/flybywiresim/a32nx/files/6932008/Idle.pdf)
[Climb.pdf](https://github.com/flybywiresim/a32nx/files/6932010/Climb.pdf)
[Flex.pdf](https://github.com/flybywiresim/a32nx/files/6932011/Flex.pdf)

**Comment by hickmannick1** [comment]
The above shows the thrust calibrated. See the idle leaver for example

**Comment by NUTTTTTTTT** [comment]
You need to increase the ranges. The ranges you've set are really small, and won't be easy to get them in the right positions. My climb detent for example is set as 0.12. When you apply the calibration settings, putting your throttles into the detents as you've set them on the EFB will automatically move the throttle levers in your cockpit to the correct detent. Have a look at https://youtu.be/8yZuv2L4jPA and ensure you're setting appropriately sized ranges that you can easily move the throttles to, without small movements knocking them out. :)

**Comment by hickmannick1** [comment]
I'll try again and see what happens, thanks for your help.

**Comment by hickmannick1** [comment]
[Idle on tablet.pdf](https://github.com/flybywiresim/a32nx/files/6933660/Idle.on.tablet.pdf)
[idle on thrusters.pdf](https://github.com/flybywiresim/a32nx/files/6933661/idle.on.thrusters.pdf)

So I've changed my settings and still have the same probelm, it's like the idle is set to high. Sensitivity settings are as recommended which work on stable version.

**Comment by NUTTTTTTTT** [comment]
See the red text below the main bar, the EFB won't allow you to apply a calibration change while that message is there so the issue is unchanged as the settings in the EFB are.

Please calibrate the detents and ranges using the tutorial for reference in a way to work best for you, and ensure that text does not show anymore. Start from the TOGA detent, place the throttle where you want toga to activate and press "Set from throttle". Set the range to something reasonable for you to easily click into and then move onto the next detent working down. 

Make sure that none of those detents are overlapping, because you can't activate both detents at the same time. :)

What's happening in your latest screenshots is that you've now got the ranges set trying to replicate my range of 0.12, and made it so that there is a part of your throttle range where you have activated both climb and flex thrust, which the EFB won't allow.

**Comment by hickmannick1** [comment]
I'll give it another go now, I've been using the a32nx for a while now and haven't had this problem before. It's most likely to be me but you never know haha.

**Comment by hickmannick1** [comment]
Still not right, even watched the video. The idle blue boxes are to high, it won't let me calibrate it right. I'll use the stable version and hopefully the bug disappears in future updates. Thanks

**Comment by NUTTTTTTTT** [comment]
> Still not right, even watched the video. The idle blue boxes are to high, it won't let me calibrate it right. I'll use the stable version and hopefully the bug disappears in future updates. Thanks

You just need to move your throttles to the idle position, and then press "Set from throttle" to move it. It's not a bug. This will become the norm in Stable version 0.7.0 when that's out, so sooner or later you'll need to correctly calibrate in order to use the A32NX. 

Please feel free to hop into the #support channel on the FBW discord for further help calibrating as it's quicker to get screenshots back and forth and see progress.

**Comment by hickmannick1** [comment]
I done it the calibration a 100 times before the latest update, not been a problem. It's fine, I'll use other aircraft. Thanks for the help though.

**Comment by aguther** [comment]
I just tried today and it seems there are indeed some strange things going on. I didn‘t really calibrate the throttles but when switching between detents it also said it‘s not properly and overlaps, but it‘s the config I use since months without any issues. I have the feeling that maybe in the EFB there might be an issue.

@Saschl Can you take a look at it?

**Comment by hickmannick1** [comment]
Only way I've fixed this is to download the experimental version, calibrate them and save settings. Then download the development version. It's saved the settings from the experimental version thankfully.

**Comment by Saschl** [comment]
Hmm that's indeed weird. I'll look at it

**Comment by MisterChocker** [comment]
The issue that was indeed added by the pr has been fixed, the default range for one detent was oddly wrong.

**Comment by MisterChocker** [comment]
Is this still an issue for you?

**Comment by hickmannick1** [comment]
I believe it's been fixed thank you
