### ISSUE TITLE
FMGC fucntion, "nextwaypoint" 

### ISSUE THREAD

**Issue by K-Border** [flybywiresim/a32nx#5573]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-05T09:19:39+00:00",
  "ref": "merge",
  "sha": "032fbad636c8e3f563c46f907367411bf5ba4066",
  "actor": "wpine215",
  "event_name": "manual"
}
```

### Describe the bug

If you modify the route with the nextway function rather than Direct, it will be twisted like the video below.

### Expected behavior

it was nextway function problem

### Steps to reproduce

1. select fix name "PC631"
2. write and input the next waypoint about "HANUL" fix
3. flight route is twist!

### References (optional)

_No Response_

### Additional info (optional)

[
![Microsoft Flight Simulator Screenshot 2021 08 07 - 01 07 32 72](https://user-images.githubusercontent.com/88470413/128593895-43520603-9ec3-4286-87c9-cdc47179cb8d.png)
](url)

### Discord Username (optional)

K Border#5808

**Comment by Benjozork** [comment]
This is the custom FMS branch, not the development version. Please provide the correct version information.

That being said, we currently do not support the custom FMS branch as it is not meant for general use. This issue is caused by the lack of proper speed prediction + the lack of Type II transitions.
