### ISSUE TITLE
Update version 7 in A320 NX installler stable version used in MFS 2020 update version 1.19.9

### ISSUE THREAD

**Issue by lasoh45** [flybywiresim/a32nx#5844]
### Aircraft Version

Stable

### Build info

```json
MFS 2020 fly by wire A320
```

### Describe the bug

after the update version 7 on 9/18/2021 the following has occurred:

1-no auto pilot button will not press and not activation of the AP
2-no managed air speed 
3-no managed navigation
4-auto throttle wont click on
5-plane will not follow the flight plan

### Expected behavior

I expect you to release a fix or patch to correct this which was working great before the update 7 version 

### Steps to reproduce

by flying the A320 NX

**Comment by Benjozork** [comment]
Hello, we cannot reproduce any of those issues and you have not provided any screenshots or proper reproduction steps.

Please re-open when the issue is properly filled according to the provided instructions, or head to our Discord #support channel for quick assistance. GitHub is more suited for technical bug reports.

**Comment by lasoh45** [comment]
The bugs exist after the versión 7 please fix them !

Javier O Delgado
Certified Business Coach
www.people-too.com
***@***.***

**Comment by Benjozork** [comment]
The build has been thoroughly tested by our QA team and I can confirm none of those issues exist. You may have a corrupted or overridden build.

**Please use our Discord #support channel as GitHub is not meant for user support.**

**Comment by Benjozork** [comment]
I suggest verifying a clean install using this guide:

https://docs.flybywiresim.com/fbw-a32nx/installation/#clean-install-steps

**Comment by lasoh45** [comment]
Thanks I’ve been flying the mod version 6 beautifully even last night with ILS wonderfully and today the installer updates this version 7 and now it’s all screwed up ! 
I will try this link you sent !
Thank You very much !

Javier O Delgado
Certified Business Coach
www.people-too.com
***@***.***

**Comment by lasoh45** [comment]
Did the clean and here are the issues :
1-flickering cockpit lights
2-won’t level off at set level
3-won’t click at AP
4-no managed speeds 
5-no managed nav
6-throttle out if control !

All after version 7 update !

Javier O Delgado
Certified Business Coach
www.people-too.com
***@***.***

**Comment by lukecologne** [comment]
For support please go to our discord server. Most of these issues sound like user error, for example the last one "throttle out of control" sounds like you didn't calibrate your throttles. v0.7 has been tested by our QA team and is confirmed to work fine.

**Comment by lasoh45** [comment]
Luke the throttle has not been adjusted yet . However the other issues are technical system issues I have been flying in version 6 for hundreds of hours ! And all of a sudden version 7 and boom !
No way ! I uninstalled the installer and reinstalled it again sir and eh !
I have to fly the MFS version again !

Javier O Delgado
Certified Business Coach
www.people-too.com
***@***.***

**Comment by Benjozork** [comment]
These are user errors related to your install and as we have asked multiple times, please go to our Discord so we can assist you quickly.

Please do not use this GitHub page for user support. This page is for reporting bugs, and none of the issues you have are bugs with version v0.7

**Comment by sidnov** [comment]
In simple words, 0.7.0 is a drastic improvement over the previous versions that you may have flown for hundreds of hours. We have spent months working on the current stable version and we know what is wrong, what isn't, what is caused by a bad install and what is caused by piloting errors. As Ben mentioned above, please try to reach out for support on our Discord server so the team can take a look, not much that can be done here on this thread.
