### ISSUE TITLE
Add V1, VR, V2 Callouts

### ISSUE THREAD

**Issue by adrianclerical** [flybywiresim/a32nx#5893]
### Aircraft Version

Development

### Description

Please add copilot calls for V1, VR and V2. Thanks.

### Discord Username (optional)

adrianclerical

**Comment by ErikNL80** [comment]
That would be a nice addition!

**Comment by Tuftymeercat37** [comment]
an option to have this would be helpful :-)

**Comment by frankkopp** [comment]
The A320neo does not have these callouts. Therefore they will not be added to the A32NX.

**Comment by Tuftymeercat37** [comment]
Appreciate the A320neo doesn't do the callout but I think we were meaning an option to have the Co-Pilot do the callout. (Similar in principle to the Cabin Crew "Prepare" callouts for Take-off and Landing.

**Comment by adrianclerical** [comment]
My thinking exactly. Does everything really have to be as per the real thing? I'm sure the real aeroplane isn't controlled with a mouse....
I'm sure back awhile someone asked for this feature to be implemented and was told it was being worked on....

**Comment by sidnov** [comment]
> I'm sure back awhile someone asked for this feature to be implemented and was told it was being worked on

@adrianclerical that's correct, we had planned to and is still planned to implement those (probably even being worked on actively, @hotshotp would be the right person answering it). However, it may not be top priority. 

On the contrary, I will have to close this issue since it is a duplicate of another open issue #1558 which can be used to communicate your wishes on the topic of implementing these callouts.
