### ISSUE TITLE
W&B  PAX with BAG PLZ optional

### ISSUE THREAD

**Issue by andrejetcat** [flybywiresim/a32nx#5937]
### Aircraft Version

Experimental

### Description

First of all, a huge thanks for all the awesome features you create for the A32NX!

The W&B feature, especially the syncronize with simbrief is also very helpful and works awesome! 
BUT, is there any chance to make it optional to add the BAG weight to a PAX? 
In todays aviaion not every flight is a holiday-charter with BAGs as many as passengers. Its not unusual that you have a full a320 with only 5 BAGS loaded in the hold. 

So it would be awesome if we can seperate the PAX-weights and the BAG weights to make it possible to select e.g. 143PAX but only e.g. 10 BAGs. which makes a huge difference in weight for this particular flight.

**Comment by sidnov** [comment]
This will be possible only when W/B, payload page is moved to the EFB

**Comment by frankkopp** [comment]
I don't think SimBrief can do this: 
![image](https://user-images.githubusercontent.com/16833201/135629488-16b6cbea-a7bc-4bc8-8ef7-3cd91781bf78.png)

There is only one weight for passengers.

**Comment by sidnov** [comment]
We'll make it manually customisable

**Comment by donstim** [comment]
> I don't think SimBrief can do this: ![image](https://user-images.githubusercontent.com/16833201/135629488-16b6cbea-a7bc-4bc8-8ef7-3cd91781bf78.png)
> 
> There is only one weight for passengers.

Yes, Simbrief can do it. You would simply select 84 kg for the passenger weight, then add 20 kg times however many bags you want to load as cargo weight. That Simbrief solution would, however, not work with the current A32NX Simbrief upload since cargo weight is not included in the upload.

It also would need some juggling to make it work with the PR that is in work as that PR still uses a weight of 84 kg per passenger and 20 kg of bags per passenger regardless of what weight is chosen in Simbrief for the passenger weight.
