### ISSUE TITLE
instale windows 11 y ahora no se visualiza el a320 en fs2020

### ISSUE THREAD

**Issue by DidiCad** [flybywiresim/a32nx#6150]
### Aircraft Version

Stable

### Build info

```json
Instalé windows 11 y ahora no se visualiza el a320 en fs2020
```

### Describe the bug

Instalé windows 11 y ahora no se visualiza el a320 en fs2020 ni el tablero ni el avión por fuera!!

### Expected behavior

Que se visualizara todo del avió A320!!

### Steps to reproduce

Simplemente entré al juego y seleccioné el A320 de Flybyware y no se el avión!!

**Comment by Kimbyeoungjang** [comment]
please use english first.

can you re-install fbw a32nx via installer?

**Comment by igor8518** [comment]
@DidiCad, have you completely reinstalled windows, or have you upgraded from a previous version?

**Comment by ErickSharp** [comment]
Hola, por favor puedes re-instalarlo? Borra el avion de su carpeta Community y re-instalarlo usando el instalador de flybywire.

**Comment by DanyGal84** [comment]
Let me translate this issue for him, since I am having the same trouble.

Describe the bug
I installed Windows 11 and now the A320 in FS2020 entire model does not render neither cockpit or external views. I don't know if the OS has something to do but apparently it is.

Expected behavior
To render and see the entire aircraft.

Steps to reproduce
Just installed via the FlyByWire Installer, launch the simulator, choose the A32NX FlyByWire edition, when the simulation starts everything about the plane is invisible. I tried uninstalling and installing again the aircraft and also tried with the stable and development editions, none of them work.

Attached you will find two screenshots one for inside the cockpit and another from outside, not rendering the aircraft where it should be.

Thank you!

![Microsoft Flight Simulator_2021 11 14-00 18](https://user-images.githubusercontent.com/20543707/141670105-2da88010-017b-49d6-99bf-443d0e3605c8.png)
![Microsoft Flight Simulator_2021 11 14-00 18_1](https://user-images.githubusercontent.com/20543707/141670110-67bc1454-e3f9-47ba-b26c-75cd46d7aa23.png)

**Comment by aguther** [comment]
Not related to Windows 11. Please go to the content manager and uninstall all A32NX you find, exit the sim, use the FBW installer and install it. Then it should be fine.

The issue is caused by the A32NX coming from the marketplace. It seems in certain situations it gets automatically installed.

**Comment by DanyGal84** [comment]
Problem solved!

Yes this is a problem related to having both the marketplace and the community version of the A320NX which is the one installed via the FBW installer.

It's not noticeable since in the aircraft selection menu the aircraft is not repeated or something like that.

Once I uninstalled the marketplace version and only having the community installation, it worked perfectly. I will attach one more screenshot only for reference.

Thank you @aguther for your help!
![Microsoft Flight Simulator_2021 11 14-03 21_1 (2)](https://user-images.githubusercontent.com/20543707/141675662-d435fc5e-1366-4b39-a056-02fe40a24c4f.png)

**Comment by aguther** [comment]
Thank you for the feedback and screenshot!
