### ISSUE TITLE
Thrustmaster tca thrustlevers not working anymore

### ISSUE THREAD

**Issue by nostilp** [flybywiresim/a32nx#6188]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-08T18:43:55+00:00",
  "ref": "v0.7.2",
  "sha": "db3e3d606b3f003adbf16f38ed031fd4a6d85642",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

After i updated to the newest version of the flybywire a32neo when the thrustlevers of the thrustmaster quadrant are on idle, in game they are in climb position making the plane unusable.

### Expected behavior

when thrustlevers on quadrand are on idle position they should be in idle position in game.

### Steps to reproduce

after update to newest version thrustlevers arent working corectly anymore.

**Comment by aguther** [comment]
Have you calibrated your throttles using the EFB?

**Comment by aguther** [comment]
Closed due to inactivity.

**Comment by jfinkel** [comment]
I have the same problem with the Thrustmaster throttle quadrant.  

- I have performed a factory calibration.  The Sensitivity function in MSFS shows that it is calibrated is expected.  
- I have tried to calibrate the Detents via the in-cockpit tablet application, but the graphics show incorrect calibration.  
- The quadrant works perfectly in the Asobo A320.  
- This bug is manifested in both the current Stable and Development versions of A32NX.  

Thanks for your kind attention.
