### ISSUE TITLE
Switch database to clear current flight plan

### ISSUE THREAD

**Issue by krangerich** [flybywiresim/a32nx#6216]
### Aircraft Version

Development

### Description

When you are on the A/C status page, you should be able switch to second and back to first nav data base. Although we only have one DB, this should clear the current flight plan (and stored data). 
This can be used as a quick "hack" (sometimes used IRL as well, I think) if you messed up the flight plan and want to start from scratch.

### References (optional)

![image](https://user-images.githubusercontent.com/7890659/142764863-026ca59e-abcf-4fd9-8873-4e78b86e3c62.png)

**Comment by frankkopp** [comment]
Just insert a new FROM/TO pair on INIT A should reset the flight plan.

**Comment by Maverickwoe** [comment]
Please put me as assignee

**Comment by Maverickwoe** [comment]
Apart from the message that did not disappear after DB switch (investigating in this last bit). Is it what you're looking for ?
https://youtu.be/U_4dnesCaPo

**Comment by Maverickwoe** [comment]
Additional information from BlueberryKing:
"Cycling the database clears the flight plan, weights, fuel data, and FMS position. Only takeoff performance data is retained."

There is no confirmation prompt before switching as far as I know

"Cycling the navigation database deletes the active and secondary flight plans. Do
not cycle it while airborne because doing so will delete the flight plan, eliminate all
speed predictions, and blank the ND. If the aircraft is in managed speed, Green
Dot becomes the speed target."

**Comment by Maverickwoe** [comment]
@BlueberryKing 
Could you please confirm those topics before I make the changes:
1/ What it actually means to the FMS to lose position as the position is mostly given by external systems.
I understand it must behave similarly to losing all ADIRS during flight and switching them back ON = losing the NAV system.
2/ Absence of any form of prompt or Scratch pad message. (It feels really weird due to the consequences it could have on the safety of the plane)

**Comment by BlueberryKing** [comment]
> @BlueberryKing Could you please confirm those topics before I make the changes: 1/ What it actually means to the FMS to lose position as the position is mostly given by external systems. I understand it must behave similarly to losing all ADIRS during flight and switching them back ON = losing the NAV system. 2/ Absence of any form of prompt or Scratch pad message. (It feels really weird due to the consequences it could have on the safety of the plane)

This has been discussed via Discord 🙂.
