### ISSUE TITLE
Cannot Request IFR Clearance/Taxi/Takeoff

### ISSUE THREAD

**Issue by janfredrik** [flybywiresim/a32nx#6247]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-11-24T18:22:00+00:00",
  "ref": "master",
  "sha": "35c9cab4e6e62945c7acd754e1652815937e010d",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

After SU7, I do not get the option to request IFR Clearance from the gate, and thus cannot also get taxi/takeoff clearance.

### Expected behavior

If an IFR flight plan has been created in SimBrief and import was used to pull in an IFR flight plan, the sim should ALWAYS allow Request IFR Clearance at the gate (in the appropriate checklist process).

### Steps to reproduce

1. Choose the A32NX from the World Map function in MSFS.
2. Select a departure airport and gate/parking.
3. Click FLY NOW.
4. Begin power up procedure.
5. Import flight plan from SimBrief
6. INIT and set departure/arrival on FP
7. TCAS ON, Mode Selector: TA/RA

**Comment by killyourradio** [comment]
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/cFMS/#flight-plan-sync-and-msfs-atc

Can you follow these instructions and report back?

**Comment by MStallen** [comment]
Delete all flightplan discontinuity's and then it will work

**Comment by RodneyKoolman** [comment]
Had the same thing. @killyourradio is right. From now on you need to activate the 'Sync' in your FlyPad (Sim options) before you can request IFR Clearance with MSFS ATC.

**Comment by tabramowicz** [comment]
I have the same issue as @janfredrik. I set Sync option to SAVE few days ago (I set it after I checked #6233 ).  My steps are:

1. Choose the A32NX from the World Map function in MSFS.
2. Select a departure airport and gate/parking.
3. Click FLY NOW.
4. Start EFB and check if SYNC is set to SAVE - it's there.
5 .Begin power up procedure.
6. Import flight plan from SimBrief - both in MCDU Menu - AOC and on INIT A page

At this moment I should have option to get IFR clerance but it's not there, only options for VFR flights.
I started using Simple Traffic from Aerosoft not sure if this can somehow interfere. I'll remove it, run above steps once again and let you know.

**Comment by RodneyKoolman** [comment]
It works for me. Do you have the latest update of FBW?
**This is what is working for me:**

- Power up aircraft and turn on FlyPad, wait until aircraft is started
- Sync option in the **FlyPad** set to 'Save'
- Click 'From Simbrief' on the **FlyPad** dashboard and wait for the flight plan to load
- MCDU > ATSU > AOC MENU > INIT/PRES > INIT DATA REQ*
- MCDU > INIT > INIT REQUEST*
- From now on 'Request IFR Clearance' is available in the ATC clearance menu, I just reproduced it.

And of course make sure the airport you are departing from is the same as in your flight plan. Otherwise it won't work.

**Comment by tabramowicz** [comment]
@RodneyKoolman 

Yep I have latest DEV version. Tried your way and still nothing :|

I'll remove FBW and reinstall it as I don't have any other ideas. 

![Zrzut ekranu 2021-11-26 144630](https://user-images.githubusercontent.com/7886985/143590533-dac0c01d-4885-45e4-b25f-a90618c2d5c0.png)

**Comment by RodneyKoolman** [comment]
If you check flight plan on the MCDU? Can you make a screenshot

**Comment by RodneyKoolman** [comment]
I just planned your route in Simbrief (picture on the left) and followed my steps as above. As you can see I am able to now file it. Try my flight plan on the left please and follow my exact steps.

![EGLL_LFBL](https://user-images.githubusercontent.com/24556645/143594358-33aea214-c9f0-45e0-b7f8-774f90c7d3fa.jpg)

**Comment by tabramowicz** [comment]
@RodneyKoolman 

Thanks! I think it's not FBW issue it's something with MSFS or maybe some other mod is breaking this. Just tried A330-900 which is using FBW 0.6 I believe. Different plane and same issue, can't get clerance. Going to clear my community folder and do some more tests. 

Also when I open ATC window I only have one frequency to tune in. I'll check assists settings. SU7 set everything to easy and I set this to Real Life or something like that. 

I think we can close this as in my opinion it's not caused by FBW changes or you can leave it open, I'll do some more tests and let you know.

**Comment by RodneyKoolman** [comment]
Ok no problem, one more thing. I see Heathrow in my ATC title and you see EGLL. Don't know why that difference is there. Maybe something with assist settings indeed.

If you need any help let me know.

**Comment by cchard360** [comment]
Do you only have "Traffic" ATC options? If so you might have this issue: https://forums.flightsimulator.com/t/atc-services-missing-since-su7-e-g-egka-shoreham-airport-no-longer-towered-atc/473597

I had it too. Deleting the fs-base-nav folder and allowing it to be reinstalled fixed it for me.

**Comment by RodneyKoolman** [comment]
> Do you only have "Traffic" ATC options? If so you might have this issue: https://forums.flightsimulator.com/t/atc-services-missing-since-su7-e-g-egka-shoreham-airport-no-longer-towered-atc/473597
> 
> I had it too. Deleting the fs-base-nav folder and allowing it to be reinstalled fixed it for me.

**Good one!** 

"For those who are experiencing this issue, can you try deleting the “fs-base-nav” folder out of Official/OneStore and re-run MSFS. Content Manager should prompt you to download the package again."

**Comment by tabramowicz** [comment]
Thanks @cchard360 @RodneyKoolman - I had to delete Navigraph latest AIRAC Cycle and then it worked - looks like it's corrupted.

I think we can close this issue.

**Comment by janfredrik** [comment]
Deleting the latest AIRAC cycle from Navigraph plus setting sync option in flypad solved it for me aswell!
