### ISSUE TITLE
No copilot avatar in the external view of the aircraft

### ISSUE THREAD

**Issue by TTpilot45** [flybywiresim/a32nx#6264]
### Aircraft Version

Development

### Build info

```json
NA
```

### Describe the bug

No copilot avatar in the external view of the aircraft

### Expected behavior

Copilot avatar in the external view of the aircraft

### Steps to reproduce

Selecting the aircraft and placing at any airport 

### References (optional)

NA

### Additional info (optional)

NA

**Comment by Barnes62** [comment]
On current development version, I am actually unable to see either of the pilots from the exterior view

**Comment by A320PHX** [comment]
That's weird., I am just missing co pilot for me on latest dev.

**Comment by kdullabh** [comment]
Same here cant see both of them, must have packed up and gone on leave.

**Comment by Barnes62** [comment]
![Screenshot 2021-11-30 183657](https://user-images.githubusercontent.com/72352800/144145278-4491201f-ad7f-46ff-a3e5-19d2a521fc26.jpg)

**Comment by A320PHX** [comment]
The weird thing is, I just did another flight, and I had both pilots... Very strange. I have never had no pilots though.

**Comment by kdullabh** [comment]
I reinstalled the FBW installer, same issue. Is anyone else having the same problem?

**Comment by Barnes62** [comment]
I have found the problem that is affecting me with regards to this issue. There are some differences in the "Weight_and_Balance" section of the flight_model.cfg files of the stable version and the dev version. 

In the stable version (with pilots visible) the flight_model.cfg file has a section of Weight_and_Balance that looks like this:

max_number_of_stations = 10 ; Number of payload stations
station_load.0 = 185, 42.36, 0, 0, PILOT, 1
station_load.1 = 185, 42.36, 0, 0, FIRST OFFICER, 2
station_load.2 = 3300, 21.98, 0, 0, ECONOMY ROWS 1-6 (seats: 36 max: 6670lbs/3024kg), 0
station_load.3 = 3850, 2.86, 0, 0, ECONOMY ROWS 7-13 (seats: 42 max: 7780lb/3530kg), 0
station_load.4 = 4400, -15.34, 0, 0, ECONOMY ROWS 14-21 (seats: 48 max: 8880lb/4032kg), 0
station_load.5 = 6600, -32.81, 0, 0, ECONOMY ROWS 22-29 (seats: 48 max: 8880lb/4032kg), 0
station_load.6 = 3300, 18.28, 0, 0, FWD BAGGAGE/CONTAINER (max: 7500lb/3402kg), 0
station_load.7 = 2650, -15.96, 0, 0, AFT CONTAINER (max: 5350lb/2426kg), 0
station_load.8 = 2200, -27.10, 0, 0, AFT BAGGAGE (max: 4650lb/2110kg), 0
station_load.9 = 1650, -37.35, 0, 0, AFT BULK/LOOSE (max: 3300lb/1497kg), 0

In the latest dev version, the same section looks like this:

max_number_of_stations = 8 ; Number of payload stations
station_load.0 = 3300, 21.98, 0, 5, ECONOMY ROWS 1-6 (seats: 36 max: 6670lbs/3024kg), 0
station_load.1 = 3850, 2.86, 0, 5.1, ECONOMY ROWS 7-13 (seats: 42 max: 7780lb/3530kg), 0
station_load.2 = 4400, -15.34, 0, 5.3, ECONOMY ROWS 14-21 (seats: 48 max: 8880lb/4032kg), 0
station_load.3 = 6600, -32.81, 0, 5.5, ECONOMY ROWS 22-29 (seats: 48 max: 8880lb/4032kg), 0
station_load.4 = 2800, 18.28, 0, 0.9, FWD BAGGAGE/CONTAINER (max: 5600lb/2540kg), 0
station_load.5 = 1950, -15.96, 0, 1, AFT CONTAINER (max: 4000lb/1815kg), 0
station_load.6 = 1700, -27.10, 0, 1.2, AFT BAGGAGE (max: 3500lb/1585kg), 0
station_load.7 = 1300, -37.35, 0, 1.4, AFT BULK/LOOSE (max: 2750lb/1245kg), 0

As you can see in the dev version, the number of stations has been reduced by two and the pilots' stations have been removed. Consequently, the pilots do not show in the cockpit from external view. 
I changed the station number back to 10 and added the pilots section in flight_sim.cfg (at stations 8 and 9, so that if something like simbrief need to modify 0 thru 7, they will be unaffected) and the pilots have now re-appeared. The same section of flight_sim.cfg now looks like this:

max_number_of_stations = 10 ; Number of payload stations
station_load.0 = 3300, 21.98, 0, 5, ECONOMY ROWS 1-6 (seats: 36 max: 6670lbs/3024kg), 0
station_load.1 = 3850, 2.86, 0, 5.1, ECONOMY ROWS 7-13 (seats: 42 max: 7780lb/3530kg), 0
station_load.2 = 4400, -15.34, 0, 5.3, ECONOMY ROWS 14-21 (seats: 48 max: 8880lb/4032kg), 0
station_load.3 = 6600, -32.81, 0, 5.5, ECONOMY ROWS 22-29 (seats: 48 max: 8880lb/4032kg), 0
station_load.4 = 2800, 18.28, 0, 0.9, FWD BAGGAGE/CONTAINER (max: 5600lb/2540kg), 0
station_load.5 = 1950, -15.96, 0, 1, AFT CONTAINER (max: 4000lb/1815kg), 0
station_load.6 = 1700, -27.10, 0, 1.2, AFT BAGGAGE (max: 3500lb/1585kg), 0
station_load.7 = 1300, -37.35, 0, 1.4, AFT BULK/LOOSE (max: 2750lb/1245kg), 0
station_load.8 = 185, 42.36, 0, 0, PILOT, 1
station_load.9 = 185, 42.36, 0, 0, FIRST OFFICER, 2

Not sure if this adversely affects something new in the FBW code, but at least it does show where the problem with the disappearing pilots lies.

**Comment by donstim** [comment]
Thanks for the report. We are investigating a fix.

**Comment by kdullabh** [comment]
Thanks for the update..

**Comment by Tibu73-ui** [comment]
Thanks, I have the same issue.
