### ISSUE TITLE
[BUG] A/THR does not maintain speed after engine failure

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#641]
**Mod Version**

master

**Describe the bug**

After engine failure, A/THR reduces remaining engine thrust to idle when failed thrust lever is retarded. This occurs regardless of A/THR mode (SPEED etc). 

**To Reproduce**

1. Fail one engine. 
2. Following ECAM, retard that thrust lever. 
3. A/THR remains in SPEED but remaining engine spools down to idle. 

**Expected behavior**

A/THR should keep speed with remaining engine. Thrust should not drop. 

**Actual behavior**

Thrust reduces to idle on remaining engine. 

**References**

**Additional context**

During engine failure, LVR MCT should also display on FMA.

**Comment by PCGamesF1Tech** [comment]
Hi,
which takeoff thrust setting did you use? 
If TOGA:
It should stay in TOGA until shortly before reaching green dot speed during acceleration and pulling OPEN CLIMB. Then it should ask for LVR MCT as the lever is still in the TOGA notch. 

If FLX/MCT:
If you didn't advance to TOGA after stabilization (for better climb performance) the lever is already in the MCT notch (FLX/MCT) from Takeoff. So there shouldn't be a message asking for LVR MCT.

**Comment by toffee2000** [comment]
It occurs both during takeoff and in other phases like cruise.

**Comment by PCGamesF1Tech** [comment]
Well, in cruise you should disengage A/THR and put the levers to MCT.
Otherwise with the A/THR active (SPEED) and selecting OPEN DES for a required descend (if above max alt for one eng out) the A/THR would command idle thrust which is not wanted (the A/THR range now goes to MCT with one eng out).
You want a shallow descent with the remaining engine at MCT thrust (fixed).
Of course you have to engage A/THR later on in a safe altitude with enough thrust available for a "normal" continuation of the flight (with SPEED mode and thrust rsnging from idle to MCT)

**Comment by toffee2000** [comment]
But when SPEED is engaged, A/THR should maintain speed right? Not spool back?

**Comment by PCGamesF1Tech** [comment]
Yes, I think you are right.
Given "cruise" at 5000ft (low altitude) with one eng out and A/THR engaged in SPEED it should hold it. 
Where's the bug? (the speed bug of course!) 😉

**Comment by toffee2000** [comment]
Bug at 250 kt. Speed drops to VLS.

**Comment by PCGamesF1Tech** [comment]
Yeah that's a bit slow... 😱

**Comment by toffee2000** [comment]
Selected, but as you said, it shouldn't matter.
