### ISSUE TITLE
Wider Throttle Quadrant Support

### ISSUE THREAD

**Issue by david-st** [flybywiresim/a32nx#6457]
### Aircraft Version

Development

### Description

I currently have & use the Winwing Orion throttle quadrant - for both FS2020 and DCS World (Obviously purchased for DCS World first), but I've been flying the MS series of flight sims since the mid-80s.

I would like to request that a wider range of throttle quadrant calibration proceedures be promulgated please? I'm at a loss as to how to correctly calibrate my Orion throttle for the A320.  The manual process has done my head-in!  Doesn't work at all.
My throttle has a reverse thrust section built into it - seems to activate a couple of buttons but in the A320 it goes from zero throttle to full reverse imediately.  Doesn't go to idle reverse at all.  None of the other throttle sections (eg. Flex, Go-Around etc.) appear to be recognised at all.
I also use this throttle in conjunction with the VKB Gladiator NXT premium - an excellent joystick with amazing programmability and I highly recommend it.  But I don't use the throttle on it as its a little too simplistic for the A320 (Probably its only poor feature).

If anyone has a solution to this I'm all ears.   

Thanks in advance.

Regards,

David

**Comment by ShadowFrost3** [comment]
Do you mean this throttle? 
![image](https://user-images.githubusercontent.com/87394534/147843572-5a45679a-ee34-490a-badc-d19cec02eee6.png)

**Comment by david-st** [comment]
Yep,
Thats the one.
:-)

**Comment by ShadowFrost3** [comment]
So the first thing support would probably ask is that you've viewed this document. 
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flyPad/throttle-calibration/#microsoft-flight-simulator-control-options

If you hop on discord I could walk you through it and quicker diagnose where an issue is otherwise I think you need to read the above. I don't see any reason why your throttle would have issues but then again I don't have your version. But I do have a similar, high quality HOTAS for DCS and have no issues using it. Virpil T-50CM for reference.

**Comment by frankkopp** [comment]
If MSFS supports the controller then the A32NX does and you should be able to calibrate it. It has nothing to do with the actual hardware as long as MSFS recognizes one or two valid axis inputs. 

Please close this issue.
