### ISSUE TITLE
Add "Boarding complete" sound

### ISSUE THREAD

**Issue by foxmike80** [flybywiresim/a32nx#6492]
### Aircraft Version

Experimental

### Description

When using the "boarding function" in the AOC of the MCDU, boarding can no longer be observed by watching the GW value increase in the ECAM. GW is - correctly - no longer displayed before engine start. It would be helpful if a "Boarding complete" audio would be played (similar to the "be seated for departure" announcement before takeoff) once the boarding process is finished.

### Discord Username (optional)

foxmike1080

**Comment by donstim** [comment]
This is planned.

**Comment by ACSoft47** [comment]
Attention ! It must be optional, because of the potential conflict with "FS2Crew: Flight Crew"  addon.

By the way, to my humble opinion, this simulation of the boarding duration in the AOC of MCDU was a bad move. This has nothing to do with an aircraft MCDU. Therefore, this page should just allow to set, INSTANTLY ONLY, the PAX & Cargo, in replacement of original sim page. It is already indicated in the official doc, that the option on tablet, for this "simulation", must be set to "instantly", if the flight start on the runway, ready to, or already in flight. So, please, make this page a specification of PAX & Cargo instead of a boarding simulation.

**Comment by donstim** [comment]
@hotshotp can confirm, but it is my understanding that the announcements will be optional.

The boarding simulation is being moved to the EFB. Until then, you can always set the boarding rate to instant if that is your preference.

**Comment by MStallen** [comment]
I use A32NX_PAX_TOTAL_ROWS_1_6 and A32NX_PAX_TOTAL_ROWS_1_6_DESIRED and play a boarding complete message once when they are equal and not zero. This within FSUIPC together with VB6

**Comment by westlakem** [comment]
I use "Self Loading Cargo" for my passenger simulation, and have never used the AOC bording feature.  I'm pretty sure those would conflict.

**Comment by ErickSharp** [comment]
@hotshotp Want to append this to the list of issues on your PR that are closed out on merge?
