### ISSUE TITLE
A32NX latest Dev version cannot enter the game after updating MSFS update 7

### ISSUE THREAD

**Issue by dc1ps2** [flybywiresim/a32nx#6655]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-05T20:38:28+00:00",
  "ref": "master",
  "sha": "eca318c76ae5dec67ee8161039e87f7afc6b1655",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

Since installing MSFS version 1.22.2.0, I have been unable to play games with the A32NX mod. It's been stuck on the reading screen and has been unresponsive for hours. I tried uninstalling and reinstalling the A32NX, even removing all addons from the community, leaving only the A32NX, but I still can't enter the game, but if you use other aircraft mods, you can enter.

![image](https://user-images.githubusercontent.com/11674129/152669552-b51b502b-68a8-475f-9589-99a925f6bcf9.png)

![image](https://user-images.githubusercontent.com/11674129/152669549-a4312a55-ba28-4097-94bd-5ac807740d6a.png)

![image](https://user-images.githubusercontent.com/11674129/152669571-9e91d526-186b-4c53-b36a-d104aaba7776.png)

### Expected behavior

N/A

### Steps to reproduce

N/A

**Comment by MrSmithers165** [comment]
Problem solved for me:

I had installed the Development version from Installer and the version at Marketplace simultaneously- there was a small update in Marketplace about 2 weeks ago which i agreed to install. Exactly since then it got stuck in loading screen. Now i deleted the version of Marketplace and the version from Installer and reinstalled the development version from Installer- works again.

Conclusion:
Do not use the Installer and Marketplace version together- i didn´t know that. Marketplace is only stable version and i guess when installing any other version of the Installer it comes to such conflicts.

**Comment by kilocharlie1** [comment]
I'm having the same issue, except I haven't installed it from the marketplace, I installed it from the installer

**Comment by derl30n** [comment]
If the issue still persists please open a new issue report.
