### ISSUE TITLE
autopilot speed, vs and heading selector no function

### ISSUE THREAD

**Issue by toppilot92** [flybywiresim/a32nx#6664]
### Aircraft Version

Development

### Build info

```json
not sure
```

### Describe the bug

Main autopilot has no function wont allow to use heading vs or speed has no function.

### Expected behavior

to operate according to function

### Steps to reproduce

when starting to use aircraft

**Comment by BlueberryKing** [comment]
Alright, are the dials you are trying to use turning blue when you try to click them? Then this might resolve your issue: https://docs.flybywiresim.com/fbw-a32nx/settings/#legacy-cockpit-interaction-system

If this doesn't help you, could you take some screenshots, so we can see what's going on?

**Comment by toppilot92** [comment]
nothing still the same

**Comment by aguther** [comment]
Well, that way we can't help you. Please provide videos/screenshots and a more detailed description. Even better join Discord and go for the support channel which allows more direct communication.

**Comment by DarthJahus** [comment]
@toppilot92, when you set speed, do you pull on the knob to validate your selection?

**Comment by toppilot92** [comment]
yes i do its the auto throttle wont respond. The speed indicator selection dont move when i turn knob.

**Comment by aguther** [comment]
Can you make a video and share it here? You can just upload it to GitHub, then it’s easier to see what happens.

Sorry to say but with very high probability a pilot error.

**Comment by toppilot92** [comment]
ok i will make video tonight... just opening up msfs

**Comment by D33pfield** [comment]
You may not have cockpit interaction system set to legacy. If this is the case, the knobs require you to use middle mouse button while holding the knob. (Hold left mb on knob then press middle mouse button)

**Comment by toppilot92** [comment]
i have legacy on sir

**Comment by toppilot92** [comment]
https://streamable.com/ppam0s here is short clip

**Comment by BlueberryKing** [comment]
In order to select a speed, you have to pull the knob, this means pressing on the lower half of it, you should see an arrow pointing down when you hover over it :)

**Comment by toppilot92** [comment]
the pink pointer wont move up or down on speed indicator

**Comment by BlueberryKing** [comment]
I am talking about the knobs on the FCU, the panel where you give commands to the autopilot. After you rotate the speed dial to the desired position, you have to make sure to actually press it on the lower half to set the speed.

You have to press on the lower half of the knob to do this.
![image](https://user-images.githubusercontent.com/22713769/153293829-3de0230f-987c-41f2-b91b-075bcaa25bff.png)

P.S Make sure your thrust levers are in the CLB detent, so the ATHR is active. In the video, they are too far forward so the ATHR is not active. You won't get the airplane to fly at your selected speed without the autothrust.

**Comment by toppilot92** [comment]
its not working its a bug for sure

**Comment by aguther** [comment]
No, it's a pilot error.

**Comment by aguther** [comment]
> https://streamable.com/ppam0s here is short clip

Ok, I tell you what I see:

1. The ATHR is armed but not active because the thrust levers are above CLB detent -> constant N1.
2. Then you disengage the ATHR by putting your thrust levers to idle.
3. Then you engage the ATHR again
4. You put your levers again above CLB detent (see point 1)
4. You dial the FCU Speed knob while the mode is managed, to use the speed you dial you need to pull the knob

Other observations:
- you put your thrust levers to TOGA while you had flaps out, therefore you're in GA TRK for lateral mode
- you engaged the AP while you have been more than 250 ft from the FCU target altitude

Recommendations:
- calibrate your throttles properly
- Learn how to use and fly the plane: https://docs.flybywiresim.com/pilots-corner/

See especially point 3:
![image](https://user-images.githubusercontent.com/6629914/153296690-aff43dff-f7b7-474e-ac95-675e1ef8296a.png)

https://mms-safetyfirst.s3.eu-west-3.amazonaws.com/pdf/safety+first/the-golden-rules-for-pilots.pdf
