### ISSUE TITLE
Message "MAP PARTLY DISPLAYED" on the ND

### ISSUE THREAD

**Issue by UNSCJohn-117** [flybywiresim/a32nx#6851]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-04T22:04:01+00:00",
  "ref": "experimental",
  "sha": "15ccf80f89451ef6efc97c2dbf9bcd1d04796211",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:15ccf80f"
}
```

### Describe the bug

The ND is giving the message "MAP PARTLY DISPLAYED" at the bottom in amber where it should say "GPS PRIMARY"

![Microsoft Flight Simulator 3_4_2022 8_19_05 PM](https://user-images.githubusercontent.com/54257824/156866976-0b8bc37b-ef78-4069-a66f-7240a3ed9891.png)

### Expected behavior

Text should display "GPS PRIMARY" in white

### Steps to reproduce

1. Start any flight (my flight was from CYYZ-EGLL)
2. Setup the aircraft as normal
3. Takeoff as normal

### Discord Username (optional)

John-117#1457

**Comment by Benjozork** [comment]
The message appears for a reason. Usually a corrupted flight path due to LNAV bugs.

I suggest you try to reproduce this using the same procedures and seek help on our Discord, where we can immediately ask for the relevant screenshots of your approach. I assume you can't take those anymore.

Gonna close as this isn't really a correct report. Will reopen and rename if information about the approach is provided.

**Comment by UNSCJohn-117** [comment]
I think I see what you mean now. Is it the curve after the last waypoint in the STAR?

![2022-03-04](https://user-images.githubusercontent.com/54257824/156867324-70522a29-7fe8-4e93-bdac-9458f2bbd1be.png)
w

**Comment by Benjozork** [comment]
Yes. I'll look into this approach.
