### ISSUE TITLE
IDG fault light not illuminating after IDG disconnect

### ISSUE THREAD

**Issue by Hummel199** [flybywiresim/a32nx#6956]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-22T13:57:19+00:00",
  "ref": "experimental",
  "sha": "adb0a938e63e88a3095da1ca5010c8a0c6413a54",
  "actor": "BlueberryKing",
  "event_name": "manual",
  "pretty_release_name": "experimental:adb0a938"
}
```

### Describe the bug

After the IDG disconnect button is pushed the fault light on the IDG push button does not illuminate. Fault light on GEN does illuminate.
![image](https://user-images.githubusercontent.com/21021532/159556877-7e337cb3-8cac-494c-aea2-67371f8ac6a4.png)

IDG is disconnected in Elec Page.
![image](https://user-images.githubusercontent.com/21021532/159557006-42febd0c-8fc8-4b7b-919a-bccb3e19891d.png)

I know that the ECAM messages aren't implemented yet, so I don't know if that will follow along with the FWC.

### Expected behavior

Fault light on IDG push button should illuminate after pressing.

### Steps to reproduce

1. Start Engines
2. Open IDG 1 or 2 guard and push the button.

**Comment by tracernz** [comment]
Experimental is not supported. If you can reproduce the issue in dev/master please update the build info.

**Comment by derl30n** [comment]
Closing since no response from op.

**Comment by davidwalschots** [comment]
Currently there's no code that manages the IDG FAULT light. I do doubt that the change requested in this issue is correct, as amber FAULT indications are used to get the pilot to press a button. I think the FAULT light on the IDG pb comes on when oil outlet temperature > 180 degrees celsius _or_ oil pressure is low and engine N2 > some percentage.

CC: @komp1821
