### ISSUE TITLE
Autopilot is unresponsive/lazy on cruise (wrt. speed and altitude)

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/a32nx#6964]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-24T17:31:46+00:00",
  "ref": "master",
  "sha": "cdb1a6281a8da541cbce47ff45fd5edf66fccb08",
  "actor": "RichardPilbery",
  "event_name": "manual",
  "pretty_release_name": "master:cdb1a628"
}
```

### Describe the bug

On cruise the speed and/or altitude of the plane can drift considerably from the setting. LNAV is not affected.
Changing the selected speed and/or altitude back and forth kicks the autopilot/autothrust back to live.

### Expected behavior

Speed/altitude to stay within limits

### Steps to reproduce

1. Cruise at a certain level
2. Wait for a bit (weather helps) until the speed and/or altitude has drifted significantly

### References (optional)

Letting the AP do it's thing, the speed gets below 0.78 whilst 0.79 is selected whilst the altitude also gets to about 50ft below what is selected: https://www.twitch.tv/videos/1435505521?t=00h44m30s

**Comment by tracernz** [comment]
The 50 feet is a feature of the real aircraft... it will allow the altitude to drift in cruise within a ±50 feet band to correct the speed rather than changing the power setting constantly... it seems to not be working properly here though.

**Comment by aguther** [comment]
As mentioned before the SOFT ALT mode is an actual mode of the real aircraft. It limits the authority of the A/THR to keep engines stable (improves maintenance and fuel costs). The SOFT ALT mode is disengaged due to speed variation when delta > 4 kts during 10 s or > 10 kts during 4 s. So quite a good amount of delta is needed.

I've pushed a potential improvement for the engagement situation to experimental version, the authority of A/THR is no longer just removed but smoothly blended which I hope will improve situations when gusty.
