### ISSUE TITLE
You locked the thread so here you have it.

### ISSUE THREAD

**Issue by Shituation** [flybywiresim/a32nx#7039]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-01-08T01:22:50+00:00",
  "ref": "v0.7.4",
  "sha": "5adc0dc1ee3bd9cf9386c312b798a5f8ca7b391b",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug
https://github.com/flybywiresim/a32nx/issues/7007#issuecomment-1094306034
@sidnov
![image](https://user-images.githubusercontent.com/43975882/162629633-f1e8dc10-8043-4aa7-a454-49292f6c70da.png)

Who are these "other organizations" and why do you have to report "statistical information" about "your users".
What marketing purposes?
Why do you need statistics of users using your software if this is all a free time project? 
You probably don't care about identifying users, you just sell the bulk of data to "other organizations".

### Expected behavior

111

### Steps to reproduce

111

### References (optional)

111

### Additional info (optional)

111

**Comment by Benjozork** [comment]
We don't sell any information to anyone. This is a warning provided to cover cases where we use third-party analysis tools such as sentry.io to log errors. This is done with full user consent and if the code runs, then you have **consented** to it. We have never required anyone to use our software, or use online features for our software, and have always made them opt-in.

If your concern is limited to server costs, you can view our transactions on our [OC](https://opencollective.com/flybywire). We use discord as it provides an instant messaging platform for our users to receive assistance with the aircraft, developers to discuss the project and a space to share progress with our community. We don't receive any personal data from Discord, and we don't enforce it's use. But of course, if you want to report errors in an informal way, then we ask to use Discord since GitHub is not concieved for this kind of long-term discussion. Alternatively, our social media DMs can be used.

Any concerns regarding Discords privacy agreement that you don't find clarified in their agreement can be raised with them, that's not related to this project.

Our code is open source, free for all to inspect. If you have concerns about the data collected (with **consent**) then you can make a politely worded, simple statement of which data is of concern to you. Until then, you will be blocked from this organization because the lash-out type of reporting is simply not accepted here.

For your information, you can view the GitHub Privacy Policy, which gives the website way more freedom than we ever asked from you, at this link: https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement#how-github-uses-your-information
