### ISSUE TITLE
Dev Upd 4c7685a Throttle not working

### ISSUE THREAD

**Issue by cind12** [flybywiresim/a32nx#7063]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-16T00:09:23+00:00",
  "ref": "master",
  "sha": "4c7685a20e6ef72329c2a997758dd14b61905c10",
  "actor": "derl30n",
  "event_name": "manual",
  "pretty_release_name": "master:4c7685a2"
}
```

### Describe the bug

Throttle is always on reverse trust. When you try to calibrate them its not possible due to rolling back to revers trust

### Expected behavior

Throttle should work as expected

### Steps to reproduce

A32nx Dev mode 
LMPA
throttles not responding properly

### Discord Username (optional)

cind12

**Comment by Benjozork** [comment]
Does the axis move properly (without going into reverse) in the MSFS controls settings ?

**Comment by Benjozork** [comment]
Also please provide appropriate info.. what throttle is it ?

**Comment by cind12** [comment]
> Does the axis move properly (without going into reverse) in the MSFS controls settings ?

Yes in control settings throttle works perfectly



> Also please provide appropriate info.. what throttle is it ?

tca thrustmaster airbus edition
Before todays update the plane was working properly on previous build

**Comment by Benjozork** [comment]
There was no changes to calibration in months so the issue is local.

Make sure to go through the guide **completely**: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flyPad/throttle-calibration/#introduction

If you follow every step, calibration will work.

I also recommend using our Discord for support requests like these.
