### ISSUE TITLE
isis: arrow symbols missing from font

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/a32nx#7129]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-04-30T05:58:36+00:00",
  "ref": "HEAD",
  "sha": "b2d7668d7dcbef695cf7462635c9800234b5967c",
  "actor": "Andreas Guther <andreas@guther.family>",
  "event_name": "manual",
  "pretty_release_name": "master:b2d7668d"
}
```

### Describe the bug

Since https://github.com/flybywiresim/a32nx/pull/6009 the arrow symbols used on the bugs page have been missing.

Before:
![image](https://user-images.githubusercontent.com/9995998/166093645-eed0f65e-427a-44ac-a3e9-63b0d82d3748.png)
After:
![image](https://user-images.githubusercontent.com/9995998/166093651-75119539-9cfe-4c4b-9dde-a6bb61683d72.png)

### Expected behavior

Arrows to be visible.

### Steps to reproduce

1. Go to bugs page on ISIS.

**Comment by ErikNL80** [comment]
Can reproduce the issue here with latest DEV as well.

**Comment by tracernz** [comment]
The ISIS is using the ECAM font... it's possible a temporary ISIS font could be created and these characters could be created in it, or wait until ongoing work on a complete ISIS font is ready.

**Comment by aweissoertel** [comment]
Hi, I would be interested in fixing this one as my first issue :)
Just confirmed that this Bug is still there.
From what I can see in the code, the arrow is there
```tsx
<text x={150} y={450} className="TextCyan">SET/SELECT→</text>
```
but the used font `/fonts/ECAMFontRegular.ttf` does not have these arrow symbols (&#x2191 and &#x2192), as @tracernz suggested:
![image](https://user-images.githubusercontent.com/57036035/178157375-4b98fa6c-3e26-4fbc-ba35-c6803fd70979.png)
So I could either put in 2 small svg's or try to somehow include the arrows from another font (maye `HoneywellMCDU.ttf`?).
Any feedback would be highly appreciated

**Comment by sidnov** [comment]
> So I could either put in 2 small svg's or try to somehow include the arrows from another font (maye `HoneywellMCDU.ttf`?).
> Any feedback would be highly appreciated 

There are plans to entirely redo the standby instrument fonts at some point. In the meantime, it would be fine to add the missing symbols to the ECAM fontstyle itself with a to-do note on the main ISI code
