### ISSUE TITLE
Auto Brake Max is not activated in Ready for Taxi or Ready for Takeoff preset.

### ISSUE THREAD

**Issue by Yucareux** [flybywiresim/a32nx#7272]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-06-02T19:33:02+00:00",
    "ref": "refs/heads/master",
    "sha": "0d2a31e44033babb50970db9e164ea6769deaeb3",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:0d2a31e4"
}
```

### Describe the bug

When loading a preset, in this case Ready for Taxi and Ready for Takeoff, AUTO BRAKE MAX is not activated.

### Expected behavior

AUTO BRAKE MAX should be activated in either of these two presets.

### Steps to reproduce

Go to FlyPad (OS 3)
Prepare the plane until reaching the Ready for Taxi or Ready for Takeoff phase.
When activating either of the two presets, it will appear momentarily that the Auto Brake Max is being activated, but it is not.

### References (optional)

https://youtu.be/REja5Tr2cTU

### Discord Username (optional)

yucareux#9939

**Comment by auroraisluna** [comment]
This can be added here: https://github.com/flybywiresim/a32nx/blob/master/src/flypad-backend/src/Aircraft/AircraftProcedures.h

Just need to find the variable for auto brake now

**Comment by donstim** [comment]
A32NX_AUTOBRAKES_ARMED_MODE_SET=3

**Comment by Konata400** [comment]
Autobreak max is in the line 129 on TAXI_CONFIG_ON
on https://github.com/flybywiresim/a32nx/blob/master/src/flypad-backend/src/Aircraft/AircraftProcedures.h

And Spoiler Disarm in line 130 have the same problem is not duplicated on TAKEOFF_CONFIG_ON

The question is that maybe the developers want you to go through all the procedures before takeoff, otherwise they would have to add Autobreak MAX and Spoiler Disarm in TAKEOFF_CONFIG_ON

Before changing anything I prefer to ask [ErickSharp](https://github.com/ErickSharp)

**Comment by frankkopp** [comment]
> The question is that maybe the developers want you to go through all the procedures before takeoff, otherwise they would have to add Autobrake MAX and Spoiler Disarm in TAKEOFF_CONFIG_ON

No - all procedure are done sequentially - so if you directly choose "Ready for Taxi" the procedures before that are also executed. Same is backwards when shutting down. 

I will look into the AUTOBRAKE - this not working would have a different reason. 
(the variable has changed as far as I can see)
