### ISSUE TITLE
[BUG] Severe pitch up when autopilot is engaged

### ISSUE THREAD

**Issue by joniatus** [flybywiresim/a32nx#732]
**Mod Version**

Master

**Describe the bug**

Severe pitch up when autopilot is engaged

**To Reproduce**

1. Take off as normal
2. At thrust reduction altitude move lever to CL
3. Engage selected speed (I used 230)
4. Engage open climb
5. Engage autopilot

**Expected behavior**

Autopilot should pitch up at climb thrust and maintain selected speed

**Actual behavior**

Plane will pitch straight up and stall.
However, if you wait long enough before engaging autopilot, the flight directors will eventually come down to ~10° and then autopilot can safely be engaged. From takeoff until a seemingly random time/altitude flight directors are at 20+ degrees pitch up.

**References**

**Additional context**

I experienced this with default A320 since the patch as well

Discord username (if different from GitHub):
@Getterup Diaz

**Comment by joniatus** [comment]
Last couple of flights it hasn't done this (started c&d). When this bug occured were from runway starts so may be related

**Comment by nabil74** [comment]
Reproduced on last flight during takeoff as per original post.

**Comment by ferics** [comment]
I just did a takeoff in Heathrow runway 09L and the pitch is insane (this happened before checking this thread). So I am assuming it is the same issue I am experiencing it here too.

**Comment by Venorcis** [comment]
Just had this happen to me as well, though a few times before it didn't. Not sure what exactly causes this.

**Comment by 2hwk** [comment]
Investigate if this issue is linked with https://np.reddit.com/r/MicrosoftFlightSim/comments/iw6mis/plane_exorcisms_or_how_i_seem_to_have_reduced_or/

**Comment by Venorcis** [comment]
> Investigate if this issue is linked with https://np.reddit.com/r/MicrosoftFlightSim/comments/iw6mis/plane_exorcisms_or_how_i_seem_to_have_reduced_or/
> 
> (half doubt it, but worth a shot)

Interesting, reading the post it also seems closely tied to #722

**Comment by AdenFlorian** [comment]
I have experienced this issue, but not sure if linked to the ghost plane stuff. I'll probably look more into this today.

**Comment by speedwaystar** [comment]
the AP referencing the wrong (AI driven) plane would absolutely explain some of the issues i've had with multiple aircraft, including the AP pitching wildy up, down, and +45 degree angles of bank, literally as if the damn thing were possessed.

**Comment by KozziOS** [comment]
I'm also having this problem

**Comment by speedwaystar** [comment]
after turning off ai ground traffic and testing in multiple flights over many hours, I can confirm that it makes the AP weirdness completely go away.

**Comment by veikkos** [comment]
> 
> 
> after turning off ai ground traffic and testing in multiple flights over many hours, I can confirm that it makes the AP weirdness completely go away.

I have "Ground Aircraft Traffic" as 0 and issue persists for me. I'm testing at EFHK 04L and I have High Altitude plan to ESSA through ADIVO if that matters. I'm starting from runway and just disable parking brake and go. Issue did not persist when I was testing from RWY 15.

`this.setAPManagedSpeed(speed, Aircraft.A320_NEO);` is constantly correctly applied to V2 + 10. Don't know why it still doesn't work but I'm guessing native side issue since I have not had this problem prior 1.8.3.0.

If anyone has ideas which variables to print and track, I'm all ears and can do more testing. Debugging by others might be needed.

**Comment by rizal72** [comment]
After many tests, I can say that this issue is related to FD (Flight Director): immediately after take off, the FD pitch line suddenly steps up like double of where it should be. If you disengage FD and then immediately engage it again, the FD pitch indicator line goes back to where it should be, making the pitch more consistent and delicate.
So if you have to look, look at the FD code, it seems to me that pitch calculates two times, causing the pitch to spike up.

Cheers

**Comment by MisterChocker** [comment]
this has been improved by game updates
