### ISSUE TITLE
MCDU some ILS not displayed 

### ISSUE THREAD

**Issue by patmack14** [flybywiresim/a32nx#7555]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-10-15T23:17:34+00:00",
    "ref": "refs/heads/master",
    "sha": "e7c669c5ea31d8c333ab83193d3aba4fdf4c887f",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:e7c669c5"
}
```

### Describe the bug

Flew into CYVR (26R) and EHAM(18R) ILS are not displayed as choices on approach page.  I first noticed this at KMSP(previous issue) where not all SID were being displayed but it seems to be growing problem.  (NON NAVIGRAPH)

I can say for certain that EHAM 18R was showing up as recently as 2 months ago.  

### Expected behavior

All available ILS Approaches should be displayed for a given airport. 

### Steps to reproduce

1.Fly into EHAM OR CYVR 
2. 18R(EHAM) , 26R(CYVR) ILS are not displayed as choices. 

### Discord Username (optional)

@PATM

**Comment by Benjozork** [comment]
Can you choose those from the main menu ?

If not, this is an MSFS issue.

**Comment by tracernz** [comment]
With navigraph:
![image](https://user-images.githubusercontent.com/9995998/196111257-8c1a584e-e1ab-4d41-8881-7acb3bd6f23d.png)
![image](https://user-images.githubusercontent.com/9995998/196111341-6087a6db-5920-49ae-bdeb-62c15f47644a.png)

With default data:
![image](https://user-images.githubusercontent.com/9995998/196112980-969d2321-93f1-4c58-97d0-7ca20b304d1f.png)
![image](https://user-images.githubusercontent.com/9995998/196113057-594fb536-d5c9-4890-8114-494051efc99a.png)
EHAM
![image](https://user-images.githubusercontent.com/9995998/196113199-959b0299-1d2f-471b-8f0b-ef30f109a730.png)
CYVR
![image](https://user-images.githubusercontent.com/9995998/196113282-f2c65467-a975-474e-96e6-911294e54149.png)
I checked and the data isn't even in the BGL files.

The issue is with the default data. You will have to report this to Microsoft.

**Comment by tracernz** [comment]
This is fixed in SU11, so probably no point reporting it actually.

**Comment by patmack14** [comment]
Ok thanks Mike.
