### ISSUE TITLE
NAV&LOGO light problem

### ISSUE THREAD

**Issue by FoxMulder1974** [flybywiresim/a32nx#7874]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-03-12T02:18:53+00:00",
    "ref": "refs/heads/master",
    "sha": "f1bf742950278be4d4c226a01ae72d8a7af2246d",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:f1bf7429",
    "version": "v0.10.0-dev.f1bf742"
}
```

### Describe the bug

when the aircraft reach cruise FL, nav and logo light turn off.

### Expected behavior

at cruise level, watch out and the NAV&LOGO light are ON

### Steps to reproduce

1. start aircraft and set on NAV&LOGO light
2. watch out and the NAV&LOGO light are ON
3. takeoff and climb
4. at cruise level, watch out and the NAV&LOGO light are OFF

### Additional info (optional)

1. i'm able to reprodure the problem everytime
2. i'm using a default livery

**Comment by lirondco** [comment]
![image](https://user-images.githubusercontent.com/60845154/225669529-a14fb782-aa1c-472f-a857-5c996e7adf38.png)

Could you maybe post a picture? The nav lights are expected to stay on during cruise (red and green lights on tip of wings) however the logo lights are expected to turn off after full retraction of flaps and they turn back on when you extend flaps during approach.  

Unless if your nav lights turn off during cruise, this is expected behavior.

**Comment by tracernz** [comment]
Also check that you don't have LVFR mods or anything like that installed (try A32NX with nothing else in the community directory), and no keybinds/external tools that interfere with lights. There have been zero other reports of this issue and nobody can reproduce it, so closing for now. Re-open if the issue persists after the above.
