### ISSUE TITLE
Armed FMAs not working properly

### ISSUE THREAD

**Issue by popa676** [flybywiresim/a32nx#7988]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-01-08T23:16:53+00:00",
    "ref": "HEAD",
    "sha": "81a8ee3a2e03a24da13cc0bcc4cf3a7d51f188a6",
    "actor": "Saschl <sascharudolf46@gmail.com>",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.9.1"
}
```

### Describe the bug

Hello,

I have problem with A32NX_FMA_LATERAL_ARMED and A32NX_FMA_VERTICAL_ARMED variables.

They don't show the right value how it is written in docs.

You can try it when spawning on runway on pfd there will be CLB, but the VERTICAL_ARMED var will output G/S.

And also VERTICAL_ARMED variable sometimes outputs value that is not written in docs, was 16 or 17 wich was indicating ALT G/S on PFD

I need that variables because i'm fip gauges developer, for example if i want make A320 PFD, i design images and then write a code wich needs variables of course.

### Expected behavior

I expected it to work properly

### Steps to reproduce

When i started coding Flight mode annunciators for my A320 PFD i encountered this issue with only armed FMAs.

### Additional info (optional)

when contacting on discord me send me friend request, i have dms disabled for not friend users

### Discord Username (optional)

PΩPA15_CZ#7435

**Comment by beheh** [comment]
This is not a bug. The `A32NX_FMA_LATERAL_ARMED ` and `A32NX_FMA_VERTICAL_ARMED` simvars contain a bitmask, as mentioned in [a320-simvars.md](https://github.com/flybywiresim/a32nx/blob/master/fbw-a32nx/docs/a320-simvars.md). This is because multiple modes can be armed at the same time. You will have to [decode the bitmasks](https://abdulapopoola.com/2016/05/30/understanding-bit-masks/) to get the armed modes.
