### ISSUE TITLE
[BUG] Chronometer continues when using pause

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/a32nx#804]
**Mod Version**

Master

**Describe the bug**

I did a flight from EKCH to ENAL (approx. 1 hour and 30 minutes) and the chronometer showed me 2 hours and 38 minutes. I paused my flight for about an hour or so, so it seems that when you pause the sim (ESC) the chronometer does not stop.

**To Reproduce**

1. Start a flight with the chronometer
2. Pause the flight for a while
3. Continue and check the values of the chronometer

**Expected behavior**

I would expect the chronometer to stop when you pause your flight.

**Actual behavior**

The chromometer does not stop and therefore does not give an accurate value.

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by theersink** [comment]
The only way to actually stop time within the sim is pause simulation under Dev mode options menu. This is an Asobo thing, not just this mod.

**Comment by NathanInnes** [comment]
If you're using active pause then that's why. Active pause is intended to keep the simulation running but the aircraft will be stuck in place as time passes.

**Comment by theersink** [comment]
Even with the "real" pause solution it will still tick time. Try using the keystroke while watching the chronometer. It will continue to run. Dev mode option is the only one that will stop time altogether. In addition the Dev mode pause is the only one that simconnect and FSUIPC will detect as a pause for 3rd party apps.

**Comment by ErikNL80** [comment]
Why is the label 'working as intended' added without any comment? I simply do not agree.

**Comment by theersink** [comment]
Asobo are the only ones who can change this. Use the dev mode pause to stop time. Until if/when Asobo decides to change the pause functionality there is nothing that can be done and it is working as intended by Asobo in the simulator. It is coded that way and not a bug with the modded aircraft. It occurs in any aircraft.

**Comment by ErikNL80** [comment]
Ok, clear. It does not have a huge priority, but would be a nice to have...

**Comment by UncleClapton** [comment]
> Why is the label 'working as intended' added without any comment? I simply do not agree.
Because I unfortunately got distracted with another issue while writing my response. X_X

The chronometer uses in-game time to measure time passage, which will continue to run even under active pause. Unfortunately there's no real time measurement system that accounts for active pause. As mentioned above the developer pause DOES pause the game as most would expect pause to work. I argue this isn't a real solution, but there's nothing the mod can do to change the logic around that.

It's worth noting this is a problem in other planes, too. We may re-address this in the future, but this is how it was intended to work.
