### ISSUE TITLE
battery at zero

### ISSUE THREAD

**Issue by papouk16** [flybywiresim/a32nx#8065]
### Aircraft Version

Development

### Build info

```json
"built": "2023-06-07T18:54:43+00:00",
    "ref": "refs/heads/master",
    "sha": "050575b62f6dca4d612fb1b532564a0b9c2a52e0",
    "actor": "lukecologne",
    "event_name": "manual",
    "pretty_release_name": "master:050575b6",
    "version": "v0.10.0-dev.050575b"
```

### Describe the bug

hello, I join the club of those who have the battery indicators at zero on the overhead, I did the update this morning, I am with the development version 050575b, yesterday everything was working fine and today, more nothing works without battery.
I did the "UT8F keyboard" manipulation in the regional settings but it doesn't change anything
help, without your A 320, I am nothing...
thanks
best regards
I'm on windows 10
flight sim by steam

### Expected behavior

attempt to uninstall/reinstall
no change, including switching with the stable version

### Steps to reproduce

the battery charge indicators are both at zero

### Discord Username (optional)

papouk16

**Comment by MjrIncident** [comment]
It is the same for me since yesterdays update

**Comment by papouk16** [comment]
let's hope they fix this mega bug quickly, I think many of us will report this bug...

**Comment by MjrIncident** [comment]
cannot stream til they do lol

**Comment by 20CCAA07** [comment]
I noted the same issue today but on the stable version instead:

```
{
    "built": "2023-05-15T13:42:40+00:00",
    "ref": "refs/tags/v0.10.0",
    "sha": "b0b83346027796b7526415ff8aa13b726308bf36",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.10.0",
    "version": "v0.10.0-rel.b0b8334"
}
```

It's quite odd because a few days ago, all was fine and afaik there was no update in between.

**Comment by BlueberryKing** [comment]
Thank you for the reports everyone. We are investigating the issue. We suspect that this is happening because Windows flags one of the files contained in the update as a virus. While it is likely that this is a false positive, we want to confirm this first.

Some team members note that the file is no longer flagged with the latest version of Windows Defender. It would therefore be very helpful to us if you could try updating your Windows Defender version and report back to us whether you are still running into the issue. The latest version as of today is 1.391.860.0. If you don't know how to update Windows Defender, please have a look at the documentation here:

![image](https://github.com/flybywiresim/a32nx/assets/22713769/5d99ca49-699d-40ed-991e-e9aec84c35b9)

(from https://learn.microsoft.com/en-us/mem/intune/user-help/turn-on-defender-windows#update-your-antivirus-definitions)

Thanks for the help!

**Comment by MjrIncident** [comment]
I used Security Intelligence veriosn 1.391.877.0
Upon test power is back and screens etc - thankyou :-)

**Comment by papouk16** [comment]
Good morning
I have version 1.391.919.0 for virus and threat protection, and it says that this version is up to date
THANKS
Have a good day
Cordially

**Comment by 20CCAA07** [comment]
Good Morning,

I have updated Windows Defender to version 1.391.919.0 (09.06.2023, 04:05) and checked the A320 again. Unfortunately, the batteries still stay at 0V and all displays remain dark (even with external power on) with the stable version:

```
{
    "built": "2023-05-15T13:42:40+00:00",
    "ref": "refs/tags/v0.10.0",
    "sha": "b0b83346027796b7526415ff8aa13b726308bf36",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.10.0",
    "version": "v0.10.0-rel.b0b8334"
}
```
Can this issue please be reopened?

**Comment by papouk16** [comment]
hello, on my side, I uninstalled FBW via the content manager of fs 2020, I checked windows defender, OK, and I reinstalled the development version and the batteries work now
to be continued
