### ISSUE TITLE
[BUG] All aircraft systems turn off when activating AP1 on initial climb

### ISSUE THREAD

**Issue by bwarren109** [flybywiresim/a32nx#884]
**Mod Version**
Master

**Describe the bug**
After a cold/dark start per checklist, pressing AP1 during initial climb causes aircraft systems to fail. Includes electrical, avionics, flight controls and engines.

**To Reproduce**
Complete startup procedure/taxi/takeoff roll per the checklist. Try to activate AP1 after rotation and initial climb.

**Expected behavior**
Autopilot should respond based on flight parameters and either activate or not. 
Aircraft should not turn off and fly directly into the Missouri River.

**Actual behavior**
All aircraft systems turn off, including electrical, avionics, flight controls, engines, etc. Glass panels immediately turn dark, lights turn off, controls do not function, engines fail.

**Additional Context**
- Does not occur after spawning on runway, all other conditions the same.
- Flight plan created by the sim
- Occurs without warning i.e. no Master Warning, EICAS warnings, etc.

Was this working before/when did the issue start occurring?
Has not been a problem before.

Is this a problem in the vanilla unmodded game?
No.

Discord username, if different from GitHub: ThisIsBrandon

**Comment by tareksabet** [comment]
Hi, can you tell us on which master version are you on plus can you provide us with screenshots concerning the issue.

**Comment by bwarren109** [comment]
It was on version: 675aff3115.
I'll download the newest version and try to replicate and get some screenshots.

**Comment by Tom-Joad** [comment]
Hello, i just wanted to say that i had nearly the same behaviour with version [4954a4d](https://github.com/flybywiresim/a32nx/commit/4954a4d842f40e72773d1e83da68bfc1c1b8d392)
Altough i was still on the ground and did not activate the Autopilot.
Battery Voltages showed 25.4 and i could not power up the Aircraft again even with External Power.
Everything just went completely dark. A ingame Restart later and about 10 Minutes in the same Problem happened again.
Went to main menu and this time let it spawn on the runway instead of the gates.
This time nothing happened for the entire flight.

**Comment by bwarren109** [comment]
I downloaded b1368d2 yesterday, started up today, and I can't get it get to happen again.
Although maybe there are issues with external power/batteries? That seems to be popping up in a couple reports.

**Comment by tareksabet** [comment]
@bwarren109 closing it at seems not to be reproduced after the latest updates.
