### ISSUE TITLE
[BUG] Wrong Display Unit color (Blue effect )

### ISSUE THREAD

**Issue by flythebest** [flybywiresim/a32nx#924]
**Mod Version**
 

0.3.0 Master

**Describe the bug**

Not really a bug but the blue effect of the Display Units do not exist in reality. This is a camera effect, nothing more.

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Actual behavior**

**References**

This is how it should look :

https://transport-photo.com/photo/106/Night-cockpit.html

https://transport-photo.com/photo/100/Night-landing.html

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Pleasure0102** [comment]
i do agree it looks weird, hopefully someone will tweak that a bit, @AdenFlorian might wanna check that, i don't know

**Comment by Benjozork** [comment]
We have had multiple IRL A320 pilots confirm that the backlight effect does exist, so we will not remove it. It is not a camera effect.

The intensity can be tweaked though.

**Comment by Pleasure0102** [comment]
Yeah I think he is referring to the color not the effect itself. Which of can be tweaked

**Comment by flythebest** [comment]
> We have had multiple IRL A320 pilots confirm that the backlight effect does exist, so we will not remove it. It is not a camera effect.
> 
> The intensity can be tweaked though.

Black light effect sure but it do not give you this blue color at all.
And if you don't want to change this, at least, let people tweak the color...

**Comment by Benjozork** [comment]
> Black light effect sure but it do not give you this blue color at all.

Do you have experience in an A320 cockpit and / or simulator ?

> And if you don't want to change this, at least, let people tweak the color...

The purpose of this mod is to faithfully recreate the A320. Introducing options for every detail is a slippery slope. We will be more than happy to tweak the color effect but it will not be removed, because as I said, we have had multiple pilots confirm it does exist.

**Comment by flythebest** [comment]
So just for your information, I'm an A320 pilot, this is my office so I'm giving you my opinion as a professional.
If you want to take this feedback into consideration that's great otherwise don't ask feedback from pilots...

Another point, if you find an A320 pilot that confirm this blue color coming from the DU's, I would be more than happy to speack with him !

**Comment by Benjozork** [comment]
Please then specify your experience when you ask for features or report issues. You have no idea how many bogus reports we get from people that ask for things to be changed and have no experience with any A320. You need to specify what your basis is for your reasoning. We don't know you're a pilot. We can't guess that.

May I ask for your Discord username so that we can verify your role ?

I'll be asking other pilots and we can possibly discuss this on Discord to reach a consensus.

We do want to take feedback, but posting an issue on GitHub requires strong references, which you didn't provide initially.

**Comment by Pleasure0102** [comment]
@flythebest he did not mean anything bad. We should definitely check how we can make it more realistic and pilot feedback is always appreciated. Remember he does not knew you are a pilot until you mentioned it. And we do get a lot of people saying they want something changed because they just don't like it. I know you were a pilot because I asked you to post it here

**Comment by flythebest** [comment]
> May I ask for your Discord username so that we can verify your role ?

Who are you to ask me to justify myself ?? What else do you need ? My logbook and my license's number ? Are you jocking or what ? 
I don't earn anything by helping you  so at least stay correct please.

**Comment by mrsprouse** [comment]
> > May I ask for your Discord username so that we can verify your role ?
> 
> Who are you to ask me to justify myself ?? What else do you need ? My logbook and my license's number ? Are you jocking or what ?
> I don't earn anything by helping you so at least stay correct please.

What is the issue with verifying you are a pilot? If you already have the role on the discord, then you have already sent the required info. All we want is your discord username so we can verify that you are the same person on discord. Don't get defensive about it.

**Comment by flythebest** [comment]
flythebest is my discord name. I reported the issue here ( as requested by Pleasure0102 ) just to make things easier. But this discussion already started in the "pilot feedback" section on discord. 
So here, when I say something ( because the cockpit of the A320 is my office and I'm not here asking for a favor to change a thing in particular)  instead of saying that you won't change anything ,  instead of asking if I have any experience ont the A320 or in the sim and instead of asking me my name to VERIFY my role, this guy should be a little bit more correct with people that try to help  you reach your goal and for free. That's all I'm saying.

**Comment by ukflyer** [comment]
Hi guys, 
Here's a video of a good representation of the night lighting. I hope it helps. The blue backlight does seem to vary depending upon camera position ..

https://www.youtube.com/watch?v=Mo7A3CuVb8g&t=105s

**Comment by hotshotp** [comment]
already tweaked to be more dim and pleasant
