### ISSUE TITLE
Won't follow the planned route since lastest 1.9.3.0 update [BUG]

### ISSUE THREAD

**Issue by dmajestic80** [flybywiresim/a32nx#992]
**Mod Version**

0.3.1

**Describe the bug**

When flying a planned route in managed mode the aircraft will start banking off course. Then when trying to correct by using selected mode it does not work, the aircraft will continue the bank until stall or manual control is taken. I have done about 100 hours using the mod before the latest update and never had this issue. I've now encountered this several times since the update and using the latest mod.

**To Reproduce**

1. Start any flight with a planned route
2. Fly in managed mode as per usual 
3. Within minutes the aircraft will start to bank off course with no other input.

**Expected behavior**

To stay on the planned route

**Actual behavior**

As described above

**References**

**Additional context**

Was this working before/when did the issue start occurring? No issues prior to 1.9.3.0 update

Is this a problem in the vanilla unmodded game? I haven't encountered this issue using the unmodded game

Discord username (if different from GitHub):

**Comment by randidiot** [comment]
I have had this problem tonight also.

**Comment by Superlister97** [comment]
I have this also to

**Comment by XiaNaphryz** [comment]
Just started a long 4+ hour flight about 35 min ago and the autopilot appears to be following the set flight path. I imported a .PLN file from SimBrief for this recent flight to create the route.

Note that I have all air traffic disabled and/or set to 0 (multiplayer, AI, real world, and ground). I've had these settings for a few weeks now ever since we saw the early reports of other aircraft system values overriding the player's aircraft soon after the previous MSFS patch went up. Perhaps this issue is still there and causing the autopilot issue?

**Comment by lionomega** [comment]
Same problem

**Comment by Remy737** [comment]
same problem here

**Comment by AndLindemann** [comment]
Not sure if that is related, but my AP in managed ALT mode also refuses to climb. ATHR stays on SPEED instead of THRST CLB and there is no ALT indicator on the FMC. Triggering managed ALT mode again shortly flashes the ALT indicator, but then it goes off again.
After the Aircraft has passed the first WP, managed ALT mode begins to work.

**Comment by dmajestic80** [comment]
> 
> 
> Just started a long 4+ hour flight about 35 min ago and the autopilot appears to be following the set flight path. I imported a .PLN file from SimBrief for this recent flight to create the route.
> 
> Note that I have all air traffic disabled and/or set to 0 (multiplayer, AI, real world, and ground). I've had these settings for a few weeks now ever since we saw the early reports of other aircraft system values overriding the player's aircraft soon after the previous MSFS patch went up. Perhaps this issue is still there and causing the autopilot issue?

I've just tested using vanilla a320 and turned off all the above you mentioned and there was no issue sticking to the planned route. Next I will test same conditions but this time adding the latest mod.

**Comment by donstim** [comment]
There is something going on with all the reports of this issue on different media, but I have all live traffic and multiplayer on, ai traffic on generic, but other players off generic and have never experienced this issue.

**Comment by ErikNL80** [comment]
With the latest version of the Master everything seems to be working again. Maybe some other users can check as well?
